<?php 
	if(isset($_REQUEST["opcion"])){
		Flash::notice("Doble Click en la Fila para ".$_REQUEST["opcion"]); 
	}
?>
<table id="tabla<?php echo Router::getController(); ?>"></table>
<div id="pager<?php echo Router::getController(); ?>"></div>
<script>
jQuery(document).ready(function(){
	
		jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Id','Nombre'], 
			colModel:[ 
				{ name:'id',index:'id', width:100},
				{ name:'nombre',index:'nombre', width:400}
			], 
			autoWidth:true,
			/**width: 550,**/
			width: jQuery('#content').width()-25,
			height: 250,
			rowNum:50, 
			/*rowList:[10,20,30,40,50], */
			pager: '#pager<?php echo Router::getController(); ?>', 
			sortname: 'id', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"LISTADO DE TIPOS DE DOCUMENTOS",
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					if( jQuery("#id")    ){ jQuery("#id").val(fila['id']); }
					if( jQuery("#nombre") ){ jQuery("#nombre").val(fila['nombre']); } 
					if( jQuery("#logo") ){ jQuery("#logo").val(fila['logo']); } 
					if( jQuery("#ancho") ){ jQuery("#ancho").val(fila['ancho']); } 
					if( jQuery("#alto") ){ jQuery("#alto").val(fila['alto']); } 
					if( jQuery("#size") ){ jQuery("#size").val(fila['size']); } 
					if( jQuery("#font") ){ jQuery("#font").val(fila['font']); } 
					if( jQuery("#tipo_letra") ){ jQuery("#tipo_letra").val(fila['tipo_letra']); } 
					if( jQuery("#papel") ){ jQuery("#papel").val(fila['papel']); } 
					
					<?php if(isset($_REQUEST["opcion"]) ){ ?>
					redireccionar_action("<?php echo Router::getController(); ?>/<?php echo $_REQUEST["opcion"]; ?>/"+fila['id'] );
					<?php }else{?>	
						jQuery("#dialogo_<?php echo Router::getController(); ?>").dialog("close");
					<?php } ?>
						
				}
		});
		 
		/*jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navGrid','#pager<?php //echo Router::getController(); ?>',{edit:false,add:false,del:false}); 
		jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navButtonAdd','#pager<?php //echo Router::getController(); ?>',{
		caption: "Columnas",
		title: "Reordena Columnas",
		onClickButton : function (){
			jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('columnChooser');
		
	});}*/
	jQuery(window).bind('resize', function() {
			jQuery("#tabla<?php echo Router::getController(); ?>").setGridWidth(jQuery('#content').width()-25, true);
	});
	
});
</script>