<!--Formulario para configurar el regimen-->

<?php echo Tag::form("regimen/add","id: regimen") ?>

<table border="0" cellpadding="1">
    <tr>
   	 <th colspan="4" scope="col">CONFIGURE REGIMEN</th>
    </tr>
  <tr>
    <td width="19%" height="30" >REGIMEN</td>
    <td width="43%" scope="col"><?php echo Tag::textField("descripcion", "size: 30","maxlength: 20") ?></td>
    <td width="21%" scope="col">&nbsp;</td>
    <td width="17%" scope="col">&nbsp;</td>
  </tr>
  <tr>
    <td height="30" colspan="4"><?php echo Tag::submitButton('Agregar', 'id: guardar', 'name: guardar') ?></tr>
</table>

<?php echo Tag::endForm() ?>