<?php echo Tag::image("logo_softdes.png","border: 0","style: float:left","width: 75px"); ?>
<font size="-2">
<a href="http://www.softdesignermonteria.net">SoftDesignerMonteria.net</a>
Correos: <a href="mailto:administrador@softdesignermonteria.net">Alejandro Betancourt</a>  y  <a href="mailto:erwin.gulfo@softdesignermonteria.net">Erwin Gulfo</a>
:Copyright (C) 2014 - Ing. Alejandro Betancourt e Ing. Erwin Gulfo - <a href="https://www.gnu.org/licenses/gpl.html">Licencia Pública General de GNU</a>
</font>
