<?php echo Tag::image("logo_dydsoluciones_350_105.png","border: 0","style: float:left","width: 125px"); ?>
<font size="-1">
<a href="http://www.dydsoluciones.net">DyDSoluciones.net</a>
Correos: <a href="mailto:alejandro.betancourt@dydsoluciones.net">Alejandro Betancourt</a>  y  <a href="mailto:erwin.gulfo@dydsoluciones.net">Erwin Gulfo</a>
:Copyright (C) 2014 - Ing. Alejandro Betancourt e Ing. Erwin Gulfo - <a href="https://www.gnu.org/licenses/gpl.html">Licencia Pública General de GNU</a>
</font>
