<link rel="stylesheet" type="text/css" href="<?php echo core::getInstancePath(); ?>css/error.css">
<link rel="stylesheet" href="<?php echo core::getInstancePath(); ?>javascript/development-bundle/themes/redmond/jquery.ui.all.css">
<link rel="stylesheet" href="<?php echo core::getInstancePath(); ?>javascript/development-bundle/demos/demos.css">
<link rel="stylesheet" href="<?php echo core::getInstancePath(); ?>javascript/timepicker/jquery-ui-timepicker-addon.css">
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo core::getInstancePath(); ?>javascript/jqgrid/css/ui.jqgrid.css" />
<link rel="stylesheet" href="<?php echo core::getInstancePath(); ?>javascript/chosen_v1.1.0/chosen.css">

<link rel="stylesheet" type="text/css" href="<?php echo core::getInstancePath(); ?>javascript/Responsive-Tabs-master/css/responsive-tabs.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo core::getInstancePath(); ?>javascript/Responsive-Tabs-master/css/style.css"/>

<style>
.ui-autocomplete-loading { background: white url('<?php echo core::getInstancePath(); ?>/public/img/ui-anim_basic_16x16.gif') right center no-repeat; }
</style>
<style>
.ui-progressbar .ui-progressbar-value { background-image: url('<?php echo core::getInstancePath(); ?>/public/img/pbar-ani.gif'); }
</style>
<?php  
	Tag::addJavascript('core/base-source');
	//Tag::addJavascript('core/calendar');
	//Tag::addJavascript('core/calendar-source');
	Tag::addJavascript('core/validator');
	Tag::addJavascript('core/validations');
	Tag::addJavascript('core/base');
	Tag::addJavascriptFramework('scriptaculous');
	Tag::addJavascript('development-bundle/jquery-1.9.1');
	//Tag::addJavascriptFramework('prototype');
	echo Tag::getJavascriptLocation();
	echo Tag::javascriptSources();
?>

<script src="<?php echo core::getInstancePath(); ?>javascript/modernizr.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery-ui.custom.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.datepicker.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.accordion.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.autocomplete.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.button.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.core.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.dialog.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.draggable.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.droppable.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.mouse.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.position.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.progressbar.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.resizable.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.selectable.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.slider.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.sortable.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.tabs.min.js"></script>
<script src="<?php echo core::getInstancePath(); ?>javascript/development-bundle/ui/minified/jquery.ui.widget.min.js"></script>
<script  src="<?php echo core::getInstancePath(); ?>javascript/timepicker/jquery-ui-timepicker-addon.js"></script>
<script  src="<?php echo core::getInstancePath(); ?>javascript/jqgrid/js/i18n/grid.locale-es.js" ></script>
<script  src="<?php echo core::getInstancePath(); ?>javascript/jqgrid/js/jquery.jqGrid.min.js" ></script>
<script  src="<?php echo core::getInstancePath(); ?>javascript/jqgrid/src/grid.celledit.js" > </script>


<script  src="<?php echo core::getInstancePath(); ?>javascript/jstree-v.pre1.0/jquery.jstree.js" > </script>
<script  src="<?php echo core::getInstancePath(); ?>javascript/chosen_v1.1.0/chosen.jquery.min.js" > </script>

<script  src="<?php echo core::getInstancePath(); ?>javascript/Responsive-Tabs-master/js/jquery.responsiveTabs.min.js" > </script>

<!--JS cargar webcam-->
<!--<script  src="<?php //echo core::getInstancePath(); ?>javascript/fotos/assets/js/jquery.min.js"></script>-->
<!--<script  src="<?php //echo core::getInstancePath(); ?>javascript/fotos/assets/fancybox/jquery.easing-1.3.pack.js" > </script>
<script  src="<?php //echo core::getInstancePath(); ?>javascript/fotos/assets/fancybox/jquery.fancybox-1.3.4.pack.js" > </script>-->
<script  src="<?php echo core::getInstancePath(); ?>javascript/webcam/webcam.js" > </script>
<!--<script  src="<?php //echo core::getInstancePath(); ?>javascript/fotos/assets/js/script.js" > </script>-->

<script>

jQuery(document).ready(function(){

	

	jQuery(".content2").find("input,section,textarea").attr("class","ui-widget ui-widget-content ui-corner-all");

	jQuery(".content2").find("input,section,textarea").css("height","25px");

	jQuery(".content2").find("table").attr("cellpadding","2");

	jQuery(".content2").find("table").attr("cellspacing","2");

	//jQuery(".content2").find("select").attr("class","ui-widget ui-widget-content ui-corner-all");
	
	jQuery(".content2").find("table").attr("class","ui-widget ui-widget-content ui-corner-all");

	
	jQuery(".content2").find("td").css("height","25px");

	jQuery(".content2").find("thead").attr("class","ui-widget ui-widget-content ui-corner-all ui-dialog-titlebar ui-widget-header ui-helper-clearfix ui-front");

	//ui-widget ui-widget-content ui-corner-all ui-dialog-titlebar ui-widget-header ui-helper-clearfix ui-front

	jQuery(".content2").find("th").css("height","30px");

	//jQuery(".content2").find("select").attr("class","text ui-widget-content ui-corner-all");

	jQuery(".content2").find("result").attr("class","ui-widget ui-widget-content ui-corner-all");

	jQuery(".content2").find("h4").attr("class","ui-widget ui-widget-content ui-corner-all ui-widget-header ui-icon-circle-arrow-e");

	jQuery(".content2").find("h1").attr("class","ui-widget ui-widget-content ui-corner-all ui-widget-header ui-icon-circle-arrow-e");

	jQuery(".content2").find(".result").attr("style","width: 500px;");

	
});

function UploadFileOk(url){
	jQuery("#archivos").val(url);
	
}


function uploadFileFunction(){ 


	var archivos = document.getElementById("archivosxls"); //Damos el valor del input tipo file
	var archivo = archivos.files; //Obtenemos el valor del input (los arcchivos) en modo de arreglo
	/* Creamos el objeto que hara la petición AJAX al servidor, debemos de validar 
		si existe el objeto “ XMLHttpRequest” ya que en internet explorer viejito no esta, 
	y si no esta usamos “ActiveXObject” */
	 if(window.XMLHttpRequest) {  
		 var Req = new XMLHttpRequest(); 
	 }else if(window.ActiveXObject) {  
		 var Req = new ActiveXObject("Microsoft.XMLHTTP");  
	 } 
		//El objeto FormData nos permite crear un formulario pasandole clave/valor para poder enviarlo,  \n";
		//este tipo de objeto ya tiene la propiedad multipart/form-data para poder subir archivos \n";
	var data = new FormData();
		//Como no sabemos cuantos archivos subira el usuario, iteramos la variable y al \n";
		//objeto de FormData con el metodo \"append\" le pasamos calve/valor, usamos el indice \"i\" para \n";
		//que no se repita, si no lo usamos solo tendra el valor de la ultima iteración \n";
	for(i=0; i<archivo.length; i++){
	   data.append('archivo'+i,archivo[i]); console.log(archivo[i]); 
	} 
	//Pasándole la url a la que haremos la petición \n";
	Req.open("POST", "<?php echo core::getInstancePath(); ?>clientes_temp/upload", true); 
	/* Le damos un evento al request, esto quiere decir que cuando termine de hacer la petición, \n";
	se ejecutara este fragmento de código */  
	Req.onload = function(Event) { 
		//Validamos que el status http sea ok \n";
		if (Req.status == 200) {  
		  //Recibimos la respuesta de php 
		  var msg = Req.responseText; 
		  jQuery("#cargados").append(msg); 
		} else {  
		  console.log(Req.status); //Vemos que paso. 
		}  
	}; 
		 //Enviamos la petición  \n";
 	Req.send(data) 
} 


</script>



<script>



function redireccionar_action(url){

		var url = "<?php echo core::getInstancePath(); ?>"+url; 

		jQuery(location).attr('href',url); 

	}
	

function doccancelar(v,p){

		var url = v+p; 

		jQuery(location).attr('href',url); 

	}	

function quitar_mensajes(){
		jQuery(".kumbiaDisplay").fadeOut(2000, function () {
		  jQuery(this).remove();
		  jQuery('#fx').each (function(){
			  this.reset();
			});
		});
	}

function aplicar_css(nombre){

		jQuery("."+nombre).find("input,section,textarea").attr("class","ui-widget ui-widget-content ui-corner-all");

		jQuery("."+nombre).find("input,section,textarea").css("height","25px");

		jQuery("."+nombre).find("table").attr("cellpadding","2");

		jQuery("."+nombre).find("table").attr("cellspacing","2");

		jQuery("."+nombre).find("select").attr("class","ui-widget ui-widget-content ui-corner-all");

		jQuery("."+nombre).find("table").attr("class","ui-widget ui-widget-content ui-corner-all");

		jQuery("."+nombre).find("td").css("height","25px");

		jQuery("."+nombre).find("thead").attr("class","ui-widget ui-widget-content ui-corner-all ui-dialog-titlebar ui-widget-header ui-helper-clearfix ui-front");

		jQuery("."+nombre).find("th").css("height","30px");

		jQuery("."+nombre).find("h4").attr("class","ui-widget ui-widget-content ui-corner-all ui-widget-header ui-icon-circle-arrow-e");

		jQuery("."+nombre).find("h1").attr("class","ui-widget ui-widget-content ui-corner-all ui-widget-header ui-icon-circle-arrow-e");

	

	}	
	



	function buscar_dialogo(controlador,opc,valor){

					jQuery("#dialogo_"+controlador).html("");
					//alert(opc);
					var datos = "";

					jQuery.ajax({

						type:"POST"

						,url:"<?php echo core::getInstancePath(); ?>"+controlador+"/find_buscar/"

						,async:true

						,data:{
								opcion: opc,
								valor: valor
							}

						,success: function(data){

								jQuery("#dialogo_"+controlador).html(data);

								jQuery("#dialogo_"+controlador).dialog("open");

							}

						,error: function(data){

								jQuery("#dialogo_"+controlador).html("Error Cargando este Elemento" + data);

								jQuery("#dialogo_"+controlador).dialog("open");

							}	

					});		


		}
		
		function validar(controlador,opcion,valor){
					jQuery("#dialogo_mensajes").html("");
					var datos = "";
					jQuery.ajax({
						type:"POST"
						,url:"<?php echo core::getInstancePath(); ?>"+controlador+"/validar/"+valor+"/"+opcion
						,async:true
						
						,success: function(data){
								jQuery("#mensajes").html(data);
							  }
						,error: function(data){
								jQuery("#dialogo_mensajes").html("Error Cargando este Elemento" + data);
								jQuery("#dialogo_mensajes").dialog("open");
							  }	
					});		
		}
		
	
		function buscar_archivos(campo){
					
					controlador='clientes_temp';
					
					jQuery("#dialogo_"+controlador).html("");
					//alert(opc);
					var datos = "";

					jQuery.ajax({

						type:"POST"

						,url:"<?php echo core::getInstancePath(); ?>clientes_temp/buscar_archivos/?campo="+campo

						,async:true

						,success: function(data){

								jQuery("#dialogo_"+controlador).html(data);

								jQuery("#dialogo_"+controlador).dialog("open");

							}

						,error: function(data){

								jQuery("#dialogo_"+controlador).html("Error Cargando este Elemento");

								jQuery("#dialogo_"+controlador).dialog("open");

							}	

					});		


		}
		
	function buscar_upload(campo){
					
					controlador='clientes_temp';
					
					jQuery("#dialogo_"+controlador).html("");
					//alert(opc);
					var datos = "";

					jQuery.ajax({

						type:"POST"

						,url:"<?php echo core::getInstancePath(); ?>clientes_temp/buscar_upload/?campo="+campo

						,async:true

						,success: function(data){

								jQuery("#dialogo_"+controlador).html(data);

								jQuery("#dialogo_"+controlador).dialog("open");

							}

						,error: function(data){

								jQuery("#dialogo_"+controlador).html("Error Cargando este Elemento");

								jQuery("#dialogo_"+controlador).dialog("open");

							}	

					});		


		}
		
	
		
function tableToJson(table) {
    var data = [];

    // first row needs to be headers
    var headers = [];
    for (var i=0; i<table.rows[0].cells.length; i++) {
        headers[i] = table.rows[0].cells[i].innerHTML.toLowerCase().replace(/ /gi,'');
    }

    // go through cells
    for (var i=1; i<table.rows.length; i++) {

        var tableRow = table.rows[i];
        var rowData = {};

        for (var j=0; j<tableRow.cells.length; j++) {

            rowData[ headers[j] ] = tableRow.cells[j].innerHTML;

        }

        data.push(rowData);
    }       

    return data;
}



function solonumeros(obj){
	patron = /[^0-9]/;
	var s = obj.value;
	obj.value = s.replace(patron,'');
}


function validar_cliente(){
		
		jQuery("#clientes_id").val();
		controlador = "mensajes";
		
		var datos = "";

					jQuery.ajax({

						type:"POST"

						,url:"<?php echo core::getInstancePath(); ?>solicitud/validar/"+jQuery("#clientes_id").val()

						,async:true

						,data:{
								opcion: true
							}

						,success: function(data){

								jQuery("#dialogo_"+controlador).html(data);

								jQuery("#dialogo_"+controlador).dialog("open");

							}

						,error: function(data){

								jQuery("#dialogo_"+controlador).html("Error Cargando este Elemento" + data);

								jQuery("#dialogo_"+controlador).dialog("open");

							}	

					});		

		
	}
	
	
	function valor_credito(){
		    
			var numero_cuotas=jQuery("#numero_cuotas").val();
			var valor_cuota=jQuery("#valor_cuota").val();
			
			if(numero_cuotas=='' || valor_cuota==''){
					
					jQuery("#error").css("display","inline");
					jQuery(".kumbiaDisplay").fadeOut(7000, function () {
					jQuery(this).remove();
					
					jQuery('#loader').each (function(){
						
					});
				});
					
				}else{
					jQuery("#loader").css("display","inline");
			
					  jQuery(".kumbiaDisplay").fadeOut(5000, function () {
					  jQuery(this).remove();
					  
					  jQuery('#loader').each (function(){
					  
					  });
					});
					
					var total_credito=numero_cuotas*valor_cuota;
			        jQuery("#total_credito").val(total_credito);
					
				}
	}
	
	
	function capturar_huella(){
		jQuery("#dialogo_huellas").html("");
			jQuery.ajax({

						type:"POST"

						,url:"<?php echo core::getInstancePath(); ?>huellas/"

						,async:true

						,data:{
								opcion: true
							}

						,success: function(data){
								
								jQuery("#dialogo_huellas").html(data);

								jQuery("#dialogo_huellas").dialog("open");

							}

						,error: function(data){

								jQuery("#dialogo_"+controlador).html("Error Cargando este Elemento" + data);

								//jQuery("#dialogo_"+controlador).dialog("open");

							}	

					});		

		
	}
	
	

</script>

	

    