<?php echo Tag::formRemote(Router::getController()."/add", "update: mensajes", "id: fx","name: fx"); ?>

<h1>AGREGAR <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?></h1>

<table width="100%">

      <tr>
    	  <th height="25" colspan="4">FORMULARIO PARA AGREGAR <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?></th>
   	  </tr>
    	<tr>
    	  
    	  <th width="30%" align="right">CODIGO:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textField("id","size: 50","maxlength: 50"); ?></td>
    	  
   	  </tr>
        <tr>
    	  <th width="30%" align="right" >NOMBRE:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textField("departamento","size: 50","placeholder: Nombre Departamento"); ?></td>
   	  </tr>
      <tr>
    	  <td colspan="4" align="center"><button id="guardar" name="guardar" >Guardar</button></td>
   	  </tr>
  </table>

<?php echo Tag::endForm(); ?>
<div id="mensajes"></div>
<?php echo view::getContent(); ?>

<script>
/*campos requeridos*/
jQuery(document).ready(function(e) {
	
   <?php 
		$entidad = new Departamentos();
		
		foreach( $entidad->getPrimaryKeyAttributes() as $filas):
			echo "jQuery(\"#$filas\").attr(\"readonly\",\"readonly\");\n";
		endforeach;	
		
		foreach( $entidad->getNonPrimaryKeyAttributes() as $filas):
				foreach( $entidad->getNonPrimaryKeyAttributes() as $filas2):
					if($filas==$filas2){ echo "jQuery(\"#$filas2\").attr(\"required\",\"required\");\n"; break;} 
				endforeach;	
				
		endforeach;	
		
	?> 
});


</script>