

<table width="100%">
	<tr>
    	<th>EMPRESA</th>
        <th>DESCRIPCION</th>
        <th>PREFIJO</th>
        <th>RESOLUCION DIAN</th>
        <th>FECHA</th>
        <th>ACTIVO</th>
        <th>DOCUMENTO</th>
     
        <th>MODIFICAR</th>
	</tr>
<?php //$cons = new DetalleConsecutivos(); ?>
<?php 
/*
  id,
  prefijo,
  desde,
  hasta,
  resolucion_dian,
  fecha,
  activo,
  consecutivos_id,
  tipo_documento_id
*/
$query = new ActiveRecordJoin(array(
						"entities" => array("DetalleConsecutivos","Empresa","TipoDocumento"),
						"fields" => array(
						
						"{#Empresa}.nombre_empresa",
						"{#DetalleConsecutivos}.descripcion",
						"{#DetalleConsecutivos}.id",
						"{#DetalleConsecutivos}.prefijo",
						"{#DetalleConsecutivos}.resolucion_dian",
						"{#DetalleConsecutivos}.fecha",
						"{#DetalleConsecutivos}.activo",
						"{#DetalleConsecutivos}.desde",
						"{#DetalleConsecutivos}.hasta",
						
						"{#DetalleConsecutivos}.tipo_documento_id",
						"{#TipoDocumento}.nombre"
						),
						"conditions" => "{#DetalleConsecutivos}.empresa_id = '".Session::get("id_empresa")."'"
						
				));

foreach($query->getResultSet() as $cons):	
				
?>

	<tr>
    	<td><?php echo $cons->nombre_empresa; ?></td>
        <td><?php echo $cons->descripcion; ?></td>
        <td><?php echo $cons->prefijo; ?></td>
        <td><?php echo $cons->resolucion_dian; ?></td>
        <td><?php echo $cons->fecha; ?></td>
       
        <td><?php echo $cons->activo; ?></td>
        <td><?php echo $cons->nombre; ?></td>
     
        <td align="center"><?php echo Tag::linkTo("consecutivos/modificar/$cons->id",Tag::image("64x64/Edit.png","width: 25px"));?></td>
	</tr>
    
<?php endforeach; ?>
</table>


<?php echo View::getContent(); ?>