<h4>FORMULARIO AGREGAR CONSECUTIVOS AL SISTEMA</h4>

<?php echo Tag::formRemote("consecutivos/add", "update: mensajes", "id: fx","name: fx"); ?>

<table width="80%" border="0" align="center" cellpadding="1">
<tr>
  <td height="0">&nbsp;</td>
  <td width="19%" height="0" align="right">DESCRIPCION</td>
  <td width="58%" height="0"><?php echo Tag::textUpperField("descripcion", "size: 50","maxlength: 50") ?></td>
  <td width="13%" height="0">&nbsp;</td>
</tr>
<tr>
  <td height="0">&nbsp;</td>
    <td height="0" align="right">FECHA</td>
    <td height="0"><?php echo Tag::textField("fecha") ?></td>
    <td height="0">&nbsp;</td>
</tr>
<tr>
  <td height="0">&nbsp;</td>
  <td height="0" align="right">PREFIJO</td>
  <td height="0"><?php echo Tag::textUpperField("prefijo", "size: 10","maxlength: 10") ?></td>
  <td height="0">&nbsp;</td>
</tr>
<tr>
  <td height="0">&nbsp;</td>
  <td height="0" align="right">DESDE</td>
  <td height="0"><?php echo Tag::numericField("desde2", "size: 15","maxlength: 15") ?></td>
  <td height="0">&nbsp;</td>
</tr>
<tr>
  <td height="0">&nbsp;</td>
  <td height="0" align="right">HASTA</td>
  <td height="0"><?php echo Tag::numericField("hasta2", "size: 15","maxlength: 15") ?></td>
  <td height="0">&nbsp;</td>
</tr>
<tr>
  <td height="0">&nbsp;</td>
  <td height="0" align="right">RESOLUCION DIAN</td>
  <td height="0"><?php echo Tag::textField("resolucion_dian", "size: 40","maxlength: 50") ?></td>
  <td height="0">&nbsp;</td>
</tr>
<tr>
  <td height="0">&nbsp;</td>
  <td height="0" align="right">TIPO DOCUMENTO</td>
  <td height="0"><?php 
  		$tp = new TipoDocumento();
  echo Tag::select("tipo_documento_id",$tp->find("empresa_id = '".Session::get("id_empresa")."'"),'using: id,nombre','useDummy=yes' ) ?></td>
  <td height="0">&nbsp;</td>
</tr>
<tr>
  <td height="0">&nbsp;</td>
  <td height="0" align="right">ACTIVO</td>
  <td height="0"><?php echo Tag::selectStatic("activo",array("0"=>"SI","1"=>"NO")) ?></td>
  <td height="0">&nbsp;</td>
</tr>
<tr>
  <td height="0">&nbsp;</td>
  <td height="0" align="right">&nbsp;</td>
  <td height="0">&nbsp;</td>
  <td height="0">&nbsp;</td>
</tr>
<tr>
    <td height="0" colspan="4" align="center"><button type="submit" id="guardar" name="guardar">Guardar</button>
     <button type="button" id="cancelar" name="cancelar" onclick="doccancelar('<?php echo core::getInstancePath(); ?>','<?php echo Router::getController(); ?>');">Cancelar</button>
    </td>
</tr>    
</td>
</table>

<div id="mensajes">



</div>

<?php echo Tag::endForm() ?>

