<table id="tabla<?php echo Router::getController(); ?>"></table>
<div id="pager<?php echo Router::getController(); ?>"></div>
<script>
jQuery(document).ready(function(){

		
		jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Id','Nombre','Logo','Ancho','Alto','Tamaño Fuente','Tipo Fuente','Papel'], 
			colModel:[ 
				{ name:'id',index:'id', width:200},
				{ name:'nombre',index:'nit', width:200}, 
				{ name:'logo',index:'nombre1', width:500},
				{ name:'ancho',index:'nombre2', width:200}, 
				{ name:'alto',index:'apellido1', width:200}, 
				{ name:'size',index:'apellido2', width:200},
				{ name:'font',index:'apellido2', width:200},
				{ name:'tipo_letra',index:'apellido2', width:200},
				{ name:'papel',index:'apellido2', width:200}
			], 
			autoWidth:true,
			width: 550,
			height: 250,
			rowNum:50, 
			/*rowList:[10,20,30,40,50], */
			pager: '#pager<?php echo Router::getController(); ?>', 
			sortname: 'id', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"LISTADO DE TIPOS DE DOCUMENTOS",
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					if( jQuery("#id")    ){ jQuery("#id").val(fila['nit']); }
					if( jQuery("#nombre") ){ jQuery("#nombre").val(fila['nombre']); } 
					if( jQuery("#logo") ){ jQuery("#logo").val(fila['logo']); } 
					if( jQuery("#ancho") ){ jQuery("#ancho").val(fila['ancho']); } 
					if( jQuery("#alto") ){ jQuery("#alto").val(fila['alto']); } 
					if( jQuery("#size") ){ jQuery("#size").val(fila['size']); } 
					if( jQuery("#font") ){ jQuery("#font").val(fila['font']); } 
					if( jQuery("#papel") ){ jQuery("#papel").val(fila['papel']); } 
					
					
					jQuery("#id").val("");
					jQuery("#nombre").val("");
					jQuery("#logo").val("");
					jQuery("#ancho").val("");
					jQuery("#alto").val("");
					jQuery("#font").val("");
					jQuery("#tipo_letra").val("");
					jQuery("#papel").val("");
								
					jQuery("#id").val(fila['id']);
					//jQuery("#clientes").val(fila['nombre1']+' '+fila['nombre2']+' '+fila['apellido1']+' '+fila['apellido2']);

					jQuery("#dialogo_<?php echo Router::getController(); ?>").dialog("close");
					
       		 }
		});
		 
		/*jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navGrid','#pager<?php //echo Router::getController(); ?>',{edit:false,add:false,del:false}); 
		jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navButtonAdd','#pager<?php //echo Router::getController(); ?>',{
		caption: "Columnas",
		title: "Reordena Columnas",
		onClickButton : function (){
			jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('columnChooser');
		
	});}*/
});
</script>