<?php 
	if(isset($_REQUEST["opcion"])){
		Flash::notice("Doble Click en la Fila para ".$_REQUEST["opcion"]); 
	}
?>
<div id="div_modal_<?php echo Router::getController(); ?>">
  <table id="filtros" width="100%" class="ui-corner-all ui-content">
    <thead>
        <tr class="ui-jqgrid-titlebar ui-widget-header  ">
            <th colspan="2">Filtros</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th align="right">Identificacion</th>
          <td align="left"><input type="number" id="nit" name="nit" size="30"  />
          <strong>Busqueda por Nombre</strong>
          <input type="text" id="nombre" name="nombre" size="50" /></td>
      </tr>
        <tr>
            <th align="right">Numero Recibo</th>
          <td align="left">
          <input type="number" id="numero" name="numero" size="10"  />
          <strong>Valor</strong>
          <input type="text" id="valor" name="valor" size="10" />
          <strong>Desde</strong>
          <input type="text" id="desde" name="desde" size="10"  />
          <strong>Hasta</strong>
          <input type="text" id="hasta" name="hasta" size="10" />
          </td>
      </tr>
         <tr>
            <th colspan="2" align="center"><button type="button" id="buscar" name="buscar">Filtrar</button></th>
      </tr>
    </tbody>
    </table>
    <table id="tabla<?php echo Router::getController(); ?>"></table>
    <div id="pager<?php echo Router::getController(); ?>"></div>
</div>
<script>
jQuery(document).ready(function(){
			
			jQuery("#buscar").click(function() {
				//alert("entro");
				jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid('setGridParam',{ 
					postData:{ 
								nit:       jQuery("#nit").val(), 
								nombre:    jQuery("#nombre").val(), 
								numero:    jQuery("#numero").val(), 
								valor:     jQuery("#valor").val(), 
								desde:     jQuery("#desde").val(), 
								hasta:     jQuery("#hasta").val(), 
								nit:       jQuery("#nit").val()
							 } 
				}).trigger('reloadGrid');
			});
		
		jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Id','Identificacion','Nombre Completo','Fecha','Numero Recibo Caja','Valor'], 
			colModel:[ 
				{ name:'id',index:'id', width:200},
				{ name:'nit',index:'nit', width:200}, 
				{ name:'nombre_completo',index:'apellido1', width:500},
				{ name:'fecha',index:'fecha', width:200}, 
				{ name:'consecutivo',index:'consecutivo', width:200}, 
				{ name:'total',index:'total', width:200, align:"right", formatter: 'number' }
			], 
			autoWidth:true,
			width: jQuery('#content').width()-25,
			height: 300,
			rowNum:25, 
			/*rowList:[10,20,30,40,50], */
			pager: '#pager<?php echo Router::getController(); ?>', 
			sortname: 'id', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"LISTADO DE CLIENTES",
			footerrow : true,
			userDataOnFooter : true, 
			
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					/*if( jQuery("#nit")    ){ jQuery("#nit").val(fila['nit']); }
					if( jQuery("#nombre1") ){ jQuery("#nombre1").val(fila['nombre1']); } 
					if( jQuery("#nombre2") ){ jQuery("#nombre2").val(fila['nombre2']); } 
					if( jQuery("#apellido1") ){ jQuery("#apellido1").val(fila['apellido1']); } 
					if( jQuery("#apellido2") ){ jQuery("#apellido2").val(fila['apellido2']); } */
					
					<?php if(isset($_REQUEST["opcion"]) ){ ?>
					redireccionar_action("<?php echo Router::getController(); ?>/<?php echo $_REQUEST["opcion"]; ?>/"+fila['id'] );
					<?php }else{?>	
						jQuery("#dialogo_<?php echo Router::getController(); ?>").dialog("close");
					<?php } ?>
					
       		 }
		}); 
		/*jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navGrid','#pager<?php //echo Router::getController(); ?>',{edit:false,add:false,del:false}); 
		jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navButtonAdd','#pager<?php //echo Router::getController(); ?>',{
		caption: "Columnas",
		title: "Reordena Columnas",
		onClickButton : function (){
			jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('columnChooser');
		
	});}*/
	jQuery(window).bind('resize', function() {
			jQuery("#tabla<?php echo Router::getController(); ?>").setGridWidth(jQuery('#content').width()-25, true);
	});
});
</script>