<?php 
	if(isset($_REQUEST["opcion"])){
		Flash::notice("Doble Click en la Fila para ".$_REQUEST["opcion"]); 
	}
?>
<div id="div_modal_<?php echo Router::getController(); ?>">

    <table id="filtros" width="100%" class="ui-corner-all ui-content">
    <thead>
        <tr class="ui-jqgrid-titlebar ui-widget-header  ">
            <th colspan="2">Filtros</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>Codigo</th>
            <td><?php  echo Tag::textFieldExt("cobradores","size: 8"); ?></td>
        </tr>
        <tr>
            <th>Fecha</th>
            <td>
            	<input type="text" id="desde" name="desde" size="20" />
                Hasta
                <input type="text" id="hasta" name="hasta" size="20" />
            </td>
        </tr>
        <tr>
        	<td colspan="2" align="center"><button id="buscar" name="buscar">Buscar</button></td>
        </tr>
    </tbody>
    </table>
    <table id="tabla<?php echo Router::getController(); ?>"></table>
    <div id="pager<?php echo Router::getController(); ?>"></div>
</div>
<script>
jQuery(document).ready(function(){
			
			/*jQuery("#codigo_departamento").keyup(function() {
				//alert("entro");
				jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('setGridParam',{ 
					postData:{ 
								nombre:     jQuery("#nombre_departamento").val(), 
								codigo:     jQuery("#codigo_departamento").val()
							 } 
				}).trigger('reloadGrid');
			});
			
			jQuery("#nombre_departamento").keyup(function() {
				//alert("entro");
				jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('setGridParam',{ 
					postData:{ 
								codigo:     jQuery("#codigo_departamento").val(), 
								nombre:     jQuery("#nombre_departamento").val()
							 } 
				}).trigger('reloadGrid');
			});*/
		
		jQuery("#buscar").click(function() {
				//alert("entro");
				jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid('setGridParam',{ 
					postData:{ 
								cobradores_id: jQuery("#cobradores_id").val(), 
								desde:         jQuery("#desde").val(), 
								hasta:         jQuery("#hasta").val()
							 } 
				}).trigger('reloadGrid');
			});	
		
		jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Codigo','Nombre','Fecha','Valor'],
			colModel:[ 
				{ name:'id',index:'id', width:50}, 
				{ name:'razon_social',index:'razon_social', width:300}, 
				{ name:'fecha',index:'fecha', width:100},
				{ name:'valor',index:'valor', width:200} 
			], 
			autoWidth:true,
			width: jQuery('#content').width()-25,
			height: 250,
			rowNum:20, 
			/*rowList:[10,20,30,40,50], */
			pager: '#pager<?php echo Router::getController(); ?>', 
			sortname: 'fecha', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"listado de los Adelantos de Caja Diario",
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					//if( jQuery("#departamentos_id")    ){ jQuery("#departamentos_id").val(fila['departamentos_id']); }
					//if( jQuery("#departamentos") ){ jQuery("#departamentos").val(fila['departamento']); } 
					
					<?php if(isset($_REQUEST["opcion"]) ){ ?>
						redireccionar_action("<?php echo Router::getController(); ?>/<?php echo $_REQUEST["opcion"]; ?>/" + fila['id'] );
					<?php }else{?>	
						jQuery("#dialogo_<?php echo Router::getController(); ?>").dialog("close");
					<?php } ?>
					
       		 }
		}); 
		
		jQuery(window).bind('resize', function() {
			jQuery("#tabla<?php echo Router::getController(); ?>").setGridWidth(jQuery('#content').width()-25, true);
	});
		
});
</script>