<?php 
	if(isset($_REQUEST["opcion"])){
		Flash::notice("Doble Click en la Fila para ".$_REQUEST["opcion"]); 
	}
?>
<div id="div_modal_<?php echo Router::getController(); ?>">
    <table id="filtros" width="100%" class="ui-corner-all ui-content">
    <thead>
        <tr class="ui-jqgrid-titlebar ui-widget-header  ">
            <th colspan="2">Filtros</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>Username</th>
            <td><input type="text" id="username" name="username" size="50"  /></td>
        </tr>
        <tr>
            <th>Busqueda por Nombre</th>
            <td><input type="text" id="nombre_completo" name="nombre_completo" size="50" /></td>
        </tr>
    </tbody>
    </table>
    <table id="tabla<?php echo Router::getController(); ?>"></table>
    <div id="pager<?php echo Router::getController(); ?>"></div>
</div>
<script>
jQuery(document).ready(function(){
		
		jQuery("#username").keyup(function() {
				//alert("entro");
				jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid('setGridParam',{ 
					postData:{ 
								username:     		jQuery("#username").val(), 
								nombre_completo:     jQuery("#nombre_completo").val()
							 } 
				}).trigger('reloadGrid');
			});
			
			jQuery("#nombre_completo").keyup(function() {
				//alert("entro");
				jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid('setGridParam',{ 
					postData:{ 
								username:        	jQuery("#username").val(), 
								nombre_completo:     jQuery("#nombre_completo").val()
							 } 
				}).trigger('reloadGrid');
			});
		
		jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Id','Username','Nombre Completo','Tipo de usuario','Id Cobrador'], 
			colModel:[ 
				{ name:'id',index:'id', width:200},
				{ name:'username',index:'username', width:200}, 
				{ name:'nombre_completo',index:'nombre_completo', width:500},
				{ name:'tipo_usuario',index:'tipo_usuario', width:200}, 
				{ name:'cobradores_id',index:'cobradores_id', width:200}
			], 
			autoWidth:true,
			width: jQuery('#content').width()-25,
			height: 250,
			rowNum:50, 
			/*rowList:[10,20,30,40,50], */
			pager: '#pager<?php echo Router::getController(); ?>', 
			sortname: 'id', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"LISTADO DE USARIOS DEL SISTEMA",
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					if( jQuery("#id")    ){ jQuery("#id").val(fila['id']); }
					if( jQuery("#username") ){ jQuery("#username").val(fila['username']); } 
					if( jQuery("#nombre_completo") ){ jQuery("#nombre_completo").val(fila['nombre_completo']); } 
					if( jQuery("#tipo_usuario") ){ jQuery("#tipo_usuario").val(fila['tipo_usuario']); } 
					if( jQuery("#cobradores_id") ){ jQuery("#cobradores_id").val(fila['cobradores_id']); } 
					
					<?php if(isset($_REQUEST["opcion"]) ){ ?>
					redireccionar_action("<?php echo Router::getController(); ?>/<?php echo $_REQUEST["opcion"]; ?>/?id="+fila['id'] );
					<?php }else{?>	
						jQuery("#dialogo_<?php echo Router::getController(); ?>").dialog("close");
					<?php } ?>
					
       		 }
		});
		 
		/*jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navGrid','#pager<?php //echo Router::getController(); ?>',{edit:false,add:false,del:false}); 
		jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navButtonAdd','#pager<?php //echo Router::getController(); ?>',{
		caption: "Columnas",
		title: "Reordena Columnas",
		onClickButton : function (){
			jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('columnChooser');
		
	});}*/
	
	jQuery(window).bind('resize', function() {
			jQuery("#tabla<?php echo Router::getController(); ?>").setGridWidth(jQuery('#content').width()-25, true);
	});
	
});
</script>