<?php echo Tag::formRemote(Router::getController()."/update", "update: mensajes", "id: fx","name: fx"); ?>

<h1>MOFIFICAR <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?></h1>

<h4>
	<?php echo $tipo_documento; 
	echo " - "; 
	echo $tipo_documento_id; 
	echo "EMPRESA: ".Tag::textField("nombre_empresa","size: 30","readOnly: readOnly","style: background: #cccccc;"); ?>
</h4>

<table width="100%" border="0" align="center" cellpadding="2" cellspacing="4">

   <tr>
     
     <td align="right"><div align="right">CLIENTE:</div></td>
     
     <td align="left" valign="middle" id="aclientes">
        <?php echo Tag::hiddenField("id"); ?> 

		<?php echo Tag::hiddenField("tipo_documento_id"); ?> 

        <?php echo Tag::hiddenField("empresa_id"); ?> 

        <?php echo Tag::hiddenField("prefijo"); ?> 

        <?php echo Tag::hiddenField("consecutivo"); ?> 
      <?php echo Tag::textFieldExt("clientes","size: 30"); ?>
   </tr>
   
   <tr>

    <td align="right" valign="top">CREDITO</td>

    <td><?php echo Tag::textFieldExt("creditos","size: 30"); ?></td>

  </tr>


  <tr>

    <td align="right" valign="top">FECHA</td>

    <td><?php echo Tag::textField("fecha","size: 20"); ?></td>

  </tr>


 
    
     <tr>
       <td align="right" valign="top">BANCO</td>
       <td>
	   		<?php echo Tag::textUpperField("banco","size: 30","maxlenth: 100"); ?>
			 CHEQUE: 
			<?php echo Tag::textUpperField("cheque","size: 30","maxlenth: 100"); ?>
       </td>
     </tr>
    
 <tr>

    <td align="right" valign="top">OBSERVACIONES</td>

    <td><?php echo Tag::textArea("observaciones","size: 20"); ?></td>

    </tr>

</table>

<div id="detalles_items" style="display:none;"></div>

<table id="grid_<?php echo Router::getController(); ?>"></table>

<div id="pag<?php echo Router::getController(); ?>"></div>

<button id="agregar_item" type="button">Agregar</button>

<button id="intereses_item" type="button" style="display:none;">Calcular Intereses</button>

<button id="modificar_item" type="button">Modificar</button>

<button id="borrar_item" type="button">Borrar</button>

 <br />


<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" id="f3">

  <tr>

    <td width="50%">&nbsp;</td>

    <th align="right">TOTAL </th>

    <td><?php echo Tag::numericField("total","size: 50","readonly: readonly"); ?></td>

  </tr>

</table>

	<div align="center">

    	<button id="guardar" type="button">Guardar</button>

        <button id="cancelar" type="button">Cancelar</button>

    </div>



<p>&nbsp;</p>


<?php echo Tag::endForm(); ?>
<div id="mensajes"></div>
<?php echo view::getContent(); ?>

<div title="Agergar Cuotas" id="dialogo_agregar_item_cxc">
	<table id="tablacxc"></table>
	<div id="pagercxc"></div>
</div>


<div title="Agergar Cuota" id="dialogo_agregar_item">
		
</div>


<div title="Agergar Cuota" id="dialogo_agregar_intereses">
	
</div>


<div title="Modificar Cuota" id="dialogo_modificar_item">
    <table width="70%" cellpadding="2" cellspacing="2" align="center">
       <tr>
   	      <td>Id</td>
           <td colspan="2">
           		<input type="text"  id="tmp_id_mod" name="tmp_id_mod" size="10" readonly="readonly" />
           		<input type="hidden"  id="tmp_codigo_mod" name="tmp_codigo_mod" size="10" readonly="readonly" />
                <input type="hidden"  id="tmp_detalle_cxc_mod" name="tmp_detalle_cxc_mod" size="10" readonly="readonly" />
          </td>
        </tr>
       <tr>
			<td>FECHA VENCIMIENTO</td>
			<td colspan="2"><input type="text"  id="tmp_vencimiento_mod"  name="tmpint_vencimiento_mod" readonly="readonly" value="<?php echo Date("YY-mm-dd"); ?>" /></td>
        </tr>
         <tr>
			<td>DESCRIPCION</td>
			<td colspan="2"><input type="text"  id="tmp_descripcion_mod"  name="tmpint_descripcion_mod"  readonly="readonly" value="INTERESES" /></td>
        </tr>
        <tr>
			<td>VALOR CUOTA</td>
			<td colspan="2"><input type="text"  id="tmp_valor_mod"  name="tmp_valor_mod"/></td>
        </tr>
    </table>
</div>


<script type="text/javascript">

var detalles = [];


function agregar_item(data){

var existe = false;   
for(i=0;i<detalles.length;i++) {  

	if (detalles[i]["detalle_cxc_id"] == data["detalle_cxc_id"]) {  

	   alert("Ojo no se Puede bajar La misma cuota 2 Veces");  

	   existe = true;  

	 }   

 }  

if (!existe) {  
	//value = parseFloat(jQuery.trim(jQuery("#total").val()));
	detalles.push(
		{
			 id              :data["id"]
			,detalle_cxc_id  :data["detalle_cxc_id"]
			,codigo          :data["codigo"]
			,numero_credito  :data["numero_credito"]
			,descripcion     :data["descripcion"]
			,valor           :data["valor"]
			,vencimiento     :data["vencimiento"]
			,anulado: "NO"

		}

	);
	
	//value += parseFloat(data["valor"]);
	//jQuery("#total").val(value);
	jQuery("#detalles_items").html(JSON.stringify(detalles));
	reload_grid();

}  



}



function agregar_item_intereses(data){

var existe = false;   
for(i=0;i<detalles.length;i++) {  

	if (detalles[i]["descripcion"] == 'INTERESES' && detalles[i]["anulado"]=='NO' ) {  

	   alert("Ojo si necesita agregar mas Intereses modifiquelo");  

	   existe = true;  

	 }   

 }  

if (!existe) {  
	//value = parseFloat(jQuery.trim(jQuery("#total").val()));
	detalles.push(
		{
			 id              :data["id"]
			,detalle_cxc_id  :data["detalle_cxc_id"]
			,codigo          :data["codigo"]
			,numero_credito  :data["numero_credito"]
			,descripcion     :data["descripcion"]
			,valor           :data["valor"]
			,vencimiento     :data["vencimiento"]
			,anulado: "NO"

		}

	);
	
	//value += parseFloat(data["valor"]);
	//jQuery("#total").val(value);
	jQuery("#detalles_items").html(JSON.stringify(detalles));
	reload_grid();

}  



}


function reload_grid(){

	jQuery("#grid_<?php echo Router::getController(); ?>").jqGrid('setGridParam',

		{ 	datatype: 'local',

			data:detalles

		}).trigger("reloadGrid");
	totalizar();
}



//agregar un item al vector json de items

function modificar_item(data,mod_id){
	
	for(i=0;i<detalles.length;i++){
			if(detalles[i].id==mod_id){
				if(detalles[i].anulado=='NO'){
					detalles[i].id                = data["id"];
					detalles[i].detalle_cxc_id    = data["detalle_cxc_id"];
					detalles[i].codigo            = data["codigo"];
					detalles[i].numero_credito    = data["numero_credito"];
					detalles[i].descripcion       = data["descripcion"];
					detalles[i].valor             = data["valor"];
					detalles[i].vencimiento       = data["vencimiento"];
					detalles[i].anulado           = data["anulado"];
				}else{
					jQuery("#dialogo_mensajes").html("");
					jQuery("#dialogo_mensajes").html("Ojo No se Puede Modificar por que ya esta anulado");
					jQuery("#dialogo_mensajes").dialog("open");
				}
			
			}

	}

	reload_grid();
	
}

function totalizar(){
	var total = 0;
	for(i=0;i<detalles.length;i++) {  
		if(detalles[i].anulado=='NO'){
			total += parseFloat(detalles[i].valor);	
		}
	}
	jQuery("#total").val(total);
}

jQuery(document).ready(function(){
	


	jQuery("#clientes_id").val("<?php echo $clientes_id; ?>");
	jQuery("#creditos_id").val("<?php echo $creditos_id; ?>");
	
	if( jQuery( "#buscar_item"     ) ){ jQuery( "#buscar_item"        ).button({ icons: {primary:'ui-icon ui-icon-circle-check' ,secondary:'ui-icon-triangle-1-s'}       });   }
	if( jQuery( "#intereses_item"     ) ){ jQuery( "#intereses_item"        ).button({ icons: {primary:'ui-icon ui-icon-circle-check' ,secondary:'ui-icon-triangle-1-s'}       });   }
	if( jQuery( "#agregar_item"     ) ){ jQuery( "#agregar_item"        ).button({ icons: {primary:'ui-icon ui-icon-circle-check' ,secondary:'ui-icon-triangle-1-s'}       });   }
	if( jQuery( "#modificar_item"    ) ){ jQuery( "#modificar_item"       ).button({ icons: {primary:'ui-icon ui-icon-circle-check' ,secondary:'ui-icon-triangle-1-s'}       });   }
	if( jQuery( "#borrar_item"   ) ){ jQuery( "#borrar_item"      ).button({ icons: {primary:'ui-icon ui-icon-circle-minus' ,secondary:'ui-icon ui-icon-closethick'} });   }

	
 <?php 
		$entidad = new RecibosCaja();
		
		foreach( $entidad->getPrimaryKeyAttributes() as $filas):
			echo "jQuery(\"#$filas\").attr(\"readonly\",\"readonly\");\n";
		endforeach;	
		
		foreach( $entidad->getNonPrimaryKeyAttributes() as $filas):
				foreach( $entidad->getNonPrimaryKeyAttributes() as $filas2):
					if($filas==$filas2){ echo "jQuery(\"#$filas2\").attr(\"required\",\"required\");\n"; break;} 
				endforeach;	
				
		endforeach;	
		
	?> 	

/*inicializamos variable local*/
//var detalles = [];


/*--------------------------------------------Guardar <?php echo Router::getController(); ?> Especiales--------------------------------------------------------------*/

jQuery("#guardar").click(function(){
		guardar_compra();
});

function guardar_compra(){
	var datos = "";
	var srv = JSON.stringify(detalles);
	//datos = jQuery("#compras").serialize();
	jQuery( "#progressbar" ).progressbar({ value: 50 });	
		//$('#resumen').html('Cargando....');
		var jqXHR = jQuery.ajax({
			type: "POST",
			url: "<?php echo core::getInstancePath(); ?><?php echo Router::getController(); ?>/update",
			data: {
					id:                 jQuery("#id").val(),
					tipo_documento_id:  jQuery("#tipo_documento_id").val(),
					empresa_id:         jQuery("#empresa_id").val(),
					prefijo:            jQuery("#prefijo").val(),
					consecutivo:        jQuery("#consecutivo").val(),
					clientes_id:        jQuery("#clientes_id").val(),
					creditos_id:        jQuery("#creditos_id").val(),
					fecha:              jQuery("#fecha").val(),
					observaciones:      jQuery("#observaciones").val(),
					banco:              jQuery("#banco").val(),
					cheque:             jQuery("#cheque").val(),
					detalles: srv
			},

			success: function(data) {
				jQuery( '#mensajes' ).html("");
				jQuery( "#progressbar" ).progressbar({ value: 90 });
				jQuery( '#mensajes' ).html(data);

			},

			error: function(data) {
				jQuery('#dialogo_mensajes').html("Error Enviando parametros.....");
				jQuery( "#progressbar" ).progressbar({ value: 0 });
				jQuery('#dialogo_mensajes').dialog("open");
			}
		});

		 jqXHR.done(function(data){
			jQuery( "#progressbar" ).progressbar({ value: 0 });
		});

}





/*--------------------------------------------------Agregar item---------------------------------------------------------------------------------*/


	jQuery("#dialogo_agregar_item_cxc").dialog(
		{ 
			autoOpen:false
			, width:600 
			, heigth:400 
			,modal: true
			,buttons:[
				{
					text:  "Cerrar"
					,click: function(){
								
							jQuery(this).dialog("close"); 
							
						}	
				}
			]
		});
		
		
/*		
jQuery("#agregar_item").click(function(){
	
	if( jQuery("#fecha_cierre").val()!='' ){
		
		reload_grid2();
		jQuery("#dialogo_agregar_item_cxc").dialog("open");
		
	}else{
			jQuery("#dialogo_mensajes").html("");
			jQuery("#dialogo_mensajes").html("Fecha Cierre es Requerido");
			jQuery("#dialogo_mensajes").dialog("open");
	}

});		
	*/	


 jQuery("#agregar_item").click(function(e){
	 e.preventDefault();
	 jQuery("#tmp_id_mod").val();
	 jQuery("#tmp_codigo_mod").val();
	 jQuery("#tmp_descripcion_mod").val();
	 jQuery("#tmp_detalle_cxc_mod").val();
	 jQuery("#tmp_valor_mod").val();
	 jQuery("#tmp_vencimiento_mod").val();
	if( jQuery("#clientes_id").val() != '' && jQuery("#creditos_id").val() != '' ){
		
		
		
		var jqXHR = jQuery.ajax({
				url:"<?php echo core::getInstancePath(); ?>detalle_cxc/find_buscar/",
				type:"POST",

				data:{
						clientes_id:  jQuery("#clientes_id").val(),
						creditos_id:  jQuery("#creditos_id").val()
					},
					fail:function(){
						alert("error");
					},
					error:function(jqXHR,textStatus,errorThrown){
						alert("error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
					}
		});

		 jqXHR.done(function(data){
			//agregar_item(data);
			jQuery("#dialogo_agregar_item").html("");	
			jQuery("#dialogo_agregar_item").html(data);
			jQuery("#dialogo_agregar_item").dialog("open");
		});
	
		//reload_grid();
	}else{
		jQuery("#dialogo_mensajes").html("");
		jQuery("#dialogo_mensajes").html("Por Favor escoja un Cliente y un Credito Valido");
		jQuery("#dialogo_mensajes").dialog("open");
	}
});


jQuery("#intereses_item").click(function(e){
	 e.preventDefault();
	if( jQuery("#clientes_id").val() != '' && jQuery("#creditos_id").val() != '' ){
		
		var jqXHR = jQuery.ajax({
				url:"<?php echo core::getInstancePath(); ?>notas_credito/agregar_intereses/",
				type:"POST",

				data:{
						clientes_id:  jQuery("#clientes_id").val(),
						creditos_id:  jQuery("#creditos_id").val(),
						fecha:        jQuery("#fecha").val(),
					},
					fail:function(){
						alert("error");
					},
					error:function(jqXHR,textStatus,errorThrown){
						alert("error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
					}
		});

		 jqXHR.done(function(data){
			//agregar_item(data);
			jQuery("#dialogo_agregar_intereses").html("");	
			jQuery("#dialogo_agregar_intereses").html(data);
			jQuery("#dialogo_agregar_intereses").dialog("open");
		});
	
		//reload_grid();
	}else{
		jQuery("#dialogo_mensajes").html("");
		jQuery("#dialogo_mensajes").html("Por Favor escoja un Cliente y un credito Valido");
		jQuery("#dialogo_mensajes").dialog("open");
	}
});



/*	 

//autocomplete con json	

jQuery( "#tmp_valor" ).autocomplete({

	source: "<?php// echo core::getInstancePath(); ?>kardex/autocompletejson",

	minLength: 2,

	select: function( event, ui ) {

		 //alert("Has seleccionado: " + ui.item.value);

		 jQuery("#tmp_valor").val(ui.item.value)

		 jQuery("#tmp_codigo").val(ui.item.id);

		 jQuery("#tmp_codigo").val(ui.item.codigo);

	}

});

*/	


jQuery("#dialogo_agregar_item").dialog(

{ 

	autoOpen:false
	, width:600 
	, heigth:400 
	,modal: true
	,buttons:[
		{
			text:  "Escoger"
			,click: function(){
					var jqXHR = jQuery.ajax({
							url:"<?php echo core::getInstancePath(); ?><?php echo Router::getController(); ?>/agregar_item/",
							type:"POST",
							dataType:"json",
							data:{
									codigo:        jQuery("#tmp_codigo").val(),
									valor:         jQuery("#tmp_valor").val(),
									vencimiento:   jQuery("#tmp_vencimiento").val(),
								},
								fail:function(){
									alert("error");
								},
								error:function(jqXHR,textStatus,errorThrown){
									alert("error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
								}
					});

					 jqXHR.done(function(data){
						agregar_item(data);
					});

					jQuery(this).dialog("close"); 

				}	

		}

	]

});



jQuery("#dialogo_agregar_intereses").dialog(

{ 

	autoOpen:false
	, width:600 
	, heigth:400 
	,modal: true
	,buttons:[
		{
			text:  "Cerrar"
			,click: function(){
					jQuery(this).dialog("close"); 
			}	

		},
		{
			text:  "Escoger"
			,click: function(){
					var jqXHR = jQuery.ajax({
							url:"<?php echo core::getInstancePath(); ?><?php echo Router::getController(); ?>/agregar_item/",
							type:"POST",
							dataType:"json",
							data:{
									descripcion:   jQuery("#tmpint_descripcion").val(),
									codigo: jQuery("#tmpint_codigo").val(),
									valor:  jQuery("#tmpint_valor").val(),
									vencimiento:   jQuery("#tmpint_vencimiento").val(),
								},
								fail:function(){
									alert("error");
								},
								error:function(jqXHR,textStatus,errorThrown){
									alert("error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
								}
					});

					 jqXHR.done(function(data){
						agregar_item(data);
					});

					jQuery(this).dialog("close"); 

				}	

		}
		

	]

});

/*-----------------------------------------------------modificar item----------------------------------------------------------------------------*/



//cuadro de dialogo de agregar item...	 

jQuery("#modificar_item").click(function(){
	 jQuery("#tmp_id_mod").val();
	 jQuery("#tmp_codigo_mod").val();
	 jQuery("#tmp_descripcion_mod").val();
	 jQuery("#tmp_detalle_cxc_mod").val();
	 jQuery("#tmp_valor_mod").val();
	 jQuery("#tmp_vencimiento_mod").val();

		toMod = jQuery("#grid_<?php echo Router::getController(); ?>").jqGrid('getGridParam','selrow');

		var sw = 0;

		for(i=0;i<detalles.length;i++){

			if(detalles[i].id==toMod){

				//alert("Lo Encontre: "+detalles[i].id + " SUBSTRING TEMP " + detalles[i].id.substring(0,4));

				if( detalles[i].anulado == "SI" ){

					alert("Elemento Anulado no se Puede Modificar");

					sw=1;

				}else{
					//alert("liena guardada en la base de datos anular");
					jQuery("#tmp_id_mod").val(detalles[i].id);
					jQuery("#tmp_detalle_cxc_mod").val(detalles[i].detalle_cxc_id);
					jQuery("#tmp_codigo_mod").val(detalles[i].codigo);
					jQuery("#tmp_valor_mod").val(detalles[i].valor);
					jQuery("#tmp_descripcion_mod").val(detalles[i].descripcion);
					jQuery("#tmp_vencimiento_mod").val(detalles[i].vencimiento);
					sw=0;

				}

			}

		}

		

		if(sw==0){

			jQuery("#dialogo_modificar_item").dialog("open");

		}

	//reload_grid();

});



	

jQuery("#dialogo_modificar_item").dialog(

{ 
	autoOpen:false
	, width:600 
	, heigth:400 
	,modal: true
	,buttons:[
		{
			text:  "Escoger"
			,click: function(){
					var mod_id =         jQuery("#tmp_id_mod").val();
					
					var jqXHR = jQuery.ajax({

							url:"<?php echo core::getInstancePath(); ?><?php echo Router::getController(); ?>/agregar_item/",
							type:"POST",
							dataType:"json",
							data:{
									id:             jQuery("#tmp_id_mod").val(),
									codigo:         jQuery("#tmp_codigo_mod").val(),
									detalle_cxc_id: jQuery("#tmp_detalle_cxc_mod").val(),
									vencimiento:    jQuery("#tmp_vencimiento_mod").val(),
									descripcion:    jQuery("#tmp_descripcion_mod").val(),
									valor:          jQuery("#tmp_valor_mod").val()

								}
								,
								fail:function(){
									alert("error");
								},
								error:function(jqXHR,textStatus,errorThrown){
									alert("error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
								}

					});

					 jqXHR.done(function(data){
					
						modificar_item(data,mod_id);
					
					});

					

					jQuery(this).dialog("close"); 

					

				}	

		}

	]

});







/*-------------------------------------------------------delete item----------------------------------------------------*/



var grid = jQuery("#grid_<?php echo Router::getController(); ?>"),
	delSettings = {
		afterShowForm: function (jQueryform) {
			// delete button: "#dData", cancel button: "#eData"
			jQuery("#dData", jQueryform.parent()).click();
		},
		// because I use "local" data I don't want to send the changes to the server
		// so I use "processing:true" setting and delete the row manually in onclickSubmit
		onclickSubmit: function (options) {
			var gridId = grid[0].id,
				gridP = grid[0].p,
				newPage = gridP.page,
				rowids = gridP.multiselect ? gridP.selarrrow : [gridP.selrow];
			// reset the value of processing option to true
			// because the value can be changed by jqGrid
			options.processing = true;
			// delete the row
			jQuery.each(rowids, function () {
				grid.jqGrid('delRowData', this);
			});
			jQuery.jgrid.hideModal("#delmod" + gridId,
							{ gb: "#gbox_" + gridId,
							 jqm: options.jqModal,
							 onClose: options.onClose });

			if (gridP.lastpage > 1) {// on the multipage grid reload the grid
				if (gridP.reccount === 0 && newPage === gridP.lastpage) {
					// if after deliting there are no rows on the current page
					// which is the last page of the grid
					newPage -= 1; // go to the previous page
				}
				// reload grid to make the row from the next page visable.
				grid.trigger("reloadGrid", [{ page: newPage}]);
			}

			return true;
		},
		processing: true
	};

//cuadro de dialogo de agregar item...	 

jQuery("#borrar_item").click(function(){
	//jQuery("#dialogo_agregar_item").dialog("open");

if(confirm("Realmente Desea Borrar o Anular el Registro")){

	//var gr = jQuery("#grid_<?php echo Router::getController(); ?>").jqGrid('getGridParam','selrow');

	//jQuery("#grid_<?php echo Router::getController(); ?>").find("#"+gr).remove();

	toDelete = jQuery("#grid_<?php echo Router::getController(); ?>").jqGrid('getGridParam','selrow');

	var sw = 0;


	for(i=0;i<detalles.length;i++){

		if(detalles[i].id==toDelete){
			//alert("Lo Encontre: "+detalles[i].id + " SUBSTRING TEMP " + detalles[i].id.substring(0,4));
			if( detalles[i].id.substring(0,4) == 'temp' ){
				//alert("linea temporarl borrar");
				sw=0;
			}else{
				//alert("liena guardada en la base de datos anular");
				sw=1;
				detalles[i].anulado = "SI";
			}

		}

	}

	//alert(detalles["id"][toDelete]);
	//jQuery("#grid_<?php echo Router::getController(); ?>").jqGrid('delGridRow',toDelete,myDelOptions);
	if(sw==0){
		if( toDelete != null ) {
			if(jQuery("#grid_<?php echo Router::getController(); ?>").delGridRow(toDelete,delSettings)){
				detalles = jQuery.grep(
							detalles, 
							function (item,index) { 
							  return item.id !=  toDelete; 
							});
			}else{
					alert("no borro nada");
				}
			//getSelectedRow();
		}else{ alert("Por favor seleccione una fila para borrar!"); }

	}else{
			//alert("anular");
			reload_grid();
	}
	//reload_grid();

}

});



/*------------------------------------------------ Configurar Grilla de Entradas especiales --------------------------------------------------------------------*/





/*grib maestros de clientes*/

function config_gridCompras(){

		grid_fndCompras = jQuery("#grid_<?php echo Router::getController(); ?>").jqGrid({
			datatype:"local",
			data: detalles,
			height:200,
			rowNum:25,
			autowidth:true,
			pager:"#pag<?php echo Router::getController(); ?>",
			colNames:['Id','Detalle Cxc Id','Codigo','Descripcion','Valor','Vencimiento',"Anulado"],
			colModel:[
				{   name:'id',               index:'id',             sorttype:'text'        ,width: 50          },
				{	name:'detalle_cxc_id',	 index:'detalle_cxc_id', sorttype:'integer'	    ,width: 50          },
				{	name:'codigo',	         index:'codigo',	     sorttype:'text'	    ,width: 50          },
				{	name:'descripcion',	     index:'descripcion',	 sorttype:'text'	    ,width: 300         },
				{	name:'valor',	         index:'valor',	     	 formatter:"number"     ,width: 100         },
				{	name:'vencimiento',	     index:'vencimiento',    sorttype:'text'        ,width: 50          },
				{	name:'anulado',		     index:'anulado',  	     sorttype:'text'        ,width: 50          }
			],
			multiselect:false,
			caption:"Detalle <?php echo Router::getController(); ?>",
			sortname: 'id', 
			viewrecords: true, 
			sortorder: "desc",
			ondblClickRow:function(rowid,iRow,iCol,e){
				

			}
		});
	}


config_gridCompras();



<?php foreach($detalles as $detalles): ?>

	/*detalles.push(
		{
			 id              :data["id"]
			,detalle_cxc_id  :data["detalle_cxc_id"]
			,codigo          :data["codigo"]
			,numero_credito  :data["numero_credito"]
			,descripcion     :data["descripcion"]
			,valor           :data["valor"]
			,vencimiento     :data["vencimiento"]
			,anulado: "NO"

		}

	);*/
		
		var jqXHR = jQuery.ajax({
				url:"<?php echo core::getInstancePath(); ?><?php echo Router::getController(); ?>/agregar_item/",
				type:"POST",
				dataType:"json",
				data:{
						id:              <?php echo $detalles->id; ?>,
						detalle_cxc_id: '<?php echo $detalles->detalle_cxc_id; ?>',
						codigo:         '<?php echo $detalles->codigo; ?>',
						descripcion:    '<?php echo $detalles->descripcion; ?>',
						valor:           <?php echo $detalles->valor; ?>,
						vencimiento:    '<?php echo $detalles->vencimiento; ?>',
						anulado:         <?php if(  $detalles->anulado  == 0 ){ echo "'NO'"; }else{ echo "'SI'"; }  ?> 
					},
					fail:function(){
						alert("error");
					},
					error:function(jqXHR,textStatus,errorThrown){
						alert("error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
					}
		});

	 jqXHR.done(function(data){
		agregar_item(data);
	});
	
<?php endforeach; ?>


});



	
</script>




