<?php 
	if(isset($_REQUEST["opcion"])){
		Flash::notice("Doble Click en la Fila para ".$_REQUEST["opcion"]); 
	}
?>
<table id="tabla<?php echo Router::getController(); ?>"></table>
<div id="pager<?php echo Router::getController(); ?>"></div>
<script>
jQuery(document).ready(function(){

		
		jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Id','Consecutivo','Fecha','Cedula','Razón Social','Nro Cuotas','Valor Cuotas','Total Crédito','Porcentaje'], 
			colModel:[ 
				{ name:'id'                ,index:'id'                 },
				{ name:'consecutivo'       ,index:'consecutivo'        },
				{ name:'fecha'             ,index:'fecha'              },
				{ name:'nit'               ,index:'nit'                }, 
				{ name:'nombre_completo'   ,index:'razon_social'       },
				{ name:'numero_cuotas'     ,index:'numero_cuotas'      }, 
				{ name:'valor_cuotas'      ,index:'valor_cuotas'       },
				{ name:'total_credito'     ,index:'total_credito'      },
				{ name:'porcentaje'        ,index:'porcentaje'         }
			], 
			autoWidth:true,
			width: jQuery('#content').width()-25,
			height: 250,
			rowNum:50, 
			/*rowList:[10,20,30,40,50], */
			pager: '#pager<?php echo Router::getController(); ?>', 
			sortname: 'id', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"LISTADO DE SOLICITUDES",
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					if( jQuery("#nit")    ){ jQuery("#nit").val(fila['nit']); }
					if( jQuery("#nombre1") ){ jQuery("#nombre1").val(fila['nombre1']); } 
					if( jQuery("#nombre2") ){ jQuery("#nombre2").val(fila['nombre2']); } 
					if( jQuery("#apellido1") ){ jQuery("#apellido1").val(fila['apellido1']); } 
					if( jQuery("#apellido2") ){ jQuery("#apellido2").val(fila['apellido2']); } 
					
					<?php if(isset($_REQUEST["opcion"]) ){ ?>
					redireccionar_action("<?php echo Router::getController(); ?>/<?php echo $_REQUEST["opcion"]; ?>/"+fila['id'] );
					<?php }else{?>	
						jQuery("#dialogo_<?php echo Router::getController(); ?>").dialog("close");
					<?php } ?>
					
       		 }
		});
		 
		/*jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navGrid','#pager<?php //echo Router::getController(); ?>',{edit:false,add:false,del:false}); 
		jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navButtonAdd','#pager<?php //echo Router::getController(); ?>',{
		caption: "Columnas",
		title: "Reordena Columnas",
		onClickButton : function (){
			jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('columnChooser');
		
	});}*/
	jQuery(window).bind('resize', function() {
			jQuery("#tabla<?php echo Router::getController(); ?>").setGridWidth(jQuery('#content').width()-25, true);
	});
});
</script>