<?php 
$page = $_REQUEST['page']; 
// get the requested page 
$limit = $_REQUEST['rows']; 
// get how many rows we want to have into the grid 
$sidx = $_REQUEST['sidx']; 
// get index row - i.e. user click to sort 
$sord = $_REQUEST['sord']; 
// get the direction if(!$sidx) 
//$sidx =1; 
if(!$sidx) $sidx =1;

$wh = "";
$searchOn = Strip($_REQUEST['_search']);
if($searchOn=='true') {
	$searchOper = $_REQUEST["searchOper"];
	$searchField = $_REQUEST["searchField"];
	$searchString = $_REQUEST["searchString"];
	
		switch ($searchOper) {
			case 'eq': $wh = " and $searchField = '$searchString' "; break;
		}
	
}

$condicion = "";
if( $_REQUEST["clientes_id"] != '' ){ $condicion = " and c.id = '".$_REQUEST["clientes_id"]."' "; }
// connect to the database 
//$db = mysql_connect($dbhost, $dbuser, $dbpassword) or die("Connection Error: " . mysql_error()); 
//mysql_select_db($database) or die("Error conecting to db."); 

$db = DbBase::rawConnect();

$result = $db->query("SELECT COUNT(*) AS count 
							FROM solicitud s, clientes c , empresa e
						where 1 = 1 
						and c.id = s.clientes_id 
						and e.id = s.empresa_id
						and s.empresa_id = '".Session::get("id_empresa")."'
						$condicion
						
						".$wr); 

$row = $db->fetchArray($result); 

$count = $row['count']; 

if( $count >0 ) { 
		$total_pages = ceil($count/$limit); 
	} else { 
		$total_pages = 0; 
} 

if ($page > $total_pages) $page=$total_pages; 
	$start = $limit*$page - $limit;  // do not put 	$limit*($page - 1) 
	$responce = new stdClass();
	$SQL = "SELECT s.*,concat(s.prefijo,s.consecutivo) as consecutivo2, 
					c.nit,c.razon_social,e.porcentaje
					
					FROM 
						solicitud s, clientes c , empresa e
					where 1 = 1 
					and c.id = s.clientes_id
					and e.id = s.empresa_id
					and s.empresa_id = '".Session::get("id_empresa")."'
					$condicion
					 ".$wh."
			ORDER BY $sidx $sord 
			LIMIT $start , $limit"; 
	$result = $db->query( $SQL ); 
	$responce->page = $page ;
	$responce->sql = $SQL; 
	$responce->total = $total_pages; 
	$responce->records = $count; 
	$i=0; 
	while( $row = $db->fetchArray($result) ) { 
	 $responce->rows[$i]['id']=$row[id]; 
	 $responce->rows[$i]['cell']=array($row[id],utf8_encode($row[consecutivo2]),$row[fecha],$row[nit],$row[razon_social],$row[capital],$row[numero_cuotas],$row[valor_cuota],$row[total_credito],$row[porcentaje]); 						
	 $i++;
	} 
	
	echo json_encode($responce);
		
		
function Strip($value)
{
	if(get_magic_quotes_gpc() != 0)
  	{
    	if(is_array($value))  
			if ( array_is_associative($value) )
			{
				foreach( $value as $k=>$v)
					$tmp_val[$k] = stripslashes($v);
				$value = $tmp_val; 
			}				
			else  
				for($j = 0; $j < sizeof($value); $j++)
        			$value[$j] = stripslashes($value[$j]);
		else
			$value = stripslashes($value);
	}
	return $value;
}

function array_is_associative ($array)
{
    if ( is_array($array) && ! empty($array) )
    {
        for ( $iterator = count($array) - 1; $iterator; $iterator-- )
        {
            if ( ! array_key_exists($iterator, $array) ) { return true; }
        }
        return ! array_key_exists(0, $array);
    }
    return false;
}

?>
