<h4>FORMULARIO AGREGAR EMPLEADO</h5>

<?php echo Tag::formRemote(Router::getController()."/add", "update: mensajes", "id: fx","name: fx"); ?>

<table width="80%" border="0" align="center" cellpadding="1">
  <tr>
    <td width="155" height="0" align="right" valign="middle" >IDENTIFICACION</td>
    <td width="180" height="0" align="left" valign="middle" scope="col">
	<?php echo Tag::hiddenField("empresa_id","value: ".Session::get("id_empresa")); ?>
	<?php echo Tag::textField("cedula", "size: 30","maxlength: 12") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle"> NOMBRE COMPLETO</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("nombre_completo", "size: 30","maxlength: 20") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">DIRECCION</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("direccion", "size: 30","maxlength: 20") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">EMAIL</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("email", "size: 30","maxlength: 100") ?></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">TELFONO</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("telefono", "size: 30","maxlength: 100") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">CELULAR</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("celular", "size: 30","maxlength: 100") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">WEB</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("web", "size: 30","maxlength: 80") ?></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">ACTIVO</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::selectStatic('activo', 
												array('' => 'Seleccione...',
													  '1' => 'SI',
													  '0' => 'NO')) ?></td>
  </tr>
   <tr>
    <td height="0" align="right" valign="middle">FECHA INGRESO</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textField("fecha_ingreso", "size: 30","maxlength: 100") ?></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">FECHA VENCIMIENTO</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textField("fecha_vencimiento", "size: 30","maxlength: 100") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">SALARIO</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::numericField("salario", "size: 30","maxlength: 15") ?></td>
  </tr>
 	  <tr>
 	 <td colspan="2" align="center" >
   		<button type="submit" id="guardar" name="guardar">Guardar</button>     <button type="button" id="cancelar" name="cancelar" onclick="doccancelar('<?php echo core::getInstancePath(); ?>','<?php echo Router::getController(); ?>');">Cancelar</button></td>
    </tr> 
</table>

<?php echo Tag::endForm() ?>

<div id="mensajes"></div>
<br />
<script type="text/javascript">
	
	jQuery(function() {
	
	jQuery( "#fecha_ingreso" ).datepicker();
	jQuery( "#fecha_vencimiento" ).datepicker();
	
	jQuery.datepicker.regional['es'] = {
                closeText: 'Cerrar',
                prevText: '&#x3c;Ant',
                nextText: 'Sig&#x3e;',
                currentText: 'Hoy',
                monthNames: ['Enero','Febrero','Marzo','Abril','Mayo','Junio',
                'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
                monthNamesShort: ['Ene','Feb','Mar','Abr','May','Jun',
                'Jul','Ago','Sep','Oct','Nov','Dic'],
				
				dayNames: ['Domingo','Lunes','Martes','Mi&eacute;rcoles','Jueves','Viernes','S&aacute;bado'],
                dayNamesShort: ['Dom','Lun','Mar','Mi&eacute;','Juv','Vie','S&aacute;b'],
                dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','S&aacute;'],
                weekHeader: 'Sm',
                dateFormat: 'yy/mm/dd',
                firstDay: 1,
                isRTL: false,
                showMonthAfterYear: false,
                yearSuffix: ''};
	
	 jQuery.datepicker.setDefaults(jQuery.datepicker.regional['es']);
	});
	
</script>
