<table border="0" cellpadding="1" id="lclientes" width="100%">
   <tr>
    <th>NIT</th>
    <th>RAZON SOCIAL</th>
     <th>VER</th>
       <th></th>
       <th title="REMISIONES">REM</th>
        <th title="DEVOLUCIONES">DEV</th>
        <th>FACT</th>
        <th>CUENTA</th>
        <th title="RECIBOS DE CAJA">REC</th>
        <th title="ANTICIPOS DE CLIENTES">ANT</th>
        <th title="CORTE DE FACTURACION">CORTE</th>
        <th title="ESTADO DE CUENTA DEL CLIENTE">ESTADO</th>
        <th title="HISTORICO CLIENTE">HISTORICO</th>
        <th title="KARDEX DE CLIENTE">KARDEX</th>
  </tr>
        <?php 
		 $i=0;	
		 foreach($clientes as $cli): ?>  
          <tr>
            <td><div align="left"><?php echo $cli->nit;?></div></td>
            <td><div align="left"><?php echo utf8_encode($cli->razon_social) ;?></div></td>
            <td><div align="center"><?php echo Tag::linkTo("clientes/show/$cli->id", Tag::image("iconos/buscar.png","width: 20"),"target: _blank") ?></div></td>
            <td><div align="center"><?php echo Tag::linkTo("clientes/modificar/$cli->id", Tag::image("64x64/Edit.png","width: 20"),"target: _blank") ?></div></td>
            <td><div align="center"><?php echo Tag::linkTo("remisiones/agregar/?cedula=$cli->nit", Tag::image("64x64/Info.png","width: 20"),"target: _blank") ?></div></td>
            <td><div align="center"><?php echo Tag::linkTo("devoluciones/agregar/?cedula=$cli->nit", Tag::image("64x64/Info.png","width: 20"),"target: _blank") ?></div></td>
            <td><div align="center"><?php echo Tag::linkTo("facturacion/agregar/?cedula=$cli->nit", Tag::image("64x64/Info.png","width: 20"),"target: _blank");  ?></div></td>
            <td><div align="center"><?php echo Tag::linkTo("cuenta_cobro/agregar/?cedula=$cli->nit", Tag::image("64x64/Info.png","width: 20"),"target: _blank"); ?></div></td>
            <td><div align="center"><?php echo Tag::linkTo("recibos_caja/agregar/?cedula=$cli->nit", Tag::image("64x64/Info.png","width: 20"),"target: _blank") ?></div></td>
            <td><div align="center"><?php echo Tag::linkTo("anticipos/agregar/?cedula=$cli->nit", Tag::image("64x64/Info.png","width: 20"),"target: _blank") ?></div></td>
            <td><div align="center"><?php echo Tag::linkTo("corte/agregar/?cedula=$cli->nit", Tag::image("64x64/Info.png","width: 20"),"target: _blank") ?></div></td>
            <td><div align="center"><?php echo Tag::linkTo("corte/estado/?cedula=$cli->nit", Tag::image("64x64/Info.png","width: 20"),"target: _blank") ?></div></td>
            <td><div align="center"><?php echo Tag::linkTo("libros/historico_clientes_buscar/?codigo=$cli->id", Tag::image("64x64/Info.png","width: 20"),"target: _blank") ?></div></td>
            <td><div align="center"><?php echo Tag::linkTo("inventario/inventario_cliente/$cli->id", Tag::image("64x64/Info.png","width: 20"),"target: _blank") ?></div></td>
          </tr>
        <?php $i++; endforeach; ?> 
 </table>
