<h4>FORMULARIO MODIFICAR EMPLEADO</h5>

<?php echo Tag::formRemote(Router::getController()."/delete", "update: mensajes", "id: fx","name: fx"); ?>

<table width="80%" border="0" align="center" cellpadding="1">
  <tr>
    <td width="155" height="0" align="right" valign="middle" >IDENTIFICACION</td>
    <td width="180" height="0" align="left" valign="middle" scope="col">
	<?php echo Tag::hiddenField("empresa_id","value: ".Session::get("id_empresa")); ?>
    <?php echo Tag::hiddenField("id", "size: 12","readonly:false","maxlength: 12") ?>
	<?php echo Tag::textField("cedula", "size: 30","maxlength: 12") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle"> NOMBRE COMPLETO</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("nombre_completo", "size: 30","maxlength: 20") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">DIRECCION</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("direccion", "size: 30","maxlength: 20") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">EMAIL</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("email", "size: 30","maxlength: 100") ?></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">TELFONO</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("telefono", "size: 30","maxlength: 100") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">CELULAR</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("celular", "size: 30","maxlength: 100") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">WEB</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("web", "size: 30","maxlength: 80") ?></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">ACTIVO</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::selectStatic('activo', 
												array('' => 'Seleccione...',
													  '1' => 'SI',
													  '0' => 'NO')) ?></td>
  </tr>
   <tr>
    <td height="0" align="right" valign="middle">FECHA INGRESO</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textField("fecha_ingreso", "size: 30","maxlength: 100") ?></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">FECHA VENCIMIENTO</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textField("fecha_vencimiento", "size: 30","maxlength: 100") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">SALARIO</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::numericField("salario", "size: 30","maxlength: 15") ?></td>
  </tr>
 	  <tr>
 	 <td colspan="2" align="center" >
   		<button type="submit" id="enviar" name="enviar">Eliminar</button>     <button type="button" id="cancelar" name="cancelar" onclick="doccancelar('<?php echo core::getInstancePath(); ?>','<?php echo Router::getController(); ?>');">Cancelar</button></td>
    </tr> 
</table>

<?php echo Tag::endForm() ?>

<div id="mensajes"></div>
<br />

<div id="mensaje"><?php echo View::getContent(); ?></div>

<?php echo Tag::endForm() ?>

<div id="mensajes"></div>

<script>
	
	jQuery(document).ready(function(e) {
		
		jQuery("#id").attr("readOnly","ReadOnly");
		jQuery("#cedula").attr("readOnly","ReadOnly");
 		jQuery("#nombre_completo").attr("readOnly","ReadOnly");
		jQuery("#direccion").attr("readOnly","ReadOnly");
		jQuery("#email").attr("readOnly","ReadOnly");
		jQuery("#telefono").attr("readOnly","ReadOnly");
		jQuery("#celular").attr("readOnly","ReadOnly");
		jQuery("#web").attr("readOnly","ReadOnly");
		jQuery("#activo").prop('disabled', true);
		jQuery("#fecha_ingreso").attr("readOnly","ReadOnly");
		jQuery("#fecha_vencimiento").attr("readOnly","ReadOnly");
		jQuery("#salario").attr("readOnly","ReadOnly");
		
    });
	
</script>