<?php 
$page = $_REQUEST['page']; 
// get the requested page 
$limit = $_REQUEST['rows']; 
// get how many rows we want to have into the grid 
$sidx = $_REQUEST['sidx']; 
// get index row - i.e. user click to sort 
$sord = $_REQUEST['sord']; 
// get the direction if(!$sidx) 
//$sidx =1; 
if(!$sidx) $sidx =1;

$wh = "";
$searchOn = Strip($_REQUEST['_search']);
if($searchOn=='true') {
	$searchOper = $_REQUEST["searchOper"];
	$searchField = $_REQUEST["searchField"];
	$searchString = $_REQUEST["searchString"];
	
		switch ($searchOper) {
			case 'eq': $wh = " and $searchField = '$searchString' "; break;
		}
	
}

// connect to the database 
//$db = mysql_connect($dbhost, $dbuser, $dbpassword) or die("Connection Error: " . mysql_error()); 
//mysql_select_db($database) or die("Error conecting to db."); 

$condicion = "";

if(isset($_REQUEST["clientes_id"])){ if($_REQUEST["clientes_id"]!=''){ $condicion .= "  and creditos.clientes_id = '".$_REQUEST["clientes_id"]."'"; } }
if(isset($_REQUEST["creditos_id"])){ if($_REQUEST["creditos_id"]!=''){ $condicion .= "  and creditos.id = '".$_REQUEST["creditos_id"]."'"; } }

$db = DbBase::rawConnect();

$sql = "SELECT 
		  creditos.empresa_id,
		  creditos.clientes_id,
		  creditos.fecha,
		  detalle_cxc.id,
		  detalle_cxc.idt,
		  detalle_cxc.tipo_documento_id,
		  detalle_cxc.prefijo,
		  detalle_cxc.consecutivo,
		  detalle_cxc.vencimiento,
		  detalle_cxc.codigo,
		  sum(detalle_cxc.valor * detalle_cxc.multiplicar) AS valor_cuota,
		  ifnull((SELECT sum(rc.valor) AS valor FROM detalle_recibos_caja rc WHERE rc.detalle_cxc_id = detalle_cxc.id and rc.anulado = 0), 0) AS valor_pagado,
		  ifnull((SELECT sum(nc.valor) AS valor FROM detalle_notas_credito nc WHERE nc.detalle_cxc_id = detalle_cxc.id and nc.anulado = 0), 0) AS valor_nota_credito
		FROM
		  creditos,
		  detalle_cxc
		  
		WHERE
		  
		  creditos.id = detalle_cxc.creditos_id
		  and detalle_cxc.anulado = 0
		  $condicion
		GROUP BY
		  creditos.empresa_id,
		  creditos.clientes_id,
		  creditos.fecha,
		  
		  detalle_cxc.tipo_documento_id,
		  detalle_cxc.prefijo,
		  detalle_cxc.consecutivo,
		  detalle_cxc.vencimiento,
		  detalle_cxc.codigo,
		  
		  ifnull((SELECT sum(rc.valor) AS valor FROM detalle_recibos_caja rc WHERE rc.detalle_cxc_id = detalle_cxc.id and rc.anulado=0), 0),
		  ifnull((SELECT sum(nc.valor) AS valor FROM detalle_notas_credito nc WHERE nc.detalle_cxc_id = detalle_cxc.id and nc.anulado = 0), 0)
		HAVING
		  (valor_cuota - valor_pagado - valor_nota_credito ) > 0
		  and valor_cuota > 0 ";

$result = $db->query("SELECT COUNT(*) AS count FROM ( $sql ) h where 1 = 1 ".$wr); 

$row = $db->fetchArray($result); 

$count = $row['count']; 

if( $count >0 ) { 
		$total_pages = ceil($count/$limit); 
	} else { 
		$total_pages = 0; 
} 

if ($page > $total_pages) $page=$total_pages; 
	$start = $limit*$page - $limit;  // do not put 	$limit*($page - 1) 
	$responce = new stdClass();
	
	$SQL = "SELECT * FROM ( $sql ) h where 1 = 1 ".$wh."
			ORDER BY $sidx $sord 
			LIMIT $start , $limit"; 
	$result = $db->query( $SQL ); 
	$responce->page = $page ;
	$responce->sql = $SQL; 
	$responce->total = $total_pages; 
	$responce->records = $count; 
	$i=0; 
	//colNames:['Id','Cod. Creditos','Prefijo','Consecutivos','Numero Credito','Fecha','Vencimiento','Codigo Cuota','Valor'], 
	while( $row = $db->fetchArray($result) ) { 
		
		$fecha = new Date($row[vencimiento]);
		$dia_semana = $fecha->getDayOfWeek();
		
		$responce->rows[$i]['id']=$row[id]; 
		$numero = $row[id]."-".$row[prefijo].$row[consecutivo]."-".$row[codigo];
		$saldo = $row[valor_cuota]-$row[valor_pagado]-$row[valor_nota_credito];
		$responce->rows[$i]['cell']=array($row[id],$row[idt],$row[prefijo],$row[consecutivo],$numero,$row[fecha],$row[vencimiento],$dia_semana,$row[codigo],$saldo); 
		$i++; 
	} 
	
	echo json_encode($responce);
		
		
function Strip($value)
{
	if(get_magic_quotes_gpc() != 0)
  	{
    	if(is_array($value))  
			if ( array_is_associative($value) )
			{
				foreach( $value as $k=>$v)
					$tmp_val[$k] = stripslashes($v);
				$value = $tmp_val; 
			}				
			else  
				for($j = 0; $j < sizeof($value); $j++)
        			$value[$j] = stripslashes($value[$j]);
		else
			$value = stripslashes($value);
	}
	return $value;
}

function array_is_associative ($array)
{
    if ( is_array($array) && ! empty($array) )
    {
        for ( $iterator = count($array) - 1; $iterator; $iterator-- )
        {
            if ( ! array_key_exists($iterator, $array) ) { return true; }
        }
        return ! array_key_exists(0, $array);
    }
    return false;
}

?>
