<?php 
	if(isset($_REQUEST["opcion"])){
		Flash::notice("Doble Click en la Fila para ".$_REQUEST["opcion"]); 
	}
?>
<table id="tabla<?php echo Router::getController(); ?>"></table>
<div id="pager<?php echo Router::getController(); ?>"></div>
<script>
jQuery(document).ready(function(){

		
		jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Id','Cedula','Nombres y Apellidos','Activo'], 
			colModel:[ 
				{ name:'id',index:'id', width:200},
				{ name:'cedula',index:'nit', width:200}, 
				{ name:'nombre_completo',index:'nombre1', width:500},
				{ name:'activo',index:'nombre2', width:200}
			], 
			autoWidth:true,
			width: jQuery('#content').width()-25,
			height: 250,
			rowNum:50, 
			/*rowList:[10,20,30,40,50], */
			pager: '#pager<?php echo Router::getController(); ?>', 
			sortname: 'id', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"LISTADO DE EMPLEADOS",
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					if( jQuery("#id")    ){ jQuery("#nit").val(fila['nit']); }
					if( jQuery("#cedula") ){ jQuery("#nombre1").val(fila['nombre1']); } 
					if( jQuery("#nombre_completo") ){ jQuery("#nombre2").val(fila['nombre2']); } 
					if( jQuery("#activo") ){ jQuery("#apellido1").val(fila['apellido1']); } 
				
					
					<?php if(isset($_REQUEST["opcion"]) ){ ?>
					redireccionar_action("<?php echo Router::getController(); ?>/<?php echo $_REQUEST["opcion"]; ?>/"+fila['id'] );
					<?php }else{?>	
						jQuery("#dialogo_<?php echo Router::getController(); ?>").dialog("close");
					<?php } ?>
					
       		 }
		}); 
		/*jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navGrid','#pager<?php //echo Router::getController(); ?>',{edit:false,add:false,del:false}); 
		jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navButtonAdd','#pager<?php //echo Router::getController(); ?>',{
		caption: "Columnas",
		title: "Reordena Columnas",
		onClickButton : function (){
			jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('columnChooser');
		
	});}*/
	jQuery(window).bind('resize', function() {
			jQuery("#tabla<?php echo Router::getController(); ?>").setGridWidth(jQuery('#content').width()-25, true);
	});
});
</script>