<div align="center">
<h4>ESCOJA UNA IMAGEN O ICONO</h4>
<?php
//$dir    = '/tmp';

$archivos1 = scandir($_SERVER['DOCUMENT_ROOT'].core::getInstancePath()."public/files/archivos_cargados/");
//$archivos2 = scandir($_SERVER['DOCUMENT_ROOT'].core::getInstancePath()."public/img", 1);

if(count($archivos1)==2){
	
	Flash::error("NO SE ENCONTRO NINGUNA IMAGEN EL EL DIRECTORIO LOGO...");

}

//print_r($archivos1);

for($i=0;$i<=count($archivos1)-1;$i++){
	
	if($i%10==0){
		
		echo "<br />";
		echo "<br />";
	
	}
	
	if($archivos1[$i]!='.' && $archivos1[$i]!='..'){
		echo Tag::image("upload/".$archivos1[$i],"width: 75px","heigth: 75px","border: 1"
						,"style: padding: 5px; cursor: hand; "
						,"onClick: UploadFileOk('public/files/upload/".$archivos1[$i]."');jQuery('#dialogo_imagen').dialog('close');"
						
						); 
	}

?>

<?php	
}
 
//print_r($archivos1);
//print_r($archivos2);
?>


<?php echo view::getContent(); ?>

</div>