<h1>Aplicaciones</h1>

<div id="cuerpo_empleado" style="padding:50px; min-height:300px"> 

 <?php echo View::getContent(); ?>   

</div>

<?php  ?>


<div align="center">



	<table width="400px" cellpadding="2" cellspacing="2" class="ui-widget ui-widget-content ui-corner-all ui-dialog-titlebar ui-widget-header ui-front">

    	<tr>

        	<td align="center"><?php echo Tag::linkTo("home/aplicaciones",Tag::image("iconos/inicio.png","width: 50px")); ?></td>

            <td align="center"><?php echo Tag::linkTo("login/salir",Tag::image("iconos/entrar.png","width: 50px")); ?></td>

        </tr>

        <tr>

        	<td align="center">Inicio</td>

            <td align="center">Cerrar Session</td>

        </tr>

    </table>

    

</div>


