<h4>FORMULARIO AGREGAR CLIENTES</h5>

<?php echo Tag::formRemote(Router::getController()."/add", "update: mensajes", "id: fx","name: fx"); ?>

<table border="0" align="center" cellpadding="1">
  <tr>
    <td width="155" height="0" align="right" valign="middle" >IDENTIFICACION</td>
    <td width="180" height="0" align="left" valign="middle" scope="col"><?php echo Tag::textField("nit", "size: 12","maxlength: 12") ?></td>
    <td width="136" align="right" scope="col">&nbsp;</td>
    <td width="349" scope="col">&nbsp;</td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">PRIMER NOMBRE</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("nombre1", "size: 20","maxlength: 20") ?></td>
    <td align="right">SEGUNDO NOMBRE</td>
    <td><?php echo Tag::textUpperField("nombre2", "size: 30","maxlength: 20") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">PRIMER APELLIDO</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("apellido1", "size: 20","maxlength: 20") ?></td>
    <td align="right">SEGUNDO APELLIDO</td>
    <td><?php echo Tag::textUpperField("apellido2", "size: 30","maxlength: 20") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">FOTO</td>
    <td height="0" colspan="3" align="left" valign="middle"><?php echo Tag::textField("foto","size: 50","readonly: readonly") ?> <button type="button" id="camara" name="camara">Capturar Foto</button></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">HUELLA</td>
    <td height="0" align="left" valign="middle"><button type="button" id="huella" name="huella" onclick="javascript:capturar_huella();">Capturar Huella</button></td>
    <td align="right" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">&nbsp;</td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">RAZ&Oacute;N SOCIAL</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("razon_social", "size: 40","maxlength: 100") ?></td>
    <td align="right" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">&nbsp;</td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">DIRECCION CASA</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("direccion_casa", "size: 40","maxlength: 100") ?></td>
    <td align="right"></td>
    <td></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">DIRECCION OFICINA</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("direccion_oficina", "size: 40","maxlength: 100") ?></td>
    <td align="right">&nbsp;</td>
    <td>&nbsp;</td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">TELEFONO FIJO(1)</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::numericField("telefono1", "size: 15","maxlength: 20") ?></td>
    <td align="right">TELEFONO FIJO(2)</td>
    <td><?php echo Tag::numericField("telefono2", "size: 15","maxlength: 15") ?></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">SUELDO MENSUAL</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::numericField("sueldo", "size: 15","maxlength: 20") ?></td>
    <td align="right">OTROS INGRESOS</td>
    <td><?php echo Tag::numericField("otros_ingresos", "size: 15","maxlength: 20") ?></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">EPS</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("eps", "size: 40","maxlength: 100") ?></td>
    <td align="right">&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">CASA PROPIA</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::selectStatic('casa', 
												array('' => 'Seleccione...',
													  'S' => 'SI',
													  'N' => 'NO')) ?></td>
    <td align="right">VEHICULOS</td>
    <td><?php echo Tag::textUpperField("vehiculos", "size: 15","maxlength: 20") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">CELULAR</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::numericField("celular", "size: 15","maxlength: 15") ?></td>
    <td align="right">&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">DEPARTAMENTOS</td>
    <td height="0" colspan="3" align="left" valign="middle">
      <?php  echo Tag::textFieldExt("departamentos","campo: departamento","size: 10"); ?>
   </td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">MUNICIPIOS</td>
    <td height="0" colspan="3" align="left" valign="middle"><?php  echo Tag::textFieldExt("municipios","campo: municipio","size: 10"); ?></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">EMAIL</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("email", "size: 30","maxlength: 100") ?></td>
    <td align="right">PAGINA WEB</td>
    <td><?php echo Tag::textUpperField("web", "size: 30","maxlength: 50") ?></td>
    </tr>
    <tr>
 	 <td colspan="4" align="center" >
     		<button type="submit" id="guardar" name="guardar">Guardar</button>
           
            <button type="button" id="cancelar" name="cancelar" onclick="doccancelar('<?php echo core::getInstancePath(); ?>','<?php echo Router::getController(); ?>');">Cancelar</button>
     </td>
    </tr> 
</table>

<div id="mensajes"></div>
<?php echo Tag::endForm() ?>

<!--

<div id="photos"></div>

<div id="camera">
	<span class="tooltip"></span>
	<span class="camTop"></span>
   
	
    <div id="screen"></div>
    <div id="buttons">
    	<div class="buttonPane">
        	<a id="shootButton" href="" class="blueButton">Foto</a>
        </div>
        <div class="buttonPane hidden">
        	<a id="cancelButton" href="" class="blueButton">Cancelar</a> <a id="uploadButton" href="" class="greenButton">Subir</a>
        </div>
    </div>
    
    <span class="settings"></span>
</div>


    -->
    
<?php // echo "<script>configcamara('".$_DOCUMENT["REQUEST"].core::getInstancePath()."public/javascript/fotos/assets/webcam/','".$_DOCUMENT["REQUEST"].core::getInstancePath()."clientes/')</script>"?>


<br />
<br />
	

	
    
    
<script language="JavaScript">
 jQuery(document).ready(function(e) {
	 
	 
 <?php 
		$entidad = new Clientes();
		
		foreach( $entidad->getPrimaryKeyAttributes() as $filas):
			echo "jQuery(\"#$filas\").attr(\"readonly\",\"readonly\");\n";
		endforeach;	
		
		foreach( $entidad->getNonPrimaryKeyAttributes() as $filas):
				foreach( $entidad->getNonPrimaryKeyAttributes() as $filas2):
					if($filas==$filas2){ echo "jQuery(\"#$filas2\").attr(\"required\",\"required\");\n"; break;} 
				endforeach;	
				
		endforeach;	
		
	?> 	
	
	 
	 jQuery("#razon_social").focus(function(){
		 	nom="";
			nom+=jQuery("#nombre1").val();nom+=" ";
			nom+=jQuery("#nombre2").val();nom+=" ";
			nom+=jQuery("#apellido1").val();nom+=" ";
			nom+=jQuery("#apellido2").val();nom+=" ";
			nom = nom.replace("  "," ");
	 		jQuery("#razon_social").val(nom);
		 });
	 
	 jQuery("#camara").click(function(event){
		 	event.preventDefault();
			 html = webcam.get_html(640, 480) ;
			 html += "<center><a href='javascript:void(webcam.snap())'>Tomar Foto</a></center>"; 
		 	 jQuery("#dialogo_camara").html(html);
			 jQuery("#dialogo_camara").dialog("open");
		 });
	
});

url = '<?php echo $_document["REQUEST"].core::getInstancePath();?>/public/javascript/webcam/';
//webcam.set_api_url( 'test.php' );
webcam.set_swf_url(url + 'webcam.swf');
webcam.set_api_url('<?php echo core::getInstancePath().Router::getController();?>/upload');	// The upload script
webcam.set_quality(80);				// JPEG Photo Quality
webcam.set_shutter_sound(true, url + '/shutter.mp3');

webcam.set_hook( 'onComplete', 'completado' );


function completado(response) {
		
     jQuery("#foto").val(response);
	//jQuery("#mensajes").html(response);
	jQuery("#dialogo_camara").dialog("close");
	
}


		
</script>
