<h4>FORMULARIO AGREGAR CLIENTES</h5>

<?php echo Tag::formRemote(Router::getController()."/add", "update: mensajes", "id: fx","name: fx"); ?>

<table border="0" align="center" cellpadding="1">
  <tr>
    <td width="155" height="0" align="right" valign="middle" >IDENTIFICACION</td>
    <td width="180" height="0" align="left" valign="middle" scope="col"><?php echo Tag::textField("nit2", "size: 12","maxlength: 12") ?></td>
    <td width="136" align="right" scope="col">&nbsp;</td>
    <td width="349" scope="col">&nbsp;</td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">PRIMER NOMBRE</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("nombre12", "size: 20","maxlength: 20") ?></td>
    <td align="right">SEGUNDO NOMBRE</td>
    <td><?php echo Tag::textUpperField("nombre22", "size: 30","maxlength: 20") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">PRIMER APELLIDO</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("apellido12", "size: 20","maxlength: 20") ?></td>
    <td align="right">SEGUNDO APELLIDO</td>
    <td><?php echo Tag::textUpperField("apellido22", "size: 30","maxlength: 20") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">RAZON SOCIAL</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("razon_social2", "size: 30","maxlength: 60") ?></td>
    <td align="right"></td>
    <td></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">DIRECCION</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("direccion", "size: 40","maxlength: 100") ?></td>
    <td align="right"></td>
    <td></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">TELEFONO</td>
    <td height="0" colspan="3" align="left" valign="middle"><?php echo Tag::NumericField("telefono", "size: 30","maxlength: 20") ?></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">CELULAR</td>
    <td height="0" colspan="3" align="left" valign="middle"><?php echo Tag::NumericField("celular", "size: 30","maxlength: 20") ?></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">REFERENCIA</td>
    <td height="0" colspan="3" align="left" valign="middle">
	<?php echo Tag::textFieldExt("clientes", "size: 10","maxlength: 20","placeholder: INGRESE REFERENCIA") ?></td>
  </tr>
 <!-- <tr>
    <td height="0" align="right" valign="middle">DEPARTAMENTOS</td>
    <td height="0" colspan="3" align="left" valign="middle">
      <?php  //echo Tag::textFieldExt("departamentos","campo: departamento","size: 10"); ?>
   </td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">MUNICIPIOS</td>
    <td height="0" colspan="3" align="left" valign="middle"><?php  //echo Tag::textFieldExt("municipios","campo: municipio","size: 10"); ?></td>
  </tr>-->
    <tr>
 	 <td colspan="4" align="center" >
     		<button type="submit" id="guardar" name="guardar">Guardar</button>
           
            <button type="button" id="cancelar" name="cancelar" onclick="doccancelar('<?php echo core::getInstancePath(); ?>','<?php echo Router::getController(); ?>');">Cancelar</button>
     </td>
    </tr> 
</table>

<div id="mensajes"></div>
<?php echo Tag::endForm() ?>

<!--

<div id="photos"></div>

<div id="camera">
	<span class="tooltip"></span>
	<span class="camTop"></span>
   
	
    <div id="screen"></div>
    <div id="buttons">
    	<div class="buttonPane">
        	<a id="shootButton" href="" class="blueButton">Foto</a>
        </div>
        <div class="buttonPane hidden">
        	<a id="cancelButton" href="" class="blueButton">Cancelar</a> <a id="uploadButton" href="" class="greenButton">Subir</a>
        </div>
    </div>
    
    <span class="settings"></span>
</div>


    -->
    
<?php // echo "<script>configcamara('".$_DOCUMENT["REQUEST"].core::getInstancePath()."public/javascript/fotos/assets/webcam/','".$_DOCUMENT["REQUEST"].core::getInstancePath()."clientes/')</script>"?>


<br />
<br />
	

	
    
    
<script language="JavaScript">
 jQuery(document).ready(function(e) {
	 
	 
 <?php 
		$entidad = new Clientes();
		
		foreach( $entidad->getPrimaryKeyAttributes() as $filas):
			echo "jQuery(\"#$filas\").attr(\"readonly\",\"readonly\");\n";
		endforeach;	
		
		foreach( $entidad->getNonPrimaryKeyAttributes() as $filas):
				foreach( $entidad->getNonPrimaryKeyAttributes() as $filas2):
					if($filas==$filas2){ echo "jQuery(\"#$filas2\").attr(\"required\",\"required\");\n"; break;} 
				endforeach;	
				
		endforeach;	
		
	?> 	
	
	 
	 jQuery("#razon_social2").focus(function(){
		 	nom="";
			nom+=jQuery("#nombre12").val();nom+=" ";
			nom+=jQuery("#nombre22").val();nom+=" ";
			nom+=jQuery("#apellido12").val();nom+=" ";
			nom+=jQuery("#apellido22").val();nom+=" ";
			nom = nom.replace("  "," ");
	 		jQuery("#razon_social2").val(nom);
		 });
	
	
});

	
</script>
