<h1>FORMULARIO PARA ELIMINAR DATOS DEL CLIENTE</h1>


<?php echo Tag::formRemote(Router::getController()."/delete", "update: mensajes", "id: fx","name: fx"); ?>

<table border="0" align="center" cellpadding="1">
  <tr>
    <td width="155" height="0" align="right" valign="middle" >IDENTIFICACION</td>
    <td width="180" height="0" align="left" valign="middle" scope="col"><?php echo Tag::hiddenField("id", "size: 12","maxlength: 12") ?><?php echo Tag::textField("nit2", "size: 12","maxlength: 12") ?></td>
    <td width="136" align="right" scope="col">&nbsp;</td>
    <td width="349" scope="col">&nbsp;</td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">PRIMER NOMBRE</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("nombre12", "size: 20","maxlength: 20") ?></td>
    <td align="right">SEGUNDO NOMBRE</td>
    <td><?php echo Tag::textUpperField("nombre22", "size: 30","maxlength: 20") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">PRIMER APELLIDO</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("apellido12", "size: 20","maxlength: 20") ?></td>
    <td align="right">SEGUNDO APELLIDO</td>
    <td><?php echo Tag::textUpperField("apellido22", "size: 30","maxlength: 20") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">RAZON SOCIAL</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("razon_social2", "size: 30","maxlength: 60") ?></td>
    <td align="right"></td>
    <td></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">DIRECCION</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textUpperField("direccion", "size: 40","maxlength: 100") ?></td>
    <td align="right"></td>
    <td></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">TELEFONO</td>
    <td height="0" colspan="3" align="left" valign="middle"><?php echo Tag::NumericField("telefono", "size: 30","maxlength: 20") ?></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">CELULAR</td>
    <td height="0" colspan="3" align="left" valign="middle"><?php echo Tag::NumericField("celular", "size: 30","maxlength: 20") ?></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">REFERENCIA</td>
    <td height="0" colspan="3" align="left" valign="middle">
	<?php echo Tag::textFieldExt("clientes", "size: 10","maxlength: 20","placeholder: INGRESE REFERENCIA") ?></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">DEPARTAMENTOS</td>
    <td height="0" colspan="3" align="left" valign="middle">
      <?php  echo Tag::textFieldExt("departamentos","campo: departamento","size: 10"); ?>
   </td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">MUNICIPIOS</td>
    <td height="0" colspan="3" align="left" valign="middle"><?php  echo Tag::textFieldExt("municipios","campo: municipio","size: 10"); ?></td>
  </tr>
    <tr>
 	 <td colspan="4" align="center" >
     		<button type="submit" id="guardar" name="guardar">Eliminar</button>
           
            <button type="button" id="cancelar" name="cancelar" onclick="doccancelar('<?php echo core::getInstancePath(); ?>','<?php echo Router::getController(); ?>');">Cancelar</button>
     </td>
    </tr> 
</table>

<div id="mensaje"><?php echo View::getContent(); ?></div>

<?php echo Tag::endForm() ?>

<div id="mensajes"></div>

<script>
	
	jQuery(document).ready(function(e) {
		
        jQuery("#id").attr("readOnly","ReadOnly");
		jQuery("#nit2").attr("readOnly","ReadOnly");
		jQuery("#nombre12").attr("readOnly","ReadOnly");
		jQuery("#nombre22").attr("readOnly","ReadOnly");
		jQuery("#apellido12").attr("readOnly","ReadOnly");
		jQuery("#apellido22").attr("readOnly","ReadOnly");
		jQuery("#razon_social2").attr("readOnly","ReadOnly");
		jQuery("#direccion").attr("readOnly","ReadOnly");
		jQuery("#telefono").attr("readOnly","ReadOnly");
		jQuery("#celular").attr("readOnly","ReadOnly");
		jQuery("#clientes_id").attr("readOnly","ReadOnly");
		jQuery("#clientes").attr("readOnly","ReadOnly");
		jQuery("#departamentos_id").attr("readOnly","ReadOnly");
		jQuery("#departamento").attr("readOnly","ReadOnly");
		jQuery("#buscar_departamentos").prop('disabled', true);
		jQuery("#buscar_clientes").prop('disabled', true);
		jQuery("#municipios_id").attr("readOnly","ReadOnly");
		jQuery("#municipio").attr("readOnly","ReadOnly");
		jQuery("#buscar_municipios").prop('disabled', true);
			

    });
	
</script>