<?php 
$path = $_SERVER['DOCUMENT_ROOT'].core::getInstancePath().'public/files/';
$path_system = $_SERVER['DOCUMENT_ROOT']."/";
$proyecto = "inversionesjd/";
//$path_system = str_replace("htdocs","/inversionesjd/",$path_system);

$path_system_linux = $_SERVER['DOCUMENT_ROOT']."/";



if(strtoupper(substr(PHP_OS, 0, 3)) === 'WIN'){ 


	Flash::notice("Hey entro por windows");
	
	Flash::notice($path_system.$proyecto);
	
	/*$command = " cd ".$path_system.$proyecto;
	
	$command3 = " git pull origin master ";
	//system($command);
	//system($command2);

	$salida = shell_exec($command);
	echo "<pre>$salida</pre>";
	$salida = shell_exec($command3);
	echo "<pre>$salida</pre>";
	echo print_r($salida);*/
	$pathRepo = $path_system.$proyecto;
	chdir($pathRepo);  
	exec("git pull origin master ");
	echo 'OK';
	
	/* $repo = new PHPGit_Repository($path_system.$proyecto,true, array('git_executable' => 'C:\Program Files\Git\bin'));
	 $repo->git('pull origin master');
	 echo 'OK';*/
		


}else{
	//si es window
	Flash::notice($path_system);
	Flash::notice("Hey entro por linux modificado hoy");
	

	$command3 = " git pull origin master ";
	//system($command);
	//system($command2);

	$salida = shell_exec("cd '$path_system_linux' && /usr/bin/git pull origin master");
	echo "<pre>$salida</pre>";
	echo print_r($salida);
	
	
	
	
}

?>
<h2>Comando ejecutado. Si hubo errores, Se mostrarán arriba.</h2>




