<?php 
$path = $_SERVER['DOCUMENT_ROOT'].core::getInstancePath().'public/files/';
$path_system = $_SERVER['DOCUMENT_ROOT']."/";
$proyecto = "inversionesjd/";
//$path_system = str_replace("htdocs","/inversionesjd/",$path_system);

$path_system_linux = $_SERVER['DOCUMENT_ROOT']."/";

Flash::notice($path_system.$proyecto);

if(strtoupper(substr(PHP_OS, 0, 3)) === 'WIN'){ 
	Flash::notice("Hey entro por windows");
	$command = " cd ".$path_system.$proyecto;
	
	$command3 = " git pull origin master ";
	//system($command);
	//system($command2);

	$salida = shell_exec($command);
	echo "<pre>$salida</pre>";
	$salida = shell_exec($command3);
	echo "<pre>$salida</pre>";
	echo print_r($salida);
	


}else{
	//si es window
	Flash::notice("Hey entro por linux");
	$command = " cd ".$path_system_linux;
	$command3 = " git pull origin master ";
	//system($command);
	//system($command2);

	$salida = shell_exec($command);
	echo "<pre>$salida</pre>";
	$salida = shell_exec($command3);
	echo "<pre>$salida</pre>";
	echo print_r($salida);
	
}

?>
<h2>Comando ejecutado. Si hubo errores, Se mostrarán arriba.</h2>




