<br /><br />
<h1>LISTADO DE CARTERA</h1>
<h1>Empresa: <?php echo $empresa->nombre_empresa; ?></h1>
<br />
<?php echo Tag::form("libros/cartera", "id: facturas","name: facturas"); ?>

<table width="100%" border="0" cellpadding="0" id="r1">
  
  <tr>
    <th colspan="4" align="center">ESCOJA SU LA EMPRES A CONSULTAR</th>
  </tr>
  <tr>
    <td align="right">EMPRESA:</td>
    <td colspan="3">
		<?php $empresa = new Empresa(); echo Tag::select("empresa_id",$empresa->find(),'using: id,nombre_empresa'); ?>
        <script>$('empresa_id').value = '<?php echo Session::get("id_empresa"); ?>';</script>
        </td>
  </tr>
   <!--<tr>
    <td><div align="right">DESDE</div></td>
    <td><?php echo Tag::dateFieldMod("desde","size: 10","value: ".Date::getFirstDayofMonth( date("m"),date("Y") ) ); ?></td>
    <td><div align="right">HASTA</div></td>
    <td><?php echo Tag::dateFieldMod("hasta","size: 10","value: ".Date::getLastDayofMonth( date("m"),date("Y") ) ); ?></td>
  </tr>-->
   <tr>
    <td colspan="4" align="center">
    		<?php 		$mes = array(	"1"=>"ENERO",
										"2"=>"FEBRERO",
										"3"=>"MARZO",
										"4"=>"ABRIL",
										"5"=>"MAYO",
										"6"=>"JUNIO",
										"7"=>"JULIO",
										"8"=>"AGOSTO",
										"9"=>"SEPTIEMBRE",
										"10"=>"OCTUBRE",
										"11"=>"NOVIEMBRE",
										"12"=>"DICIEMBRE"
									); ?>
    		MES <?php echo Tag::selectStatic("mes",$mes); ?> AÑO <?php echo Tag::textField("yyyy","size: 4","maxlength: 4","value: ".date("Y")); ?>
            	<script>
                	$('mes').value = '<?php echo intval(date("m")); ?>';
                </script>
            </td>
  </tr>
  <tr>
    <td colspan="4"><div align="center"><?php echo Tag::submitButton("Enviar"); ?></div></td>
  </tr>
</table>

<?php echo Tag::endForm(); ?>

<br />

<table border="0" cellpadding="1" id="remisiones" width="100%">
   <tr>
    <th>NUMERO</th>
    <th>CLIENTE</th>
    <th>DIRECCIÓN</th>
    <th>FECHA</th>
    <!--<th>VENC.</th>-->
    <!--<th>ATRASO</th>-->
    <th>TOTAL</th>
    <!--<th>ANTICIPOS</th>-->
    <th>PAGADO</th>
    <th>SALDO</th>
    <th>DESC.</th>
    <th>FECHA</th>
    <th>ABONO</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <!--<th>&nbsp;</th>-->
    <th>&nbsp;</th>
  </tr>
        <?php 
		 $i=0;	
		 $cliente = new Clientes();
		 $recenc = new RecibosCaja();
		 $rec = new DetalleRecibosCaja();
		 $ant = new AnticiposFactura();
		 $antenc = new Anticipos();
		 $dir = new Direccion();
		 $c1 = 0;
		 $c2 = 0;
		 $c3 = 0;
		 $c4 = 0;
		 $c5 = 0;
		 
		 foreach($facturas as $fac): 
		 
		 ?>  
          <tr>
            <td><?php echo $fac->prefijo."-".intval($fac->consecutivo); ?></td>
            <td><?php echo utf8_encode($fac->razon_social);  ?></td>
            <td><?php echo utf8_encode($fac->direccion);  ?></td>
            <td><?php echo $fac->fecha ; ?></td>
            <!--<td><?php echo $fac->vencimiento ; ?></td>
            <td><?php echo $fac->atraso; ?></td>-->
            <td>$<?php echo number_format($fac->total,0);    $c1 += $fac->total; ?></td>
           <!-- <td>$<?php echo number_format($fac->anticipo,0); $c2 += $fac->anticipo;?></td> -->
            <td>$<?php echo number_format($fac->pagado+$fac->anticipo-$fac->descontado,0);   $c3 += $fac->pagado + $fac->anticipo - $fac->descontado;?></td>
            <td>$<?php echo number_format($fac->total-$fac->anticipo-$fac->pagado,0); $c4+= $fac->total-$fac->anticipo-$fac->pagado;?></td>
            <td>$<?php echo number_format($fac->descontado,0); $c5 += $fac->descontado;?></td>
            <td colspan="2">
            	<table width="100%" cellpadding="1" cellspacing="1" border="0" style="padding:0px;">
                	<!--<tr><td width="50%">FECHA</td><td width="50%">ABONO</td></tr>-->
                <tr>
            	<?php foreach($ant->find(" factura_id = '$fac->id' and anulado = 0") as $ant): ?>
                			<td width="50%"><?php echo $antenc->findFirst(" id = '$ant->anticipos_id' ")->fecha; ?></td><td width="50%">$<?php echo number_format($ant->valor,0); ?></td>
				<?php endforeach; ?>
                </tr>
                <tr>
                <?php foreach($rec->find(" factura_id = '$fac->id' and anulado = 0") as $rec): ?>
                			<td width="50%"><?php echo $recenc->findFirst(" id = '$rec->recibos_caja_id' ")->fecha; ?></td><td width="50%">$<?php echo number_format($rec->total - $rec->descuento,0); ?></td>		
				<?php endforeach; ?>
                </tr>
           		 </table>
            </td>
            
            <?php if($fact->empresa_id == 1){ ?>
            <td><?php echo Tag::linkTo("facturacion/show/$fac->id", Tag::image("64x64/Search.png","width: 20"),"target: _blank") ?></td>
            <td><?php echo Tag::linkTo("print/facturacion_html/$fac->id", Tag::image("iconos/impresora.png","width: 20"),"target: _blank") ?></td>
            <!--<td><?php echo Tag::linkTo("print/facturacion/$fac->id", Tag::image("iconos/pdf.png","width: 20"),"target: _blank") ?></td>-->
            
            <?php }else{ ?>
            <td><?php echo Tag::linkTo("cuenta_cobro/show/$fac->id", Tag::image("64x64/Search.png","width: 20"),"target: _blank") ?></td>
            <td><?php echo Tag::linkTo("print/cuenta_cobro_html/$fac->id", Tag::image("iconos/impresora.png","width: 20"),"target: _blank") ?></td>
            <!--<td><?php echo Tag::linkTo("print/cuenta_cobro/$fac->id", Tag::image("iconos/pdf.png","width: 20"),"target: _blank") ?></td>-->
            <td>	
				
				<!--<?php echo Tag::button("Ver Pagos","id: ver_pagos$i","name: ver_pagos$i"); ?>
                <script>
                	new Event.observe("ver_pagos<?php echo $i; ?>", "click", function(){
								
								 parametros = '';
								 parametros += "factura_id=<?php echo $fac->id; ?>";
								 parametros += "&empresa_id=<?php echo $fac->empresa_id; ?>";
								
										
								 Dialog.alert(
									{
										url: "<?php echo core::getInstancePath(); ?>libros/ver_pagos/?"+parametros, 
										options: {method: 'get'
										, evalScripts: true}
									}, 
									{
										className: "mac_os_x", width:900,height:600,
										okLabel: "Click Aqui Para Cerrar Esta Ventana"}
									);
									
									
						 });
                </script>-->
                
                </td>
            <?php }?>
          </tr>
        <?php $i++; 
		endforeach; ?> 
         <tr>
            <th colspan="4" align="right">TOTALES</th>
            <td>$<?php echo number_format($c1,0); ?></td>
           <!--<td>$<?php echo number_format($c2,0); ?></td>-->
           <td>$<?php echo number_format($c3,0); ?></td>
           <td>$<?php echo number_format($c4,0); ?></td>
           <td>$<?php echo number_format($c5,0); ?></td>
           <td>&nbsp;</td>
            <td>&nbsp;</td>
          <!--  <td>&nbsp;</td>-->
            <td>&nbsp;</td>
  </tr>
 </table>
 
<?php echo view::getContent(); ?>