<?php 
$db = DbBase::rawConnect();
$condicion = '';
/*$consulta = str_replace(" ","%",$_REQUEST["term"]);
if($_REQUEST["term"]!=''){
    $condicion .= " and color like '%$consulta%' ";
}*/
if($_REQUEST["inicio"]!=''){
    $condicion .= " and pedido_clientes.fecha >= '".$_REQUEST["inicio"]."' ";
}
if($_REQUEST["fin"]!=''){
    $condicion .= " and pedido_clientes.fecha <= '".$_REQUEST["fin"]."' ";
}




$page = $_REQUEST['page']; 
// get the requested page 
$limit = $_REQUEST['rows']; 
// get how many rows we want to have into the grid 
$sidx = $_REQUEST['sidx']; 
// get index row - i.e. user click to sort 
$sord = $_REQUEST['sord']; 
// get the direction if(!$sidx) 
//$sidx =1; 
if(!$sidx) $sidx =1;

$wh = "";
$searchOn = Strip($_REQUEST['_search']);
if($searchOn=='true') {
    $searchOper = $_REQUEST["searchOper"];
    $searchField = $_REQUEST["searchField"];
    $searchString = $_REQUEST["searchString"];
    
        switch ($searchOper) {
            case 'eq': $wh = " and $searchField = '$searchString' "; break;
        }
    
}
/*$sql = "SELECT
					 pedido_clientes.id,
					 pedido_clientes.prefijo,
					 pedido_clientes.consecutivo,
					 pedido_clientes.fecha,
					 pedido_clientes.hora_entrada,pedido_clientes.hora_salida,
					 pedido_clientes.placa,pedido_clientes.color,
					 pedido_clientes.liquidado,
					 detalle_pedido_clientes.valor,
					 detalle_pedido_clientes.cantidad,
					 sum(detalle_pedido_clientes.total) as total, 
					 detalle_pedido_clientes.anulado AS detalle_pedido_clientes_anulado,
					 pedido_clientes.liquidado AS detalle_pedido_clientes_anulado,
					 clase_vehiculo.id AS clase_vehiculo_id,
					 clase_vehiculo.clase_vehiculo AS clase_vehiculo_clase_vehiculo,
					 tipo_auto.id AS tipo_auto_id, tipo_auto.tipo_auto AS tipo_auto_tipo_auto,
					 centro_produccion.centro_produccion AS centro_produccion_centro_produccion
					
				FROM
					 pedido_clientes pedido_clientes INNER JOIN detalle_pedido_clientes detalle_pedido_clientes ON pedido_clientes.id = detalle_pedido_clientes.pedido_clientes_id
					 INNER JOIN empresa empresa ON pedido_clientes.empresa_id = empresa.id
					 INNER JOIN clase_vehiculo clase_vehiculo ON pedido_clientes.clase_vehiculo_id = clase_vehiculo.id
					 INNER JOIN centro_produccion centro_produccion ON pedido_clientes.centro_produccion_id = centro_produccion.id
					 INNER JOIN tipo_auto tipo_auto ON pedido_clientes.tipo_auto_id = tipo_auto.id
				WHERE
					 detalle_pedido_clientes.anulado = 0
					 and pedido_clientes.anulado = 0
					 and pedido_clientes.fecha >= $P{inicio}
					 and pedido_clientes.fecha <= $P{fin}
				GROUP BY
					 pedido_clientes.id
				ORDER BY
					 pedido_clientes.prefijo ASC,
					 pedido_clientes.consecutivo ASC";*/
// connect to the database 
//$db = mysql_connect($dbhost, $dbuser, $dbpassword) or die("Connection Error: " . mysql_error()); 
//mysql_select_db($database) or die("Error conecting to db."); 

$db = DbBase::rawConnect();
$result = $db->query("SELECT COUNT(*) AS count 
							FROM 
								pedido_clientes pedido_clientes INNER JOIN detalle_pedido_clientes detalle_pedido_clientes ON pedido_clientes.id = detalle_pedido_clientes.pedido_clientes_id
								 INNER JOIN empresa empresa ON pedido_clientes.empresa_id = empresa.id
								 INNER JOIN clase_vehiculo clase_vehiculo ON pedido_clientes.clase_vehiculo_id = clase_vehiculo.id
								 INNER JOIN centro_produccion centro_produccion ON pedido_clientes.centro_produccion_id = centro_produccion.id
								 INNER JOIN tipo_auto tipo_auto ON pedido_clientes.tipo_auto_id = tipo_auto.id
							WHERE 
								detalle_pedido_clientes.anulado = 0
								and pedido_clientes.anulado = 0
                            $condicion
                            ".$wr."
								GROUP BY
								 pedido_clientes.id
							"); 

$row = $db->fetchArray($result); 
$count = $row['count']; 
if( $count >0 ) { 
        $total_pages = ceil($count/$limit); 
    } else { 
        $total_pages = 0; 
} 

if ($page > $total_pages) $page=$total_pages; 
$start = $limit*$page - $limit;  // do not put 	$limit*($page - 1) 
$responce = new stdClass();
$SQL = "SELECT 
					pedido_clientes.id,
					 pedido_clientes.prefijo,
					 pedido_clientes.consecutivo,
					 pedido_clientes.fecha,
					 pedido_clientes.hora_entrada,pedido_clientes.hora_salida,
					 pedido_clientes.placa,pedido_clientes.color,
					 pedido_clientes.liquidado,
					 detalle_pedido_clientes.valor,
					 detalle_pedido_clientes.cantidad,
					 sum(detalle_pedido_clientes.total) as total, 
					 detalle_pedido_clientes.anulado AS detalle_pedido_clientes_anulado,
					 pedido_clientes.liquidado AS detalle_pedido_clientes_anulado,
					 clase_vehiculo.id AS clase_vehiculo_id,
					 clase_vehiculo.clase_vehiculo AS clase_vehiculo_clase_vehiculo,
					 tipo_auto.id AS tipo_auto_id, tipo_auto.tipo_auto AS tipo_auto_tipo_auto,
					 centro_produccion.centro_produccion AS centro_produccion_centro_produccion
				FROM 
					pedido_clientes pedido_clientes INNER JOIN detalle_pedido_clientes detalle_pedido_clientes ON pedido_clientes.id = detalle_pedido_clientes.pedido_clientes_id
					 INNER JOIN empresa empresa ON pedido_clientes.empresa_id = empresa.id
					 INNER JOIN clase_vehiculo clase_vehiculo ON pedido_clientes.clase_vehiculo_id = clase_vehiculo.id
					 INNER JOIN centro_produccion centro_produccion ON pedido_clientes.centro_produccion_id = centro_produccion.id
					 INNER JOIN tipo_auto tipo_auto ON pedido_clientes.tipo_auto_id = tipo_auto.id
				WHERE 
					detalle_pedido_clientes.anulado = 0
					and pedido_clientes.anulado = 0
                    $condicion
                     ".$wh." 
					 group by  kardex.id, kardex.codigo, kardex.nombre_producto, kardex.valor
         ORDER BY $sidx $sord 
        LIMIT $start , $limit"; 
		
$result = $db->query( $SQL ); 
$responce->page = $page ;
$responce->sql = $SQL; 
$responce->total = $total_pages; 
$responce->records = $count; 
$total = 0;
$cantidad = 0;
$i=0; 
while( $row = $db->fetchArray($result) ) { 
	$total += $row[total];
	$cantidad += $row[cantidad];
    $responce->rows[$i]['id']=$row[id]; 
    $responce->rows[$i]['cell']=array($row[id],$row[codigo],$row[nombre_producto],$row[costo],$row[cantidad],$row[total]); 
    $i++; 
} 

//$responce->userdata['amount']  = $amttot; 
//$responce->userdata['tax']     = $taxtot; 
$responce->userdata['nombre']             = 'Totales:';
$responce->userdata['total']              = $total; 
$responce->userdata['cantidad']           = $cantidad; 


echo json_encode($responce);

		
function Strip($value)
{
	if(get_magic_quotes_gpc() != 0)
  	{
    	if(is_array($value))  
			if ( array_is_associative($value) )
			{
				foreach( $value as $k=>$v)
					$tmp_val[$k] = stripslashes($v);
				$value = $tmp_val; 
			}				
			else  
				for($j = 0; $j < sizeof($value); $j++)
        			$value[$j] = stripslashes($value[$j]);
		else
			$value = stripslashes($value);
	}
	return $value;
}

function array_is_associative ($array)
{
    if ( is_array($array) && ! empty($array) )
    {
        for ( $iterator = count($array) - 1; $iterator; $iterator-- )
        {
            if ( ! array_key_exists($iterator, $array) ) { return true; }
        }
        return ! array_key_exists(0, $array);
    }
    return false;
}
?>
    