<?php echo Tag::formRemote("libros/detalle_recibos_caja_diario", "update: mensajes", "id: facturas","name: facturas"); ?>

<h1>REPORTE DE RECIBOS DE CAJA Y ANTICIPOS POR FECHA</h1>

<table width="100%" border="0" cellpadding="0" id="r1">
  
  <tr>
    <th colspan="4" align="center">LISTADO DE RECIBOS DE CAJA Y ANTICIPOS POR FECHA</th>
  </tr>
  <tr>
    <td align="right">EMPRESA:</td>
    <td colspan="3">
		<?php $empresa = new Empresa(); echo Tag::select("empresa_id",$empresa->find(),'using: id,nombre_empresa'); ?>    
    <script>$('empresa_id').value = '<?php echo Session::get("id_empresa"); ?>';</script>
    </td>
  </tr>
  <tr>
    <td width="15%"><div align="right">Fecha</div></td>
    <td width="10%"><?php echo Tag::dateFieldMod("finicial","value: ".date("Y-m-d"),"size: 10") ?></td>
    <td width="19%">&nbsp;</td>
    <td width="10%">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4"><div align="center"><?php echo Tag::submitButton("Enviar"); ?></div></td>
  </tr>
</table>
<div align="center">
  <table border="0" cellpadding="2" id="remisiones"  cellspacing="2">
    <tr>
      <td align="center"><?php echo Tag::linkTo("#", Tag::image("64x64/Back.png",'width: 32px'),"onClick: window.close();") ?></td>
      <td align="center"><?php echo Tag::linkTo("menu/", Tag::image("iconos/inicio.png",'width: 32px'),"tittle: Regresar al Menu"); ?></td>
    </tr>
    <tr>
      <td align="center">Regresar</td>
      <td align="center">Inicio</td>
    </tr>
  </table>
</div>

<div id="mensajes" style="min-height:400px;"></div>

<div align="center">
  <table border="0" cellpadding="2" id="remisiones"  cellspacing="2">
    <tr>
      <td align="center"><?php echo Tag::linkTo("#", Tag::image("64x64/Back.png",'width: 32px'),"onClick: window.close();") ?></td>
      <td align="center"><?php echo Tag::linkTo("menu/", Tag::image("iconos/inicio.png",'width: 32px'),"tittle: Regresar al Menu"); ?></td>
    </tr>
    <tr>
      <td align="center">Regresar</td>
      <td align="center">Inicio</td>
    </tr>
  </table>
</div>

<?php echo Tag::endForm(); ?>
