<!--<?php 
/*echo View::getContent(); 
$menu = new Menu();
$s_menu = new Menu();
foreach($menu->find("aplicacion = '".Router::getApplication()."' and posicion='aplicaciones' and posicion_x<>0 ","order: orden") as $menu):
	echo "<h1>$menu->descripcion</h1>";	
		echo "<table align=\"center\" width=\"100%\" border=\"1\" cellspacing=\"2\" cellpadding=\"2\">";
		  echo "<tr>";
			echo "<td>"; 
			   echo "<ul style=\"width:100%;display:inline;\">";
				if($s_menu->count("posicion_y='$menu->posicion_x' and aplicacion = '".Router::getApplication()."' and posicion='aplicaciones' ")){			
						foreach($s_menu->find("posicion_y='$menu->posicion_x' and posicion='aplicaciones' ","order: orden") as $s_menu):
						echo "<li style=\"width:150px;height:100px;vertical-align:central;display:inline-block;padding:5px;\"  >";
							echo "<span><a href='".core::getInstancePath()."$s_menu->url' title='$s_menu->tittle'>".Tag::image("$s_menu->urlimage","width: 50px")."</a></span>";
							echo "<span style=\"padding:5px;\" >$s_menu->descripcion</span>";
						echo "</li>";
						endforeach;
				}
			 echo "</ul>";
			echo "</td>";
		echo "</tr>";
	  echo "</table>";
endforeach;*/
?>-->
<div id="horizontalTab">
<?php 

echo View::getContent(); 
$menu = new Menu();
$s_menu = new Menu();

$i=0;

echo "<ul>";
	foreach($menu->find("aplicacion = '".Router::getApplication()."' and posicion='aplicaciones' and posicion_x<>0 ","order: orden") as $menu):
		echo "<li><a href=\"#tab-$i\">$menu->descripcion</li>";	$i++; 
	endforeach;
echo "</ul>";

$i=0;
foreach($menu->find("aplicacion = '".Router::getApplication()."' and posicion='aplicaciones' and posicion_x<>0 ","order: orden") as $menu):
		echo "<div id=\"tab-$i\">"; $i++; 
			echo "<ul style=\"width:100%;display:inline;\">";
				if($s_menu->count("posicion_y='$menu->posicion_x' and aplicacion = '".Router::getApplication()."' and posicion='aplicaciones' ")){			
						foreach($s_menu->find("posicion_y='$menu->posicion_x' and posicion='aplicaciones' ","order: orden") as $s_menu):
						echo "<li style=\"width:150px;height:100px;vertical-align:central;display:inline-block;padding:5px;\"  >";
							echo "<span><a href='".core::getInstancePath()."$s_menu->url' title='$s_menu->tittle'>".Tag::image("$s_menu->urlimage","width: 50px")."</a></span>";
							echo "<span style=\"padding:5px;\" >$s_menu->descripcion</span>";
						echo "</li>";
						endforeach;
				}
			 echo "</ul>";
		echo "</div>";
endforeach;
?>
</div>

<!--<div id="horizontalTab2">
        <ul>
            <li><a href="#tab-1">Responsive Tab-1</a></li>
            <li><a href="#tab-2">Responsive Tab-2</a></li>
            <li><a href="#tab-3">Responsive Tab-3</a></li>
            <li><a href="#tab-4">Responsive Tab-4</a></li>
            <li><a href="#tab-5">Responsive Tab-5</a></li>
        </ul>

        <div id="tab-1">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eu scelerisque eros. Fusce ante orci, hendrerit sit amet metus sit amet, venenatis sodales felis. Morbi vel mi in leo dignissim convallis in a neque. Suspendisse sollicitudin nibh non dapibus condimentum. Etiam sit amet arcu ultricies, porttitor justo eget, scelerisque urna. Praesent non ligula nec ligula euismod condimentum eget sed augue. Ut feugiat, turpis id sollicitudin vestibulum, tellus massa adipiscing nisl, quis cursus nisl arcu vel ipsum.</p>
        </div>
        <div id="tab-2">
            <p>Quisque sodales sodales lacus pharetra bibendum. Etiam commodo non velit ac rhoncus. Mauris euismod purus sem, ac adipiscing quam laoreet et. Praesent vulputate ornare sem vel scelerisque. Ut dictum augue non erat lacinia, sed lobortis elit gravida. Proin ante massa, ornare accumsan ultricies et, posuere sit amet magna. Praesent dignissim, enim sed malesuada luctus, arcu sapien sodales sapien, ut placerat eros nunc vel est. Donec tristique mi turpis, et sodales nibh gravida eu. Etiam odio risus, porttitor non lacus id, rhoncus tempus tortor. Curabitur tincidunt molestie turpis, ut luctus nibh sollicitudin vel. Sed vel luctus nisi, at mattis metus. Aenean ultricies dolor est, a congue ante dapibus varius. Nulla at auctor nunc. Curabitur accumsan feugiat felis ut pretium. Praesent semper semper nisi, eu cursus augue.</p>
        </div>
        <div id="tab-3">
            <p>Mauris facilisis elit ut sem eleifend accumsan molestie sit amet dolor. Pellentesque dapibus arcu eu lorem laoreet, vitae cursus metus mattis. Nullam eget porta enim, eu rutrum magna. Duis quis tincidunt sem, sit amet faucibus magna. Integer commodo, turpis consequat fermentum egestas, leo odio posuere dui, elementum placerat eros erat id augue. Nullam at eros eget urna vestibulum malesuada vitae eu mauris. Aliquam interdum rhoncus velit, quis scelerisque leo viverra non. Suspendisse id feugiat dui. Nulla in aliquet leo. Proin vel magna sed est gravida rhoncus. Mauris lobortis condimentum nibh, vitae bibendum tortor vehicula ac. Curabitur posuere arcu eros.</p>
        </div>
        <div id="tab-4">
            <p>Donec egestas facilisis sapien sit amet euismod. Donec mollis lectus neque, in consectetur magna sodales et. Nam rutrum libero vitae magna sollicitudin aliquet. In tristique ultrices euismod. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse pretium congue sodales. Curabitur egestas, metus sed ultrices suscipit, metus nibh vehicula ligula, vel volutpat sapien nibh sed quam. Etiam elementum nisi eu risus congue, ut eleifend lectus ultricies. Vivamus in ligula fermentum, bibendum sapien eget, pretium est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ut ante non risus rutrum faucibus.</p>
        </div>
        <div id="tab-5">
            <p>Proin dignissim faucibus odio sollicitudin sagittis. Phasellus aliquet, erat vitae mollis consectetur, enim lectus ornare libero, et porta mi dui eu tellus. Morbi lobortis, elit at euismod porta, magna lacus mattis massa, a lacinia ligula risus et lectus. Sed et aliquam ligula. Nunc venenatis orci magna, quis facilisis sem porta non. Nunc sodales arcu in consectetur malesuada. Maecenas varius justo lacus, scelerisque viverra tellus luctus eu. Nam imperdiet ultricies suscipit. Ut urna mauris, eleifend quis lacinia non, mollis id libero. Praesent pharetra viverra ipsum at posuere. Quisque commodo tortor nec hendrerit faucibus. Fusce convallis urna et vehicula tincidunt. Duis sed vehicula justo, eu placerat nisi. Donec facilisis augue non turpis semper, eget condimentum mauris malesuada. Nunc in dignissim mi, sed laoreet felis.</p>
        </div>
</div>-->
<script>
jQuery(document).ready(function () {
	jQuery('#horizontalTab').responsiveTabs({
		rotate: false,
		startCollapsed: 'accordion',
		collapsible: 'accordion',
		setHash: true
	});
});	
</script>