<h4>FORMULARIO PERMITIR CLIENTES-DEUDORES</h5>

<?php echo Tag::formRemote(Router::getController()."/add", "update: mensajes", "id: fx","name: fx"); ?>

<table border="0" align="center" cellpadding="1">
  <tr>
    <td width="155" height="0" align="right" valign="middle" >PERMITIR CLIENTE</td>
    <td height="0" align="left" valign="middle" scope="col"><?php echo Tag::textFieldExt("clientes", "size: 20","maxlength: 20","placeholder: INGRESE CLIENTE") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">PERMITIR DEUDOR</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textFieldExt("deudores", "size: 20","maxlength: 20","placeholder: INGRESE DEUDOR") ?></td>
    </tr>
    <tr>
      <td align="right" >ESTADO</td>
      <td align="left" ><?php echo Tag::selectStatic('estado', 
												array('' => 'Seleccione...',
													  '0' => 'ACTIVO',
													  '1' => 'INACTIVO')) ?></td>
    </tr>
    <tr>
 	 <td colspan="2" align="center" >
     		<button type="submit" id="guardar" name="guardar">Guardar</button>
           
            <button type="button" id="cancelar" name="cancelar" onclick="doccancelar('<?php echo core::getInstancePath(); ?>','<?php echo Router::getController(); ?>');">Cancelar</button>
     </td>
    </tr> 
</table>

<div id="mensajes"></div>
<?php echo Tag::endForm() ?>

<!--

<div id="photos"></div>

<div id="camera">
	<span class="tooltip"></span>
	<span class="camTop"></span>
   
	
    <div id="screen"></div>
    <div id="buttons">
    	<div class="buttonPane">
        	<a id="shootButton" href="" class="blueButton">Foto</a>
        </div>
        <div class="buttonPane hidden">
        	<a id="cancelButton" href="" class="blueButton">Cancelar</a> <a id="uploadButton" href="" class="greenButton">Subir</a>
        </div>
    </div>
    
    <span class="settings"></span>
</div>


    -->
    
<?php // echo "<script>configcamara('".$_DOCUMENT["REQUEST"].core::getInstancePath()."public/javascript/fotos/assets/webcam/','".$_DOCUMENT["REQUEST"].core::getInstancePath()."clientes/')</script>"?>


<br />
<br />
	

	
    
    
<script language="JavaScript">
 jQuery(document).ready(function(e) {
	 
	 
 <?php 
		$entidad = new Clientes();
		
		foreach( $entidad->getPrimaryKeyAttributes() as $filas):
			echo "jQuery(\"#$filas\").attr(\"readonly\",\"readonly\");\n";
		endforeach;	
		
		foreach( $entidad->getNonPrimaryKeyAttributes() as $filas):
				foreach( $entidad->getNonPrimaryKeyAttributes() as $filas2):
					if($filas==$filas2){ echo "jQuery(\"#$filas2\").attr(\"required\",\"required\");\n"; break;} 
				endforeach;	
				
		endforeach;	
		
	?> 	
	
	 
	 jQuery("#razon_social").focus(function(){
		 	nom="";
			nom+=jQuery("#nombre1").val();nom+=" ";
			nom+=jQuery("#nombre2").val();nom+=" ";
			nom+=jQuery("#apellido1").val();nom+=" ";
			nom+=jQuery("#apellido2").val();nom+=" ";
			nom = nom.replace("  "," ");
	 		jQuery("#razon_social").val(nom);
		 });
	 
	 jQuery("#camara").click(function(event){
		 	event.preventDefault();
			 html = webcam.get_html(640, 480) ;
			 html += "<center><a href='javascript:void(webcam.snap())'>Tomar Foto</a></center>"; 
		 	 jQuery("#dialogo_camara").html(html);
			 jQuery("#dialogo_camara").dialog("open");
		 });
	
});

url = '<?php echo $_document["REQUEST"].core::getInstancePath();?>/public/javascript/webcam/';
//webcam.set_api_url( 'test.php' );
webcam.set_swf_url(url + 'webcam.swf');
webcam.set_api_url('<?php echo core::getInstancePath().Router::getController();?>/upload');	// The upload script
webcam.set_quality(80);				// JPEG Photo Quality
webcam.set_shutter_sound(true, url + '/shutter.mp3');

webcam.set_hook( 'onComplete', 'completado' );


function completado(response) {
		
     jQuery("#foto").val(response);
	//jQuery("#mensajes").html(response);
	jQuery("#dialogo_camara").dialog("close");
	
}


		
</script>
