<table id="tabla<?php echo Router::getController(); ?>"></table>
<div id="pager<?php echo Router::getController(); ?>"></div>
<script>
jQuery(document).ready(function(){

		
		jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Id','Cedula','Estado'], 
			colModel:[ 
				{ name:'id',index:'id', width:200},
				{ name:'nit',index:'nit', width:200}, 
				{ name:'estado',index:'estado', width:500}
			], 
			autoWidth:true,
			width: 550,
			height: 250,
			rowNum:50, 
			/*rowList:[10,20,30,40,50], */
			pager: '#pager<?php echo Router::getController(); ?>', 
			sortname: 'id', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"LISTADO DE USUARIOS HABILITADOS PARA CRÉDITOS",
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					if( jQuery("#nit")    ){ jQuery("#nit").val(fila['nit']); }
							
					<?php if(isset($_REQUEST["opcion"]) ){ ?>
					redireccionar_action("<?php echo Router::getController(); ?>/<?php echo $_REQUEST["opcion"]; ?>/?id="+fila['id'] );
					<?php }else{?>	
						jQuery("#dialogo_<?php echo Router::getController(); ?>").dialog("close");
					<?php } ?>
					
       		 }
		});
		 
		/*jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navGrid','#pager<?php //echo Router::getController(); ?>',{edit:false,add:false,del:false}); 
		jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navButtonAdd','#pager<?php //echo Router::getController(); ?>',{
		caption: "Columnas",
		title: "Reordena Columnas",
		onClickButton : function (){
			jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('columnChooser');
		
	});}*/
});
</script>