<div id="menuapp" class="menuapp">
<?php echo Tag::formRemote(Router::getController()."/add", "update: mensajes", "id: fx","name: fx"); ?>

<table border="0" align="center" cellpadding="1">
  <tr>
    <td width="153" height="0" align="right" valign="middle" >ID</td>
    <td width="167" height="0" align="left" valign="middle" scope="col"><?php echo Tag::textField("id", "size: 12","maxlength: 12") ?></td>
    <td colspan="2" align="left" scope="col">(Autoincremental no modifcificar si es nuevo dejar en blanco)</td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">APLICACION</td>
    <td height="0" colspan="3" align="left" valign="middle">
		<?php 
			$apl = new Aplicaciones();
			echo Tag::select('aplicaciones',$apl->find(), 'using: aplicacion,aplicacion', 'useDummy: no');
	   ?>
</td>

  </tr>
  <tr>
    <td height="0" align="right" valign="middle">POSICION</td>
    <td height="0" align="left" valign="middle">
		<?php 
			$apl = new Posiciones();
			echo Tag::select('posiciones',$apl->find(), 'using: posicion,posicion', 'useDummy: yes');
	   ?></td>
    <td colspan="2" align="left">(Izquierda - Navegacion - aplicaciones)</td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">POSICION_X</td>
    <td height="0" colspan="3" align="left" valign="middle">
			<?php echo Tag::numericField("posicion_x", "size: 10","maxlength: 20") ?>
            <button type="button" id="px" name="px">Ver Menus</button>(ASIGNELE UN NUMERO SI ES MENU PRINCIPAL, SI ES ITEM 0)
            </td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">POSICION_Y</td>
    <td height="0" colspan="3" align="left" valign="middle">
			<?php echo Tag::numericField("posicion_y", "size: 10","maxlength: 20") ?>
            <button type="button" id="py" name="py">Ver Items</button>(ASIGNELE UN NUMERO SI ES UN ITEM, SI ES MENU PRINCIPAL 0)
            </td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">ORDEN</td>
    <td height="0" colspan="3" align="left" valign="middle"><?php echo Tag::numericField("orden", "size: 10","maxlength: 5") ?></td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">DESCRIPCION</td>
    <td height="0" colspan="3" align="left" valign="middle"><?php echo Tag::textField("descripcion", "size: 40","maxlength: 100") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">TITULO</td>
    <td height="0" colspan="3" align="left" valign="middle"><?php echo Tag::textField("titulo", "size: 40","maxlength: 100") ?></td>
    </tr>
  <tr>
    <td height="0" align="right" valign="middle">URL</td>
    <td height="0" align="left" valign="middle"><?php echo Tag::textField("url", "size: 40","maxlength: 50") ?></td>
    <td colspan="2" align="left">(ejemplo: controlador/accion)</td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">&nbsp;</td>
    <td height="0" align="left" valign="middle">&nbsp;</td>
    <td width="128" align="left">&nbsp;</td>
    <td width="328" align="left">&nbsp;</td>
  </tr>
  
  <tr>
    <td height="0" align="right" valign="middle">SECCION</td>
    <td height="0" align="left" valign="middle">
		<?php 
			$apl = new Secciones();
			echo Tag::select('secciones',$apl->find(), 'using: seccion,seccion', 'useDummy: yes');
	   ?></td>
    <td colspan="2" align="left">(Nombre de la seccion)</td>
  </tr>
  <tr>
    <td height="0" align="right" valign="middle">URL IMAGE</td>
    <td height="0" colspan="3" align="left" valign="middle">
			<?php echo Tag::textField("urlimage", "size: 50","readonly: readonly","value: aplicaciones/agenda.jpg") ?>
            		<button type="button" id="imagen" name="imagen">Buscar Imagen</button></td>
    </tr>
    <tr>
      <td colspan="4" align="center" >&nbsp;</td>
    </tr>
    <tr>
 	 <td colspan="4" align="center" >
     		<button type="submit" id="guardar" name="guardar">Guardar</button>
           
            <button type="button" id="cancelar" name="cancelar" onclick="doccancelar('<?php echo core::getInstancePath(); ?>','<?php echo Router::getController(); ?>');">Cancelar</button>
     </td>
    </tr> 
</table>

<div id="mensajes"></div>

<div id="buscar_imagen">
	
<div align="center">
<h1>ESCOJA UNA IMAGEN O ICONO</h1>
<?php
$archivos1 = scandir($_SERVER['DOCUMENT_ROOT'].core::getInstancePath()."public/img/iconos");
if(count($archivos1)==2){
	Flash::error("NO SE ENCONTRO NINGUNA IMAGEN EL EL DIRECTORIO LOGO...");
}
//print_r($archivos1);
for($i=0;$i<=count($archivos1)-1;$i++){
	if($i%10==0){
		echo "<br />";
		echo "<br />";
	}
	if($archivos1[$i]!='.' && $archivos1[$i]!='..'){
		echo Tag::image("iconos/".$archivos1[$i],"width: 50px","heigth: 50px","border: 1","style: padding: 5px;","onClick: jQuery('#urlimage').val('iconos/".$archivos1[$i]."');jQuery('#buscar_imagen').dialog('close');"); 
	}
}?>
<?php echo view::getContent(); ?>

</div>
    
</div>

</div>

<div id="div_posicion_x"></div>
<div id="div_posicion_y"></div>

<?php echo Tag::endForm() ?>
    
<script language="JavaScript">

 
 jQuery(document).ready(function(e) {
	 
	  function escoger(url){
	  	jQuery("#urlimage").val(url);
		jQuery("#buscar_imagen").dialog("close");
	  }

	
	jQuery("#buscar_imagen").dialog({  autoOpen: false, width: 600 , height: 400 , title: "Escoger una Imagen" }); 
	jQuery("#div_posicion_x").dialog({ autoOpen: false, width: 600 , height: 400 , title: "Menu" }); 
	jQuery("#div_posicion_y").dialog({ autoOpen: false, width: 600 , height: 400 , title: "Items" }); 
	
	aplicar_css("menuapp");
	
	if( jQuery( "#buscar"     ) ){ jQuery( "#buscar"        ).button({ icons: {primary:'ui-icon ui-icon-circle-check' ,secondary:'ui-icon-triangle-1-s'}       });   }
	if( jQuery( "#px"         ) ){ jQuery( "#px"            ).button({ icons: {primary:'ui-icon ui-icon-circle-check' ,secondary:'ui-icon-triangle-1-s'}       });   }
	if( jQuery( "#py"         ) ){ jQuery( "#py"            ).button({ icons: {primary:'ui-icon ui-icon-circle-check' ,secondary:'ui-icon-triangle-1-s'}       });   }
	if( jQuery( "#imagen"     ) ){ jQuery( "#imagen"        ).button({ icons: {primary:'ui-icon ui-icon-circle-check' ,secondary:'ui-icon-triangle-1-s'}       });   }
	if( jQuery( "#enviar"     ) ){ jQuery( "#enviar"        ).button({ icons: {primary:'ui-icon ui-icon-circle-check' ,secondary:'ui-icon-triangle-1-s'}       });   }
	if( jQuery( "#guardar"    ) ){ jQuery( "#guardar"       ).button({ icons: {primary:'ui-icon ui-icon-circle-check' ,secondary:'ui-icon-triangle-1-s'}       });   }
	if( jQuery( "#cancelar"   ) ){ jQuery( "#cancelar"      ).button({ icons: {primary:'ui-icon ui-icon-circle-minus' ,secondary:'ui-icon ui-icon-closethick'} });   }

	jQuery("#imagen").click(function(){
		jQuery( "#buscar_imagen" ).dialog("open");	
	});
		
		
	jQuery("#px").click(function(){
		
		jQuery( "#div_posicion_x" ).html("");	
		
			if(jQuery("#aplicaciones").val() != '@' && jQuery("#posiciones").val() != '@' ){
				var jqXHR = jQuery.ajax({
						url:"<?php echo core::getInstancePath(); ?>menuapp/posicion_x/",
						type:"POST",
						
						data:{
								aplicaciones:        jQuery("#aplicaciones").val(),
								posiciones:          jQuery("#posiciones").val()
							},
							fail:function(){
								alert("error");
							},
							error:function(jqXHR,textStatus,errorThrown){
								alert("error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
							}
				});
		
			 	jqXHR.done(function(data){
					jQuery( "#div_posicion_x" ).html(data);
					jQuery( "#div_posicion_x" ).dialog("open");
				});
			}else{
				jQuery( "#dialogo_mensajes" ).html("");
				jQuery( "#dialogo_mensajes" ).html("Error Escoja una aplicacion y una posicion");
				jQuery( "#dialogo_mensajes" ).dialog("open");
				}
	});
	
	jQuery("#py").click(function(){
			jQuery( "#div_posicion_y" ).html("");	
				if( jQuery("#aplicaciones").val() != '@' && jQuery("#posiciones").val() != '@' && jQuery("#posicion_x").val() != ''  ){
					var jqXHR = jQuery.ajax({
						url:"<?php echo core::getInstancePath(); ?>menuapp/posicion_y/",
						type:"POST",
						
						data:{
								aplicaciones:        jQuery("#aplicaciones").val(),
								posiciones:          jQuery("#posiciones").val(),
								posicion_x:          jQuery("#posicion_x").val(),
								posicion_y:          jQuery("#posicion_y").val()
							},
							fail:function(){
								alert("error");
							},
							error:function(jqXHR,textStatus,errorThrown){
								alert("error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
							}
							});
					
						 jqXHR.done(function(data){
							jQuery( "#div_posicion_y" ).html(data);
							jQuery( "#div_posicion_y" ).dialog("open");
						});
				}else{
					jQuery( "#dialogo_mensajes" ).html("");
					jQuery( "#dialogo_mensajes" ).html("Error Escoja una aplicacion, una posicion y un menu ");
					jQuery( "#dialogo_mensajes" ).dialog("open");
				}
	});	
		
	
});
 
</script>
