<h4>REPORTE LISTADO DE CARTERA</h5>

<?php echo Tag::formRemote(Router::getController()."/detalle_cartera", "update: resultado", "id: fx","name: fx","before: mostrar();","success: esconder(); ","complete: esconder(); " ); ?>

<table id="filtros" width="100%" class="ui-corner-all ui-content">
<thead>
    <tr class="ui-jqgrid-titlebar ui-widget-header  ">
        <th colspan="4">Filtros</th>
    </tr>
</thead>
<tbody>
    <tr>
        <th>Cliente</th>
        <td colspan="3"><input type="number" id="nit" name="nit" size="30"  /></td>
    </tr>
    <tr>
        <th>Busqueda por Nombre</th>
        <td><input type="text" id="nombre" name="nombre" size="50" /></td>
        <th>Busqueda por Direccion</th>
        <td><input type="text" id="direccion" name="direccion" size="50" /></td>
    </tr>
    <tr>
        <th>Departamento</th>
        <td><?php  echo Tag::textFieldExt("departamentos","campo: departamento","size: 10"); ?></td>
        <th>Municipio</th>
        <td><?php  echo Tag::textFieldExt("municipios","campo: municipio","size: 10"); ?></td>
    </tr>
    <tr>
      <th colspan="4"><button type="submit" id="guardar" name="guardar">Enviar</button></th>
    </tr>
</tbody>
</table>

<?php echo Tag::endForm() ?>
<div id="loader">
<?php echo Tag::image("ajax-loader.gif"); ?>
</div>
<div id="resultado" style="min-height:600px; max-height:800px; overflow:auto;" ></div>


<div id="mensajes"></div>


<script>
function mostrar(){
		jQuery("#loader").show();
 
	}
function esconder(){
		jQuery("#loader").hide();
	}	
	
esconder();
	
function ver_pagos(id){
	jQuery.ajax({
			type:"POST"
			,url:"<?php echo core::getInstancePath(); ?>recibos_caja/ver_pagos/"
			,async:true
			,data:{
					creditos_id: id
				}
			,success: function(data){
					jQuery("#div_ver_pagos").html("");
					jQuery("#div_ver_pagos").html(data);
					jQuery("#div_ver_pagos").dialog("open");
				}
			,error: function(data){
					jQuery("#dialogo_mensajes").html("Error Cargando este Elemento" + data);
					jQuery("#dialogo_mensajes").dialog("open");
				}	
		});			

}

function ver(id){
	jQuery.ajax({
			type:"POST"
			,url:"<?php echo core::getInstancePath(); ?>creditos/show/"
			,async:true
			,data:{
					id: id
				}
			,success: function(data){
					jQuery("#div_ver_pagos").html("");
					jQuery("#div_ver_pagos").html(data);
					jQuery("#div_ver_pagos").dialog("open");
				}
			,error: function(data){
					jQuery("#dialogo_mensajes").html("Error Cargando este Elemento" + data);
					jQuery("#dialogo_mensajes").dialog("open");
				}	
		});			

}


function ver_cuotas(id,id2){
		
			 jQuery.ajax({
					url:"<?php echo core::getInstancePath(); ?>detalle_cxc/find_buscar/",
					type:"POST",
					async:true,
					data:{
							clientes_id:  id,
							creditos_id:  id2
						}
					,success: function(data){
							jQuery("#div_ver_pagos").html("");
							jQuery("#div_ver_pagos").html(data);
							jQuery("#div_ver_pagos").dialog("open");
						}
					,error: function(data){
							jQuery("#dialogo_mensajes").html("Error Cargando este Elemento" + data);
							jQuery("#dialogo_mensajes").dialog("open");
						}	
				});

	}

</script>