<h4>REPORTE LISTADO DE CARTERA</h5>

<?php echo Tag::formRemote(Router::getController()."/detalle_cartera", "update: resultado", "id: fx","name: fx","before: mostrar();","success: esconder(); ","complete: esconder(); " ); ?>

<table id="filtros" width="100%" class="ui-corner-all ui-content">
<thead>
    <tr class="ui-jqgrid-titlebar ui-widget-header  ">
        <th colspan="4">Filtros</th>
    </tr>
</thead>
<tbody>
    <tr>
        <th>Cliente</th>
        <td colspan="3"><input type="number" id="nit" name="nit" size="30"  /></td>
    </tr>
    <tr>
        <th>B&uacute;squeda por Nombre</th>
        <td><input type="text" id="nombre" name="nombre" size="50" /></td>
        <th>B&uacute;squeda por Direcci&oacute;n</th>
        <td><input type="text" id="direccion" name="direccion" size="50" /></td>
    </tr>
    <tr>
        <th>Departamento</th>
        <td><?php  echo Tag::textFieldExt("departamentos","campo: departamento","size: 10"); ?></td>
        <th>Municipio</th>
        <td><?php  echo Tag::textFieldExt("municipios","campo: municipio","size: 10"); ?></td>
    </tr>
    <tr>
      <th colspan="4"><button type="submit" id="guardar" name="guardar">Enviar</button></th>
    </tr>
</tbody>
</table>

<?php echo Tag::endForm() ?>
<div id="loader">
<?php echo Tag::image("ajax-loader.gif"); ?>
</div>
<div id="resultado" style="min-height:200px; max-height:200px; overflow:auto;" ></div>

<br />
<button type="button" id="imprimir" name="imprimir">Imprimir</button>

<button type="button" id="imprimir2" name="imprimir2">Excel</button>

<button type="button" id="imprimir3" name="imprimir3">Pdf</button>

<div id="mensajes"></div>


<script>
function mostrar(){
		jQuery("#loader").show();
 
	}
function esconder(){
		jQuery("#loader").hide();
	}	
	
esconder();

	
function ver_pagos(id){
	jQuery.ajax({
			type:"POST"
			,url:"<?php echo core::getInstancePath(); ?>recibos_caja/ver_pagos/"
			,async:true
			,data:{
					creditos_id: id
				}
			,success: function(data){
					jQuery("#dialogo_mensajes").html("");
					jQuery("#dialogo_mensajes").html(data);
					jQuery("#dialogo_mensajes").dialog("open");
				}
			,error: function(data){
					jQuery("#dialogo_mensajes").html("Error Cargando este Elemento" + data);
					jQuery("#dialogo_mensajes").dialog("open");
				}	
		});			

}

function ver(id){
	jQuery.ajax({
			type:"POST"
			,url:"<?php echo core::getInstancePath(); ?>creditos/show/"
			,async:true
			,data:{
					id: id
				}
			,success: function(data){
					jQuery("#dialogo_mensajes").html("");
					jQuery("#dialogo_mensajes").html(data);
					jQuery("#dialogo_mensajes").dialog("open");
				}
			,error: function(data){
					jQuery("#dialogo_mensajes").html("Error Cargando este Elemento" + data);
					jQuery("#dialogo_mensajes").dialog("open");
				}	
		});			

}


function ver_cuotas(id,id2){
		
			 jQuery.ajax({
					url:"<?php echo core::getInstancePath(); ?>detalle_cxc/find_buscar/",
					type:"POST",
					async:true,
					data:{
							clientes_id:  id,
							creditos_id:  id2
						}
					,success: function(data){
							jQuery("#dialogo_mensajes").html("");
							jQuery("#dialogo_mensajes").html(data);
							jQuery("#dialogo_mensajes").dialog("open");
						}
					,error: function(data){
							jQuery("#dialogo_mensajes").html("Error Cargando este Elemento" + data);
							jQuery("#dialogo_mensajes").dialog("open");
						}	
				});

	}
	
jQuery(document).ready(function(e) {
    jQuery("#imprimir").click(function(e) {
        e.preventDefault();
		var data = jQuery("#fx").serialize();
		url = "<?php echo core::getInstancePath(); ?>reports/detalle_cartera/?"+data+"&print=html";
	    window.open(url, '_blank');
    });
	
	 jQuery("#imprimir2").click(function(e) {
        e.preventDefault();
		var data = jQuery("#fx").serialize();
		url = "<?php echo core::getInstancePath(); ?>reports/detalle_cartera/?"+data+"&print=excel";
	    window.open(url, '_blank');
    });
	
	jQuery("#imprimir3").click(function(e) {
        e.preventDefault();
		var datos = jQuery("#fx").serialize();
		alert(datos);
		url = "<?php echo core::getInstancePath(); ?>reports/detalle_cartera/?"+datos+"&print=pdf";
		alert(url);
	    window.open(url, '_blank');
		/*var datos = jQuery("#fx").serialize();
				var jqXHR = jQuery.ajax({
						url:"<?php //echo core::getInstancePath(); ?>reports/detalle_clientes/?"+datos+"&print=pdf",
						type:"POST",
						data: datos,
							fail:function(){
								alert("error");
							},
							error:function(jqXHR,textStatus,errorThrown){
								alert("error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
							}
				});

		 jqXHR.done(function(datos){
			//url = "<?php //echo core::getInstancePath(); ?>reports/generarpdf/?"+data+"&print=pdf";
	    	//window.open(url, '_blank');
			
				var jqXHR2 = jQuery.ajax({
					url:"<?php echo core::getInstancePath(); ?>reports/generapdf/",
					type:"POST",
					dataType:"pdf",
					data:{ 
							print: "pdf",
							html: datos,
							title: "Reportes",
							url: "www.dydsoluciones.net",
							author: "dydsoluciones.net"
						},
						fail:function(jqXHR,textStatus,errorThrown){
							alert("error erro 2 "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
						},
						error:function(jqXHR,textStatus,errorThrown){
							alert("error error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
						}
				});
				
				jqXHR2.done(function(data){
					jQuery("#resultado").html(data);
					//url = "<?php //echo $_SERVER['DOCUMENT_ROOT'].core::getInstancePath(); ?>public/temp/Reportes.pdf";
			    	//window.open(url, '_blank');
				}); // jqXHR2
			});// jqXHR*/

	    });//imprimir 3
});

</script>