<h1>Modulo de Reportes Cr&eacute;ditos</h1>   	

<table align="center" width="100%" border="1" cellspacing="2" cellpadding="2">

 

  <tr>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("reports/cred_clientes",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php //echo Tag::linkTo("reports/cxc_resumen",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php //echo Tag::linkTo("reports/solicitud",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php //echo Tag::linkTo("reports/cxc",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

  </tr>

  <tr>

    <td height="30" align="center" valign="middle">Cr&eacute;ditos por Cliente</td>

    <td height="30" align="center" valign="middle">&nbsp;</td>

    <td height="30" align="center" valign="middle">&nbsp;</td>

    <td height="30" align="center" valign="middle">&nbsp;</td>

  </tr>
</table>