<h4>REPORTE DE CR&Eacute;DITOS POR CLIENTE</h5>

<?php echo Tag::formRemote(Router::getController()."/buscar_creditos", "update: mensajes", "id: fx","name: fx"); ?>

<table border="0" align="center" cellpadding="1">
  <tr>
    <td width="155" height="0" align="right" valign="middle" >CLIENTES</td>
    <td height="0" align="left" valign="middle" scope="col"><?php echo Tag::textFieldExt("clientes", "size: 20","maxlength: 20","placeholder: INGRESE CLIENTE") ?></td>
    </tr>
    <tr>
 	 <td colspan="2" align="center" >
     		<button type="submit" id="guardar" name="guardar">Ver reportes</button>
           
            <button type="button" id="cancelar" name="cancelar" onclick="doccancelar('<?php echo core::getInstancePath(); ?>','<?php echo Router::getController(); ?>');">Cancelar</button>
     </td>
    </tr> 
</table>

<div id="mensajes"></div>
<?php echo Tag::endForm() ?>