<?php echo view::getContent(); ?>
<table width="100%" border="1" cellpadding="2" cellspacing="2" class="ui-corner-all ui-content" id="filtros">
<thead>
    <tr class="ui-jqgrid-titlebar ui-widget-header  ">
        <th>Codigo</th>
        <th>Nombres</th>
        <th>Direccion Casa</th>
        <th>Total Credito</th>
        <th>Pagado</th>
        <th>Saldo</th>
        <th>Saldo Capital</th>
        <th class="oculto">Ver Credito</th>
        <th class="oculto">Ver Cuotas</th>
        <th class="oculto">Ver Pagos</th>
    </tr>
</thead>
<tbody>
<?php 
$a=0;$a1=0;$a2=0;$a3=0;
?>
<?php foreach($detalles as $detalles): ?>
    <tr>
        <td align="left" nowrap="nowrap"><?php echo $detalles->id; ?></td>
        <td align="left" nowrap="nowrap"><?php echo $detalles->razon_social; ?></td>
        <td align="left" nowrap="nowrap"><?php echo $detalles->direccion; ?></td>
        <td align="left" nowrap="nowrap">$ <?php echo number_format($detalles->valor_total);                       $a+=$detalles->valor_total; ?></td>
        <td align="left" nowrap="nowrap">$ <?php echo number_format($detalles->pagado);                            $a1+=$detalles->pagado;?></td>
        <td align="left" nowrap="nowrap">$ <?php echo number_format($detalles->valor_total+$detalles->pagado);     $a2+=$detalles->valor_total+$detalles->pagado;?></td>
        <td align="left" nowrap="nowrap">$ <?php echo number_format($detalles->capital+$detalles->capital_pagado); $a3+=$detalles->capital+$detalles->capital_pagado;?></td>
        <td align="left" nowrap="nowrap" class="oculto"><?php echo Tag::linkTo("creditos/show/$detalles->creditos_id",Tag::image("iconos/Visa.png","border: 0","width: 32px"),"target: _blank"); ?></td>
        <td align="left" nowrap="nowrap" class="oculto"><?php echo Tag::image("iconos/Visa.png","border: 0","width: 32px","id: a$detalles->creditos_id","onclick: ver_cuotas($detalles->clientes_id,$detalles->creditos_id)"); ?></td>
        <td align="left" nowrap="nowrap" class="oculto"><?php echo Tag::image("iconos/Folder.png","border: 0","width: 32px","id: b$detalles->creditos_id","onclick: ver_pagos($detalles->creditos_id)"); ?></td>
    </tr>
   
<?php endforeach; ?>    

  <tr>
      <th align="left" nowrap="nowrap">&nbsp;</th>
      <th align="left" nowrap="nowrap">&nbsp;</th>
      <th align="left" nowrap="nowrap">&nbsp;</th>
      <th align="left" nowrap="nowrap">$ <?php echo number_format($a);  ?></th>
      <th align="left" nowrap="nowrap">$ <?php echo number_format($a1);  ?></th>
      <th align="left" nowrap="nowrap">$ <?php echo number_format($a2);  ?></th>
      <th align="left" nowrap="nowrap">$ <?php echo number_format($a3);  ?></th>
      <th align="left" nowrap="nowrap" class="oculto">&nbsp;</th>
      <th align="left" nowrap="nowrap" class="oculto">&nbsp;</th>
      <th align="left" nowrap="nowrap" class="oculto">&nbsp;</th>
   </tr>
    
    
</tbody>
</table>
<div id="div_ver_pagos"></div>
<script>

jQuery(document).ready(function(e) {
	jQuery("#div_ver_pagos").dialog(
			{ autoOpen: false 
				,width: 800
 			    ,height: 500
				,title: " Pagos Realizados " 
				,modal: true
				,buttons: {
					"Cerrar": function() {
							jQuery( this ).dialog( "close" );
						}
				}
	 });
  
});

</script>
