<?php echo view::getContent(); ?>
<?php if(isset($_REQUEST["print"])){ ?>
<style>
	.oculto{ display:none;}
</style>
<table width="100%" border="1" cellpadding="1" cellspacing="1" class="ui-corner-all ui-content" >
    <tr >
      <th colspan="7">Informe Listado de Clientes</th>
    </tr>
    <tr >
      <th colspan="7"><?php echo Session::get("nombre_empresa"); ?></th>
    </tr>
    <tr >
      <th colspan="7">Reporte Impreso el dia <?php echo date("Y-m-d"); ?> </th>
    </tr>
    <tr >
      <th colspan="7">Filtrado por:</th>
    </tr>
    <tr >
      <th width="25%" align="left">Identificacion:</th>
      <th width="75%" colspan="6" align="left"><?php echo $_REQUEST["nit"] ?></th>
    </tr>
    <tr >
      <th align="left">Nombre</th>
      <th colspan="6" align="left"><?php echo $_REQUEST["nombre"] ?></th>
  </tr>
    <tr >
      <th align="left">Direccion </th>
      <th colspan="6" align="left"><?php echo $_REQUEST["direccion"] ?></th>
    </tr>
</table>	 
<?php } ?>

<table width="100%" border="1" cellpadding="1" cellspacing="1" class="ui-corner-all ui-content" >
<thead>
    <tr class="ui-jqgrid-titlebar ui-widget-header  ">
        <th>Codigo</th>
        <th>Nombres</th>
        <th>Direccion Casa</th>
        <th>Telefono</th>
        <th>celular</th>
        <th>Departamento</th>
        <th>Municipio</th>
    </tr>
</thead>
<tbody>
<?php foreach($detalles as $detalles): ?>
    <tr>
        <td align="left" ><?php echo $detalles->id; ?></td>
        <td align="left" ><?php echo $detalles->razon_social; ?></td>
        <td align="left" ><?php echo $detalles->direccion; ?></td>
        <td align="left" ><?php echo $detalles->telefono; ?></td>
        <td align="left" ><?php echo $detalles->celular; ?></td>
        <td align="left" ><?php echo $detalles->departamento; ?></td>
        <td align="left" ><?php echo $detalles->municipio; ?></td>
    </tr>
<?php endforeach; ?>    
</tbody>
</table>


