<h4>Extracto Resumen</h5>
<table width="100%" cellpadding="0" cellspacing="0" >

<?php 
 //Flash::notice($fecha);
$sql ="SELECT
		 cxc.id AS cxc_id,
		 cxc.creditos_id AS cxc_creditos_id,
		 cxc.prefijo AS cxc_prefijo,
		 cxc.consecutivo AS cxc_consecutivo,
		 cxc.tipo_documento_id AS cxc_tipo_documento_id,
		 cxc.fecha AS cxc_fecha,
		 cxc.valor_total AS cxc_valor_total,
		 cxc.pagado AS cxc_pagado,
		 cxc.anulado AS cxc_anulado,
		 creditos.id AS creditos_id,
		 creditos.empresa_id AS creditos_empresa_id,
		 creditos.clientes_id AS creditos_clientes_id,
		 creditos.solicitud_id AS creditos_solicitud_id,
		 creditos.tipo_documento_id AS creditos_tipo_documento_id,
		 creditos.prefijo AS creditos_prefijo,
		 creditos.consecutivo AS creditos_consecutivo,
		 creditos.fecha_act AS creditos_fecha_act,
		 creditos.fecha AS creditos_fecha,
		 creditos.anulado AS creditos_anulado,
		 creditos.observaciones AS creditos_observaciones,
		 creditos.fecha_cuota AS creditos_fecha_cuota,
		 creditos.cuotas AS creditos_cuotas,
		 creditos.valor_cuotas AS creditos_valor_cuotas,
		 creditos.total_credito AS creditos_total_credito,
		 creditos.porcentaje AS creditos_porcentaje,
		 clientes.id AS clientes_id,
		 clientes.nit AS clientes_nit,
		 clientes.nombre1 AS clientes_nombre1,
		 clientes.nombre2 AS clientes_nombre2,
		 clientes.apellido1 AS clientes_apellido1,
		 clientes.apellido2 AS clientes_apellido2,
		 clientes.foto AS clientes_foto,
		 clientes.url AS clientes_url,
		 clientes.razon_social AS clientes_razon_social,
		 clientes.direccion_casa AS clientes_direccion_casa,
		 clientes.direccion_oficina AS clientes_direccion_oficina,
		 clientes.telefono1 AS clientes_telefono1,
		 clientes.telefono2 AS clientes_telefono2,
		 clientes.sueldo AS clientes_sueldo,
		 clientes.otros_ingresos AS clientes_otros_ingresos,
		 clientes.eps AS clientes_eps,
		 clientes.casa AS clientes_casa,
		 clientes.vehiculos AS clientes_vehiculos,
		 clientes.celular AS clientes_celular,
		 clientes.departamentos_id AS clientes_departamentos_id,
		 clientes.municipios_id AS clientes_municipios_id,
		 clientes.activo AS clientes_activo,
		 clientes.correo AS clientes_correo,
		 clientes.web AS clientes_web,
		 empresa.id AS empresa_id,
		 empresa.nombre_corto AS empresa_nombre_corto,
		 empresa.nombre_empresa AS empresa_nombre_empresa,
		 empresa.nit AS empresa_nit,
		 empresa.direccion AS empresa_direccion,
		 empresa.logo AS empresa_logo,
		 empresa.regimen_id AS empresa_regimen_id,
		 empresa.telefonos AS empresa_telefonos,
		 empresa.celular AS empresa_celular,
		 empresa.web AS empresa_web,
		 empresa.correo AS empresa_correo,
		 empresa.activo AS empresa_activo,
		 empresa.kardex_id_default AS empresa_kardex_id_default,
		 empresa.tipo_costeo AS empresa_tipo_costeo,
		 empresa.valor_caja_defecto AS empresa_valor_caja_defecto,
		 empresa.cobro_tarifa AS empresa_cobro_tarifa,
		 empresa.porcentaje AS empresa_porcentaje,
		 '$fecha' AS fecha_corte,
		 ( select r.fecha from recibos_caja r, detalle_recibos_caja dr
				where r.id = dr.recibos_caja_id
				and dr.anulado = '0'
				and dr.descripcion like 'INTERESES%'
				and r.clientes_id = clientes.id
				and r.creditos_id = creditos.id
		  order by r.fecha desc limit 1 ) AS fecha_recibo_caja,
		 ifnull(prestamos_mes(creditos.id,clientes.id,'$fecha','valor' ),0) as valor_prestado_mes,
		 ifnull(prestamos_mes(creditos.id,clientes.id,'$fecha','intereses' ),0) as valor_prestado_intereses,
		 ifnull(prestamos_mes(creditos.id,clientes.id,'$fecha','dias' ),0) as dias_prestado_intereses,
		 (
		round(
				(
				  (
					(cxc.valor_total +  cxc.pagado - ifnull(prestamos_mes(creditos.id,clientes.id,'$fecha','valor' ),0)
				  )
				  * ( creditos.porcentaje /100 ) ) /30
				)
				  * (datediff('$fecha',
					   case
			when ifnull((select r.fecha from recibos_caja r, detalle_recibos_caja dr
					where r.id = dr.recibos_caja_id
						and dr.anulado = '0'
						and dr.descripcion like 'INTERESES%'
						and r.clientes_id = clientes.id
					  and r.creditos_id = creditos.id
					  order by r.fecha desc limit 1),0)=0 then creditos.fecha
			else
				(select r.fecha from recibos_caja r, detalle_recibos_caja dr
					where r.id = dr.recibos_caja_id
						and dr.anulado = '0'
						and dr.descripcion like 'INTERESES%'
						and r.clientes_id = clientes.id
					  and r.creditos_id = creditos.id
					  order by r.fecha desc limit 1)
			end) + 1)
			  ,-3)
		) as intereses,
	ifnull((select sum(dr.valor) from recibos_caja r, detalle_recibos_caja dr
					where r.id = dr.recibos_caja_id
						and dr.anulado = '0'
						and dr.descripcion not like 'INTERESES%'
						and r.clientes_id = clientes.id
					  and r.creditos_id = creditos.id
				and concat(year(r.fecha),month(r.fecha)) = concat(year('$fecha'),month('$fecha'))
					  ),0) as abonos_mes,
	(datediff('$fecha',
					   case
			when ifnull((select r.fecha from recibos_caja r, detalle_recibos_caja dr
					where r.id = dr.recibos_caja_id
						and dr.anulado = '0'
						and dr.descripcion like 'INTERESES%'
						and r.clientes_id = clientes.id
					  and r.creditos_id = creditos.id
					  order by r.fecha desc limit 1),0)=0 then creditos.fecha
			else
				(select r.fecha from recibos_caja r, detalle_recibos_caja dr
					where r.id = dr.recibos_caja_id
						and dr.anulado = '0'
						and dr.descripcion like 'INTERESES%'
						and r.clientes_id = clientes.id
					  and r.creditos_id = creditos.id
					  order by r.fecha desc limit 1)
			end) + 1) as dias_atraso
	FROM
		 creditos creditos INNER JOIN cxc cxc ON creditos.id = cxc.creditos_id
		 INNER JOIN clientes clientes ON creditos.clientes_id = clientes.id
		 INNER JOIN empresa empresa ON creditos.empresa_id = empresa.id
	where
	 cxc.valor_total +  cxc.pagado <> 0";
	
$db = DbBase::rawConnect();
$result = $db->query($sql);
//Flash::notice($sql);
?>
<thead>
<tr class="ui-widget ui-widget-content ui-corner-all ui-dialog-titlebar ui-widget-header ui-front">
      	<td>Ident.</td>
        <td width="200px">Nombre</td>
        <td>Deuda</td>
        <td>Dias/Dda</td>
        <td>Pres/mes</td>
        <td>Dias</td>
        <td>Int/Dias</td>
        <td>Abonos</td>
        <td>Saldo</td>
        <td>%</td>
        <td>Int</td>
        <td>Total/Int</td>
        <td>Saldo Total</td>
        
      </tr>
</thead>
<tbody>      
<?php while($row = $db->fetchArray($result)){ ?>
      <tr>
      	<td><?php echo $row["clientes_nit"]; //$F{clientes_nit} ?></td>
        <td><?php echo $row["clientes_razon_social"]; //$F{clientes_razon_social}  ?></td>
        <td><?php echo $row["cxc_valor_total"] + $row["cxc_pagado"] + $row["abonos_mes"] - $row["valor_prestado_mes"] ;  //$F{cxc_valor_total}+$F{cxc_pagado}+$F{abonos_mes}-$F{valor_prestado_mes} ?></td>
        <td><?php echo $row["dias_atraso"]; //$F{dias_atraso} ?></td>
        <td><?php echo $row["valor_prestado_mes"]; //$F{valor_prestado_mes} ?></td>
        <td><?php echo $row["dias_prestado_intereses"]; //$F{dias_prestado_intereses}  ?></td>
        <td><?php echo $row["valor_prestado_intereses"]; //$F{valor_prestado_intereses} ?></td>
        <td><?php echo $row["abonos_mes"]; //$F{abonos_mes} ?></td>
        <td><?php echo ($row["cxc_valor_total"]+$row["cxc_pagado"]+$row["abonos_mes"]-$row["valor_prestado_mes"])-$row["abonos_mes"]; //($F{cxc_valor_total}+$F{cxc_pagado}+$F{abonos_mes}-$F{valor_prestado_mes})-$F{abonos_mes} ?></td>
        <td><?php echo $row["creditos_porcentaje"]; //$F{creditos_porcentaje}  ?></td>
        <td><?php echo $row["intereses"]; //$F{intereses}  ?></td>
        <td><?php echo $row["valor_prestado_intereses"]+$row["intereses"]; //$F{valor_prestado_intereses}+$F{intereses}  ?></td>
        <td><?php echo (($row["cxc_valor_total"]+$row["cxc_pagado"]+$row["abonos_mes"]-$row["valor_prestado_mes"])-$row["abonos_mes"] + $row["valor_prestado_mes"]); //(($F{cxc_valor_total}+$F{cxc_pagado}+$F{abonos_mes}-$F{valor_prestado_mes})-$F{abonos_mes}) + $F{valor_prestado_mes}  ?></td>
        
      </tr>

<?php } ?>
</tbody>
</table>
<?php echo view::getContent(); ?>
<style media="print">
  #print{
	  	display:none;
	  }
</style>
<div align="center" id="print">
	<?php echo Tag::linkTo(Router::getController()."/detalle_extracto_resumen_csv/?fecha=".$_REQUEST["fecha"],Tag::image("iconos/excel.png","width: 50px"),"target: _blank"); ?>
</div>