<?php //echo view::getContent(); 

if(isset($_REQUEST["print"])){ 

	if($_REQUEST["print"]=="pdf"){ 
		ob_start(); 
	}
	
	if($_REQUEST["print"]=="html" || $_REQUEST["print"]=="pdf" || $_REQUEST["print"]=="excel"){?>
    		<style>

			/*Estilo para las tablas en los reportes*/
			table.gridtable {
				font-family: arial;
				font-size:11px;
				color:#333333;
				border-width: 1px;
				border-color: #217ec4;
				border-collapse: collapse;
				border-style: solid;
			}
			table.gridtable th {
				border-width: 1px;
				padding: 8px;
				border-style: solid;
				border-color: #217ec4;
				background-color: #70a9d2;
			}
			table.gridtable td {
				border-width: 1px;
				padding: 8px;
				border-style: solid;
				border-color: #217ec4;
				background-color: #e8f4fd;
			}
			
			.no_mostrar{
				display:none
			}
			
			</style>
	<?php } 
	
	if($_REQUEST["print"]=="excel"){
		header("Content-type: application/vnd.ms-excel; name='excel'");
		header("Content-Disposition: filename=ListadoRecibosCaja.xls");
		header("Pragma: no-cache");
		header("Expires: 0");	
	} 
	
	
?>
<table width="100%" border="1" cellpadding="1" cellspacing="1" class="gridtable" >
    <tr >
      <th colspan="8">Informe Listado Recibos de caja</th>
    </tr>
    <tr >
      <th colspan="8"><?php echo Session::get("nombre_empresa"); ?></th>
    </tr>
    <tr >
      <th colspan="8">Reporte Impreso el d&iacute;a <?php echo date("Y-m-d"); ?> </th>
    </tr>
    <tr >
      <th colspan="8">Filtrado por:</th>
    </tr>
    <tr >
      <th align="left">Fecha Desde:</th>
      <th colspan="7" align="left"><?php echo $_REQUEST["desde"] ?> Fecha Hasta: <?php echo $_REQUEST["hasta"] ?></th>
    </tr>
    <tr >
      <th align="left">Cobrador: </th>
      <th colspan="7" align="left"><?php echo $_REQUEST["cobradores"] ?></th>
    </tr>
</table>	 
<?php } ?>

<br />
<h4>Anticipos de de Caja</h4>

<table width="100%" border="1" cellpadding="2" cellspacing="2" class="gridtable" id="filtros">
<thead>
    <tr class="ui-jqgrid-titlebar ui-widget-header  ">
        <th>N&uacute;mero</th>
        <th>Fecha</th>
        <th>Valor</th>
        <th class="no_mostrar">Opciones</th>
    </tr>
</thead>
<tbody>
<?php 
$a_a=0;
?>
<?php foreach($detalles_caja_cobrador as $detalles): ?>
    <tr>
        <td align="left" nowrap="nowrap"><?php echo $detalles->id; ?></td>
        <td align="left" nowrap="nowrap"><?php echo $detalles->fecha; ?></td>
        <td align="right" nowrap="nowrap">$ <?php echo number_format($detalles->valor);     $a_a +=$detalles->valor; ?></td>
        <td align="center" nowrap="nowrap" class="no_mostrar"><?php echo Tag::linkTo("caja_cobrador/show/$detalles->id",Tag::image("iconos/Visa.png","border: 0","width: 32px"),"target: _blank"); ?></td>
    </tr>
   
<?php endforeach; ?>    
  <tr>
      <th colspan="2" align="right" nowrap="nowrap">Totales</th>

      <th align="right" nowrap="nowrap">$ <?php echo number_format($a_a);  ?></th>
      <th align="right" nowrap="nowrap" class="no_mostrar">&nbsp;</th>
    </tr>
</tbody>
</table>


<br />
<h4>Recibos de Caja</h4>
<table width="100%" border="1" cellpadding="2" cellspacing="2" class="gridtable" id="filtros">
<thead>
    <tr class="ui-jqgrid-titlebar ui-widget-header  ">
        <th>N&uacute;mero <br />Recibo Caja</th>
        
        <th>Fecha</th>
        <th>Capital</th>
        <th>Intereses</th>
        <th>Total Pagado</th>
        <th class="no_mostrar">Opciones</th>
    </tr>
</thead>
<tbody>
<?php 
$rc_a=0;$rc_a1=0;$rc_a2=0;$rc_a3=0;
?>
<?php foreach($detalles_recibos_caja as $detalles): ?>
    <tr>
        <td align="left" nowrap="nowrap"><?php echo $detalles->prefijo.$detalles->consecutivo; ?></td>
        <td align="left" nowrap="nowrap"><?php echo $detalles->razon_social; ?></td>
        <td align="left" nowrap="nowrap"><?php echo $detalles->fecha; ?></td>
        <td align="right" nowrap="nowrap">$ <?php echo number_format($detalles->capital);     $rc_a +=$detalles->capital; ?></td>
        <td align="right" nowrap="nowrap">$ <?php echo number_format($detalles->intereses);   $rc_a1+=$detalles->intereses;?></td>
        <td align="right" nowrap="nowrap">$ <?php echo number_format($detalles->valor);       $rc_a2+=$detalles->valor;?></td>
        <td align="center" nowrap="nowrap" class="no_mostrar"><?php echo Tag::linkTo("recibos_caja/show/$detalles->id",Tag::image("iconos/Visa.png","border: 0","width: 32px"),"target: _blank"); ?></td>
    </tr>
   
<?php endforeach; ?>    
  <tr>
      <th colspan="3" align="right" nowrap="nowrap">Totales</th>
      <th align="right" nowrap="nowrap">$ <?php echo number_format($rc_a);  ?></th>
      <th align="right" nowrap="nowrap">$ <?php echo number_format($rc_a1);  ?></th>
      <th align="right" nowrap="nowrap">$ <?php echo number_format($rc_a2);  ?></th>
      <th align="right" nowrap="nowrap" class="no_mostrar">&nbsp;</th>
    </tr>
</tbody>
</table>


<br />
<h4>Relacion de Creditos</h4>
<table width="100%" border="1" cellpadding="2" cellspacing="2" class="gridtable" id="filtros">
<thead>
    <tr class="ui-jqgrid-titlebar ui-widget-header  ">
        <th>N&uacute;mero <br />Credito</th>
        <th>Cliente</th>
        <th>Fecha</th>
        <th>Capital</th>
        <th>Valor<br />Cuotas</th>
        <th>Numero<br />Cuotas</th>
      <th>Total</th>
        <th class="no_mostrar">Opciones</th>
    </tr>
</thead>
<tbody>
<?php 
$c_a=0;$c_a1=0;$c_a2=0;$c_a3=0;
?>
<?php foreach($detalles_creditos as $detalles): ?>
    <tr>
        <td align="left" nowrap="nowrap"><?php echo $detalles->prefijo.$detalles->consecutivo; ?></td>
        <td align="left" nowrap="nowrap"><?php echo $detalles->razon_social; ?></td>
        <td align="left" nowrap="nowrap"><?php echo $detalles->fecha; ?></td>
        <td align="right" nowrap="nowrap">$ <?php echo number_format($detalles->capital);       $c_a +=$detalles->capital; ?></td>
        <td align="right" nowrap="nowrap">$ <?php echo number_format($detalles->valor_cuotas);  $c_a1+=$detalles->valor_cuotas;?></td>
      <td align="left" nowrap="nowrap"><?php echo $detalles->cuotas; ?></td>
        <td align="right" nowrap="nowrap">$ <?php echo number_format($detalles->total_credito); $c_a2+=$detalles->total_credito;?></td>
      <td align="center" nowrap="nowrap" class="no_mostrar"><?php echo Tag::linkTo("creditos/show/$detalles->id",Tag::image("iconos/Visa.png","border: 0","width: 32px"),"target: _blank"); ?></td>
    </tr>
   
<?php endforeach; ?>    
  <tr>
      <th colspan="3" align="right" nowrap="nowrap">Totales</th>
      <th align="right" nowrap="nowrap">$ <?php echo number_format($c_a);  ?></th>
      <th align="right" nowrap="nowrap">$ <?php echo number_format($c_a1);  ?></th>
      <th align="right" nowrap="nowrap">&nbsp;</th>
      <th align="right" nowrap="nowrap">$ <?php echo number_format($c_a2);  ?></th>
      <th align="right" nowrap="nowrap" class="no_mostrar">&nbsp;</th>
    </tr>
</tbody>
</table>

<br />
<h4>Relacion de Egresos</h4>
<table width="100%" border="1" cellpadding="2" cellspacing="2" class="gridtable" id="filtros">
<thead>
    <tr class="ui-jqgrid-titlebar ui-widget-header  ">
        <th>N&uacute;mero <br />Egreso</th>
        <th>Fecha</th>
        <th>Descripcion</th>
        <th>Valor<br />Cuotas</th>
        <th class="no_mostrar">Opciones</th>
    </tr>
</thead>
<tbody>
<?php 
$e_a=0;
?>
<?php foreach($detalles_egresos as $detalles): ?>
    <tr>
        <td align="left" nowrap="nowrap"><?php echo $detalles->prefijo.$detalles->consecutivo; ?></td>
        <td align="left" nowrap="nowrap"><?php echo $detalles->fecha; ?></td>
        <td align="left" nowrap="nowrap"><?php echo $detalles->concepto; ?></td>
        <td align="right" nowrap="nowrap">$ <?php echo number_format($detalles->total*$detalles->multiplica); $e_a2+=($detalles->total*$detalles->multiplica);?></td>
      <td align="center" nowrap="nowrap" class="no_mostrar"><?php echo Tag::linkTo("egresos/show/$detalles->id",Tag::image("iconos/Visa.png","border: 0","width: 32px"),"target: _blank"); ?></td>
    </tr>
   
<?php endforeach; ?>    
  <tr>
      <th colspan="3" align="right" nowrap="nowrap">Totales</th>
      <th align="right" nowrap="nowrap">$ <?php echo number_format($e_a);  ?></th>
      <th align="right" nowrap="nowrap" class="no_mostrar">&nbsp;</th>
    </tr>
</tbody>
</table>
<br />
<h4>Resumen</h4>
<table width="100%" border="1" cellpadding="2" cellspacing="2" class="gridtable" id="filtros">
<thead>
    <tr class="ui-jqgrid-titlebar ui-widget-header  ">
        <th>Documento</th>
        <th>Valor</th>
    </tr>
</thead>
<tbody>

   <tr>
      <td align="left" nowrap="nowrap"><strong>ANTICIPO</strong></td>
      <td align="right" nowrap="nowrap">$ <?php echo number_format($a_a);  ?></td>
    </tr>
    <tr>
      <td align="left" nowrap="nowrap"><strong>RECIBOS DE CAJA</strong></td>
      <td align="right" nowrap="nowrap">$ <?php echo number_format($rc_a2);  ?></td>
    </tr>
    <tr>
      <td align="left" nowrap="nowrap"><strong>CREDITOS</strong></td>
      <td align="right" nowrap="nowrap">$ <?php echo number_format($c_a2*(-1));  ?></td>
    </tr>
    <tr>
      <td align="left" nowrap="nowrap"><strong>EGRESOS</strong></td>
      <td align="right" nowrap="nowrap">$ <?php echo number_format($e_a*(-1));  ?></td>
    </tr>
   

  <tr>
      <th align="right" nowrap="nowrap">Totales Dinero Efectivo</th>
      <th align="right" nowrap="nowrap">$ <?php echo number_format($a_a + $rc_a - $c_a - $e_a);  ?></th>
    </tr>
</tbody>
</table>


<?php if($_REQUEST["print"]=="pdf"){ 

$content = ob_get_clean();
 
$content2 = "<page backtop='7mm' backbottom='7mm' backleft='10mm' backright='10mm'> 
				  <page_header> 
					   ".Session::get("nombre_empresa")."
				  </page_header> 
				  <page_footer> 
					   Reporte Generado por: <a href='www.dydsoluciones.net'>dydsoluciones.net</a> fecha: ".date("Y-m-d H:i:s")."
				  </page_footer> 
					 $content
				</page> ";
	
	
	$path = $_SERVER['DOCUMENT_ROOT']; 
	require($path.core::getInstancePath()."public/html2pdf/html2pdf.class.php");
		try
		{
			$html2pdf = new HTML2PDF('L', 'A4', 'es',array(mL, mT, mR, mB));
			$html2pdf->writeHTML($content2);
			$html2pdf->Output('Reporte_ListadoRecibosCaja.pdf');
		
		}
		catch(HTML2PDF_exception $e) {
			echo $e;
			exit;
		}
	
} ?>

