<?php //echo view::getContent(); 

if(isset($_REQUEST["print"])){ 

	if($_REQUEST["print"]=="pdf"){ 
		ob_start(); 
	}
	
	if($_REQUEST["print"]=="html" || $_REQUEST["print"]=="pdf" || $_REQUEST["print"]=="excel"){?>
    		<style>

			/*Estilo para las tablas en los reportes*/
			table.gridtable {
				font-family: arial;
				font-size:11px;
				color:#333333;
				border-width: 1px;
				border-color: #217ec4;
				border-collapse: collapse;
				border-style: solid;
			}
			table.gridtable th {
				border-width: 1px;
				padding: 8px;
				border-style: solid;
				border-color: #217ec4;
				background-color: #70a9d2;
			}
			table.gridtable td {
				border-width: 1px;
				padding: 8px;
				border-style: solid;
				border-color: #217ec4;
				background-color: #e8f4fd;
			}
			
			</style>
	<?php } 
	
	if($_REQUEST["print"]=="excel"){
		header("Content-type: application/vnd.ms-excel; name='excel'");
		header("Content-Disposition: filename=ListadoCartera.xls");
		header("Pragma: no-cache");
		header("Expires: 0");	
	} 
	
	
?>
<table width="100%" border="1" cellpadding="1" cellspacing="1" class="gridtable" >
    <tr >
      <th colspan="10">Informe Listado Cartera</th>
    </tr>
    <tr >
      <th colspan="10"><?php echo Session::get("nombre_empresa"); ?></th>
    </tr>
    <tr >
      <th colspan="10">Reporte Impreso el d&iacute;a <?php echo date("Y-m-d"); ?> </th>
    </tr>
    <tr >
      <th colspan="10">Filtrado por:</th>
    </tr>
    <tr >
      <th width="25%" align="left">Identificaci&oacute;n:</th>
      <th width="75%" colspan="9" align="left"><?php echo $_REQUEST["nit"] ?></th>
    </tr>
    <tr >
      <th align="left">Nombre</th>
      <th colspan="9" align="left"><?php echo $_REQUEST["nombre"] ?></th>
  </tr>
    <tr >
      <th align="left">Fecha Desde:</th>
      <th colspan="9" align="left"><?php echo $_REQUEST["desde"] ?> Fecha Hasta: <?php echo $_REQUEST["hasta"] ?></th>
    </tr>
    <tr >
      <th align="left">Cobrador: </th>
      <th colspan="9" align="left"><?php echo $_REQUEST["cobradores"] ?></th>
    </tr>
</table>	 
<?php } ?>
<table width="100%" border="1" cellpadding="2" cellspacing="2" class="gridtable" id="filtros">
<thead>
    <tr class="ui-jqgrid-titlebar ui-widget-header  ">
        <th>C&oacute;digo</th>
        <th>Nombres</th>
        <th>Direcci&oacute;n Casa</th>
        <th>Total Cr&eacute;dito</th>
        <th>Pagado</th>
        <th>Saldo</th>
        <th>Saldo Capital</th>
        <th class="oculto">Ver Cr&eacute;dito</th>
        <th class="oculto">Ver Cuotas</th>
        <th class="oculto">Ver Pagos</th>
    </tr>
</thead>
<tbody>
<?php 
$a=0;$a1=0;$a2=0;$a3=0;
?>
<?php foreach($detalles as $detalles): ?>
    <tr>
        <td align="left" nowrap="nowrap"><?php echo $detalles->id; ?></td>
        <td align="left" nowrap="nowrap"><?php echo $detalles->razon_social; ?></td>
        <td align="left" nowrap="nowrap"><?php echo $detalles->direccion; ?></td>
        <td align="left" nowrap="nowrap">$ <?php echo number_format($detalles->valor_total);                       $a+=$detalles->valor_total; ?></td>
        <td align="left" nowrap="nowrap">$ <?php echo number_format($detalles->pagado);                            $a1+=$detalles->pagado;?></td>
        <td align="left" nowrap="nowrap">$ <?php echo number_format($detalles->valor_total+$detalles->pagado);     $a2+=$detalles->valor_total+$detalles->pagado;?></td>
        <td align="left" nowrap="nowrap">$ <?php echo number_format($detalles->capital+$detalles->capital_pagado); $a3+=$detalles->capital+$detalles->capital_pagado;?></td>
        <td align="left" nowrap="nowrap" class="oculto"><?php echo Tag::linkTo("creditos/show/$detalles->creditos_id",Tag::image("iconos/Visa.png","border: 0","width: 32px"),"target: _blank"); ?></td>
        <td align="left" nowrap="nowrap" class="oculto"><?php echo Tag::image("iconos/Visa.png","border: 0","width: 32px","id: a$detalles->creditos_id","onclick: ver_cuotas($detalles->clientes_id,$detalles->creditos_id)"); ?></td>
        <td align="left" nowrap="nowrap" class="oculto"><?php echo Tag::image("iconos/Folder.png","border: 0","width: 32px","id: b$detalles->creditos_id","onclick: ver_pagos($detalles->creditos_id)"); ?></td>
    </tr>
   
<?php endforeach; ?>    

  <tr>
      <th align="left" nowrap="nowrap">&nbsp;</th>
      <th align="left" nowrap="nowrap">&nbsp;</th>
      <th align="left" nowrap="nowrap">&nbsp;</th>
      <th align="left" nowrap="nowrap">$ <?php echo number_format($a);  ?></th>
      <th align="left" nowrap="nowrap">$ <?php echo number_format($a1);  ?></th>
      <th align="left" nowrap="nowrap">$ <?php echo number_format($a2);  ?></th>
      <th align="left" nowrap="nowrap">$ <?php echo number_format($a3);  ?></th>
      <th align="left" nowrap="nowrap" class="oculto">&nbsp;</th>
      <th align="left" nowrap="nowrap" class="oculto">&nbsp;</th>
      <th align="left" nowrap="nowrap" class="oculto">&nbsp;</th>
   </tr>
    
    
</tbody>
</table>

<?php if($_REQUEST["print"]=="pdf"){ 

$content = ob_get_clean();
 
$content2 = "<page backtop='7mm' backbottom='7mm' backleft='10mm' backright='10mm'> 
				  <page_header> 
					   ".Session::get("nombre_empresa")."
				  </page_header> 
				  <page_footer> 
					   Reporte Generado por: <a href='www.dydsoluciones.net'>dydsoluciones.net</a> fecha: ".date("Y-m-d H:i:s")."
				  </page_footer> 
					 $content
				</page> ";
	
	
	$path = $_SERVER['DOCUMENT_ROOT']; 
	require($path.core::getInstancePath()."public/html2pdf/html2pdf.class.php");
		try
		{
			$html2pdf = new HTML2PDF('L', 'A4', 'es',array(mL, mT, mR, mB));
			$html2pdf->writeHTML($content2);
			$html2pdf->Output('Reporte_ListadoCartera.pdf');
		}
		catch(HTML2PDF_exception $e) {
			echo $e;
			exit;
		}
	
} ?>


<div id="div_ver_pagos" style="width:950px; height:600px"></div>
<script>

jQuery(document).ready(function(e) {
	jQuery("#div_ver_pagos").dialog(
			{ autoOpen: false 
				,width: 900
 			    ,height: 800
				,title: " Pagos Realizados " 
				,modal: true
				,buttons: {
					"Cerrar": function() {
							jQuery( this ).dialog( "close" );
						}
				}
	 });
  
});

</script>
