<?php //echo view::getContent(); 

if(isset($_REQUEST["print"])){ 

	if($_REQUEST["print"]=="pdf"){ 
		ob_start(); 
	}
	
	if($_REQUEST["print"]=="html" || $_REQUEST["print"]=="pdf" || $_REQUEST["print"]=="excel"){?>
    		<style>

			/*Estilo para las tablas en los reportes*/
			table.gridtable {
				font-family: arial;
				font-size:11px;
				color:#333333;
				border-width: 1px;
				border-color: #217ec4;
				border-collapse: collapse;
				border-style: solid;
			}
			table.gridtable th {
				border-width: 1px;
				padding: 8px;
				border-style: solid;
				border-color: #217ec4;
				background-color: #70a9d2;
			}
			table.gridtable td {
				border-width: 1px;
				padding: 8px;
				border-style: solid;
				border-color: #217ec4;
				background-color: #e8f4fd;
			}
			
			</style>
	<?php } 
	
	if($_REQUEST["print"]=="excel"){
		header("Content-type: application/vnd.ms-excel; name='excel'");
		header("Content-Disposition: filename=ListadoReferencias.xls");
		header("Pragma: no-cache");
		header("Expires: 0");	
	} 
	
	
?>

<table width="100%" border="1" cellpadding="1" cellspacing="1" class="gridtable" >
    <tr >
      <th colspan="7">Informe Listado de Referencias</th>
    </tr>
    <tr >
      <th colspan="7"><?php echo Session::get("nombre_empresa"); ?></th>
    </tr>
    <tr >
      <th colspan="7">Reporte Impreso el d&iacute;a <?php echo date("Y-m-d"); ?> </th>
    </tr>
    <tr >
      <th colspan="7">Filtrado por:</th>
    </tr>
    <tr >
      <th width="25%" align="left">Identificaci&oacute;n:</th>
      <th width="75%" colspan="6" align="left"><?php echo $_REQUEST["nit"] ?></th>
    </tr>
    <tr >
      <th align="left">Nombre</th>
      <th colspan="6" align="left"><?php echo $_REQUEST["nombre"] ?></th>
  </tr>
    <tr >
      <th align="left">Direcci&oacute;n </th>
      <th colspan="6" align="left"><?php echo $_REQUEST["direccion"] ?></th>
    </tr>
</table>	 
<?php } 

			$condicion1 ="";
			$condicion2 ="";
			$condicion3 ="";
			
			$condicion4 ="";
			$condicion5 ="";
			
			$condicion6 =" group by c.razon_social, c.nit";
			
			$db = DbBase::rawConnect();
			$sql = "SELECT c.razon_social, c.nit, c.direccion, c.telefono, 
			c.celular, d.departamento,m.municipio FROM `clientes` c, clientes c2, departamentos d, municipios m
            WHERE c.id = c2.referencia_id AND c.departamentos_id = d.id
			AND c.municipios_id = m.id
			AND d.id = m.departamentos_id";
			
			if($_REQUEST["nit"]!=''){ $condicion1 = " and c.nit like '%".$_REQUEST["nit"]."%'"; 
			}
			if($_REQUEST["nombre"]!=''    ){ $condicion2 = " and c.razon_social like '%".str_replace(" ","%",$_REQUEST["nombre"])."%'"; 
			}
			if($_REQUEST["direccion"]!='' ){ $condicion3 = " and c.direccion like '%".str_replace(" ","%",$_REQUEST["direccion"])."%'"; 
			}
			
			if($_REQUEST["departamentos_id"]!='' ){ $condicion4 = " and c.departamentos_id = '".$_REQUEST["departamentos_id"]."'"; 
			}
			if($_REQUEST["municipios_id"]!=''){ $condicion5 = " and c.municipios_id = '".$_REQUEST["municipios_id"]."'"; 
			}
			
			$detalles=$db->query($sql.$condicion1.$condicion2.$condicion3.$condicion4.$condicion5.$condicion6);
		
		
?>

<table width="100%" border="1" cellpadding="1" cellspacing="1" class="gridtable" >
    <tr class="ui-jqgrid-titlebar ui-widget-header  ">
        <th>C&oacute;digo</th>
        <th>Nombres</th>
        <th>Direcci&oacute;n Casa</th>
        <th>Tel&eacute;fono</th>
        <th>Celular</th>
        <th>Departamento</th>
        <th>Municipio</th>
    </tr>
<tbody>
<?php while($row =$db->fetchArray($detalles)){ ?>
    <tr>
        <td align="left" ><?php echo $row[nit]; ?></td>
        <td align="left" ><?php echo $row[razon_social]; ?></td>
        <td align="left" ><?php echo $row[direccion]; ?></td>
        <td align="left" ><?php echo $row[telefono]; ?></td>
        <td align="left" ><?php echo $row[celular]; ?></td>
        <td align="left" ><?php echo $row[departamento]; ?></td>
        <td align="left" ><?php echo $row[municipio]; ?></td>
    </tr>
<?php } ?>    
</tbody>
</table>

<?php if($_REQUEST["print"]=="pdf"){ 

$content = ob_get_clean();
 
$content2 = "<page backtop='7mm' backbottom='7mm' backleft='10mm' backright='10mm'> 
				  <page_header> 
					   ".Session::get("nombre_empresa")."
				  </page_header> 
				  <page_footer> 
					   Reporte Generado por: <a href='www.dydsoluciones.net'>dydsoluciones.net</a> fecha: ".date("Y-m-d H:i:s")."
				  </page_footer> 
					 $content
				</page> ";
	
	
	$path = $_SERVER['DOCUMENT_ROOT']; 
	require($path.core::getInstancePath()."public/html2pdf/html2pdf.class.php");
		try
		{
			$html2pdf = new HTML2PDF('L', 'A4', 'es',array(mL, mT, mR, mB));
			$html2pdf->writeHTML($content2);
			$html2pdf->Output('Reporte_Referencias.pdf');
		}
		catch(HTML2PDF_exception $e) {
			echo $e;
			exit;
		}
	
} ?>

