<?php echo view::getContent(); ?>
<table width="100%" border="1" cellpadding="2" cellspacing="2" class="ui-corner-all ui-content" id="filtros">
<thead>
    <tr class="ui-jqgrid-titlebar ui-widget-header  ">
        <th>Codigo</th>
        <th>Numero Recibo</th>
        <th>Cliente</th>
        <th>Fecha</th>
        <th>Cobrador</th>
        <th>Capital Prestado</th>
        <th>Numero Cuotas</th>
        <th>Valor Cuotas</th>
        <th>Total Credito</th>
        <th class="oculto">Ver</th>
    </tr>
</thead>
<tbody>
<?php 
$a=0;$a1=0;$a2=0;$a3=0;
?>
<?php foreach($detalles as $detalles): ?>
    <tr>
        <td align="left" ><?php echo $detalles->id; ?></td>
        <td align="left" ><?php echo $detalles->prefijo.$detalles->consecutivo; ?></td>
        <td align="left" ><?php echo $detalles->nombre; ?></td>
        <td align="left" ><?php echo $detalles->fecha; ?></td>
        <td align="left" ><?php echo $detalles->razon_social; ?></td>
        <td align="right" >$ <?php echo number_format($detalles->capital);       $a+=$detalles->capital; ?></td>
        <td align="right" ><?php echo $detalles->cuotas;   ?></td>
        <td align="right" >$ <?php echo number_format($detalles->valor_cuotas);  $a1+=$detalles->valor_cuotas;?></td>
        <td align="right" >$ <?php echo number_format($detalles->total_credito); $a2+=$detalles->total_credito;?></td>
        <td align="right"  class="oculto"><?php echo Tag::linkTo("creditos/show/$detalles->id",Tag::image("iconos/Visa.png","border: 0","width: 32px"),"target: _blank"); ?></td>
    </tr>
   
<?php endforeach; ?>    
  <tr>
      <th colspan="5" align="right" >Totales</th>
      <th align="right" >$ <?php echo number_format($a);  ?></th>
      <th align="right" >&nbsp;</th>
      <th align="right" >$ <?php echo number_format($a1);  ?></th>
      <th align="right" >$ <?php echo number_format($a2);  ?></th>
      <th align="right"  class="oculto">&nbsp;</th>
   </tr>
</tbody>
</table>