<h4>REPORTE LISTADO DE DEUDORES</h5>

<table width="400px" cellpadding="2" cellspacing="2" class="ui-widget ui-widget-content ui-corner-all ui-dialog-titlebar ui-widget-header ui-helper-clearfix ui-front">
      <tr>
        <td align="center"><?php echo Tag::linkTo(Router::getController()."/print_jaspertDeudores",Tag::image("iconos/pdf.png","width: 50px"),"target: _blank"); ?></td>
      </tr>
      <tr>
        <td align="center">Listado General de Deudores</td>
      </tr>
</table>

<div id="mensajes"></div>
