<h4>Extracto Resumen</h5>
<?php echo Tag::formRemote(Router::getController()."/detalle_extracto_resumen", "update: mensajes", "id: fx","name: fx"); ?>

<table width="400px" cellpadding="2" cellspacing="2" class="ui-widget ui-widget-content ui-corner-all ui-dialog-titlebar ui-widget-header ui-helper-clearfix ui-front">
      <tr>
            <td align="center">
                Fecha Corte: <?php echo Tag::textField("fecha","size: 20","value: ".date("Y-m-d")); ?>
                <?php //echo "Fecha Corte del Informe: ".date("Y-m-d"); ?>
            </td>
      </tr>
      <tr>
            <td align="center">
                <button id="enviar">Enviar Consulta</button>
                <?php //echo Tag::linkTo(Router::getController()."/print_jaspertExtractoResumen/?fecha=".date("Y-m-d"),Tag::image("iconos/pdf.png","width: 50px"),"target: _blank"); ?>
           </td>
      </tr>
      <tr>
        <td align="center">Listado Extracto Resumen</td>
      </tr>
</table>

<?php echo Tag::endForm(); ?>
<div id="mensajes"></div>
<?php echo view::getContent(); ?>