
 <h1>Modulo de Reportes</h1>   	

<table align="center" width="100%" border="1" cellspacing="2" cellpadding="2">

 

  <tr>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("reports/clientes",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("reports/deudores",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("reports/solicitud",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>
    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("reports/cxc",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("reports/creditos",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

  </tr>

  <tr>

    <td height="30" align="center" valign="middle">Clientes</td>

    <td height="30" align="center" valign="middle">Deudores</td>

    <td height="30" align="center" valign="middle">Solicitud</td>
    <td align="center" valign="middle">Cartera</td>

    <td height="30" align="center" valign="middle">Cr&eacute;ditos</td>

  </tr>
</table>