
<table width="100%" border="0">
  <tr>
    <td width="17%">Escoja el mes</td>
    <td width="83%"><?php $meses = array(
							
							'1' => 'ENERO',
							'2' => 'FEBRERO',
							'3' => 'MARZO',
							'4' => 'ABRIL',
							'5' => 'MAYO',
							'6' => 'JUNIO',
							'7' => 'JULIO',
							'8' => 'AGOSTO',
							'9' => 'SEPTIEMBRE',
							'10' => 'OCTUBRE',
							'11' => 'NOVIEMBRE',
							'12' => 'DICIEMBRE'
							
							);
							echo Tag::selectStatic("meses", $meses, 'useDummy: yes');
					?>
</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
