<h4>REPORTE LISTADO DE REFERENCIAS</h5>

<?php echo Tag::formRemote(Router::getController()."/detalle_referencias", "update: resultado", "id: fx","name: fx"); ?>

<table id="filtros" width="100%" class="ui-corner-all ui-content">
<thead>
    <tr class="ui-jqgrid-titlebar ui-widget-header  ">
        <th colspan="4">Filtros</th>
    </tr>
</thead>
<tbody>
    <tr>
        <th>Identificaci&oacute;n</th>
        <td colspan="3"><input type="number" id="nit" name="nit" size="30"  /></td>
    </tr>
    <tr>
        <th>Busqueda por Nombre</th>
        <td><input type="text" id="nombre" name="nombre" size="50" /></td>
        <th>Busqueda por Direcci&oacute;n</th>
        <td><input type="text" id="direccion" name="direccion" size="50" /></td>
    </tr>
    <tr>
        <th>Departamento</th>
        <td><?php  echo Tag::textFieldExt("departamentos","campo: departamento","size: 10"); ?></td>
        <th>Municipio</th>
        <td><?php  echo Tag::textFieldExt("municipios","campo: municipio","size: 10"); ?></td>
    </tr>
    <tr>
      <th colspan="4"><button type="submit" id="guardar" name="guardar">Enviar</button></th>
    </tr>
</tbody>
</table>

<?php echo Tag::endForm() ?>

<div id="resultado" style="min-height:400px; max-height:500px; overflow:auto;" ></div>

<br />
<!--
<table width="400px" cellpadding="2" cellspacing="2" class="ui-widget ui-widget-content ui-corner-all ui-dialog-titlebar ui-widget-header ui-helper-clearfix ui-front">
      <tr>
        <td align="center"><?php //echo Tag::linkTo(Router::getController()."/print_jaspertClientes",Tag::image("iconos/pdf.png","width: 50px"),"target: _blank"); ?></td>
      </tr>
      <tr>
        <td align="center">Listado General de Clientes</td>
      </tr>
</table>
-->
<button type="button" id="imprimir" name="imprimir">Imprimir</button>

<button type="button" id="imprimir2" name="imprimir2">Excel</button>

<button type="button" id="imprimir3" name="imprimir3">Pdf</button>

<div id="mensajes"></div>


<script>
	
jQuery(document).ready(function(e) {
    jQuery("#imprimir").click(function(e) {
        e.preventDefault();
		var data = jQuery("#fx").serialize();
		url = "<?php echo core::getInstancePath(); ?>reports/detalle_referencias/?"+data+"&print=html";
	    window.open(url, '_blank');
    });
	
	 jQuery("#imprimir2").click(function(e) {
        e.preventDefault();
		var data = jQuery("#fx").serialize();
		url = "<?php echo core::getInstancePath(); ?>reports/detalle_referencias/?"+data+"&print=excel";
	    window.open(url, '_blank');
    });
	
	jQuery("#imprimir3").click(function(e) {
        e.preventDefault();
		var datos = jQuery("#fx").serialize();
		url = "<?php echo core::getInstancePath(); ?>reports/detalle_referencias/?"+datos+"&print=pdf";
	    window.open(url, '_blank');
		/*var datos = jQuery("#fx").serialize();
				var jqXHR = jQuery.ajax({
						url:"<?php //echo core::getInstancePath(); ?>reports/detalle_clientes/?"+datos+"&print=pdf",
						type:"POST",
						data: datos,
							fail:function(){
								alert("error");
							},
							error:function(jqXHR,textStatus,errorThrown){
								alert("error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
							}
				});

		 jqXHR.done(function(datos){
			//url = "<?php //echo core::getInstancePath(); ?>reports/generarpdf/?"+data+"&print=pdf";
	    	//window.open(url, '_blank');
			
				var jqXHR2 = jQuery.ajax({
					url:"<?php echo core::getInstancePath(); ?>reports/generapdf/",
					type:"POST",
					dataType:"pdf",
					data:{ 
							print: "pdf",
							html: datos,
							title: "Reportes",
							url: "www.dydsoluciones.net",
							author: "dydsoluciones.net"
						},
						fail:function(jqXHR,textStatus,errorThrown){
							alert("error erro 2 "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
						},
						error:function(jqXHR,textStatus,errorThrown){
							alert("error error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
						}
				});
				
				jqXHR2.done(function(data){
					jQuery("#resultado").html(data);
					//url = "<?php //echo $_SERVER['DOCUMENT_ROOT'].core::getInstancePath(); ?>public/temp/Reportes.pdf";
			    	//window.open(url, '_blank');
				}); // jqXHR2
			});// jqXHR*/

	    });//imprimir 3
});
  

</script>
