<?php echo View::getContent(); ?>
<br />
<br />
<?php echo Tag::formRemote(Router::getController()."/valida", "update: mensajes", "id: fx","name: fx"); ?>

<table width="50%" align="center" title="Inicio de Sesion" class="login"> 
 <thead >
   <tr>
      <th colspan="5" class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix" align="left"><?php echo Tag::image("iconos/clientes.png", "width: 32", "height: 32", "border: 0", "alt: Imagen"); ?> INICIO DE SESSION            </th>
   </tr>
</thead>
<tbody>
    <tr>
      <td width="32%" align="right"><div align="right">Nombre de Usuario:</div></td>
      <td width="43%" align="left" colspan="3"><?php echo Tag::textField('login','size: 40') ?></td>		
</tr>
<tr>
  <td align="right"><div align="right">Password:</div></td>
      <td align="left" colspan="3"><?php echo Tag::passwordField('password','size: 40') ?></td>
</tr>
    <tr>
      <td><div align="right">Empresa</div></td>
      <td colspan="3" style="padding-left:10px"><?php $empresa = new Empresa(); echo Tag::select("empresa",$empresa->find(),'using: id,nombre_corto',"size: 40","style: width:200px"); ?></td>
    </tr>
    <tr>
      <th colspan="4"><button type="submit" id="inicio" name="inicio">Iniciar Sesion</button></th>
    </tr>
     <tr>
    <th colspan="3" class="lower" >
                <?php echo View::getContent(); ?>
                <?php foreach(View::getValidationMessages() as $message){
                        Flash::error($message->getMessage());
                     } ?>            
                <div id="mensajes"></div>
       </th>
   </tr>

</tbody>
</table>
</div>
  

<!-- Begin Page Content -->
<!--<div id="container">
    <form>
        <label for="username">Username:</label>
        <input type="text" id="username" name="username">
        <label for="password">Password:</label>
        <input type="password" id="password" name="password">
        <div id="lower">
            <input type="submit" value="Login">
        </div><!--/ lower-->
<!--    </form>
</div><!--/ container-->
<!-- End Page Content -->

<?php echo Tag::endForm(); ?>





