<form id="egresos" name="egresos">
<table width="100%" border="0" align="center" cellpadding="2" cellspacing="4">
  <thead >
	<tr>
    	<th colspan="2" class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix" align="left"><?php echo $tipo_documento; echo " - "; echo $tipo_documento_nombre;  ?></th>
  	</tr>
</thead>

  <tr>
    <td width="18%" align="right">EMPRESA</td>
    <td>
        <?php echo Tag::hiddenField("id"); ?> 
		<?php echo Tag::hiddenField("tipo_documento_id"); ?> 
        <?php echo Tag::hiddenField("empresa_id"); ?> 
        <?php echo Tag::hiddenField("prefijo2"); ?> 
        <?php echo Tag::hiddenField("consecutivo"); ?> 
        <?php echo Tag::hiddenField("anulado"); ?> 
		<?php echo Tag::textField("nombre_empresa","size: 30","readOnly: readOnly","style: background: #cccccc;"); ?>       </td>
  </tr>
  
   <tr>
    <td align="right">COBRADORES:</td>
    <td align="left">
	<?php echo Tag::textFieldExt("cobradores","size: 4","readOnly: readOnly","style: background: #cccccc;"); ?>         </tr>
  <!--<tr>
     <td align="right" valign="top">BANCO</td>
     <td><?php //echo Tag::textFieldExt("bancos","size: 4","readOnly: readOnly","style: background: #cccccc;"); ?></td>
     <td colspan="3"><button id="buscar_bancos" type="button">Buscar</button>
	     </td>
  </tr>-->
  <tr>
    <td align="right" valign="top">FECHA</td>
    <td><?php echo Tag::textField("fecha","size: 20"); ?></td>
    </tr>
  <tr>
    <td align="right" valign="top">HORA</td>
    <td><?php echo Tag::textField("hora","size: 20"); ?></td>
  </tr>
  <tr>
    <td align="right" valign="top">FORMA DE PAGO</td>
    <td>
    	<select id="forma_pago_id">
    <?php 
		$fp = new FormaPago();
		foreach($fp->find() as $fp):
	?>
    	<option value="<?php echo $fp->id; ?>"><?php echo $fp->forma_pago; ?></option>
     <?php endforeach; ?>   
     </select>
    </td>
    </tr>
  <tr>
    <td align="right" valign="top">CHEQUE</td>
    <td><?php echo Tag::textField("chuque","size: 50"); ?></td>
    </tr>
</table>

<table id="grid_egresos"></table>
<div id="pagegresos"></div>
  

<button id="agregar_item" type="button">Agregar</button>

<button id="modificar_item" type="button">Modificar</button>

<button id="borrar_item" type="button">Borrar</button>

 <br />

<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" id="f3">
  <tr>
    <td width="50%">&nbsp;</td>
    <th align="right">CANTIDAD TOTAL </th>
    <td><?php echo Tag::textField("total","size: 12"); ?></td>
  </tr>
</table>

	<div align="center">
    	<button id="guardar" type="button">Guardar</button>
        <button id="cancelar" type="button">Cancelar</button>
    </div>

<p>&nbsp;</p>

<div id="mensajes"></div>

</form>

<div title="Agergar Producto a la Compra" id="dialogo_agregar_item">
	
 <table width="90%" cellpadding="2" cellspacing="2" align="center">
        
        <tr>
   	       <td>Compra Mercancia</td>
            <td>
            	<input type="hidden" readonly="readonly" size="2" id="tmp_idtemp" name="tmp_idtemp" />
                <input type="text" readonly="readonly" size="2" id="tmp_cxp_id" name="tmp_cxp_id" />
            </td>
            <td><input type="text"  id="tmp_factura" name="tmp_factura"/> <button id="buscar_cxp" type="button">Buscar</button></td>
        </tr>
        <tr>
       	    <td>Concepto</td>
            <td colspan="2"><input type="text"  id="tmp_concepto"  name="tmp_concepto" size="40"/></td>
        </tr>
        <tr>
   	      <td>Valor</td>
           <td colspan="2"><input type="text"  id="tmp_valor" name="tmp_valor" value="0" size="10" /></td>
        </tr>
        <tr>
       	    <td>Suma/Resta</td>
            <td colspan="2">
            	<select id="tmp_multiplica">
                	<option value="1">SUMA</option>
                    <option value="-1">RESTA</option>
                </select>
            </td>
        </tr>
    </table>
    
</div>


<script type="text/javascript">



jQuery(document).ready(function(){
	
	if( jQuery( "#tmp_multiplica"  ) ){ jQuery( "#tmp_multiplica"  ).chosen({ disable_search_threshold: 5, width: "250px", Height: "150px" });   }
	if( jQuery( "#forma_pago_id"   ) ){ jQuery( "#forma_pago_id"   ).chosen({ disable_search_threshold: 5, width: "250px", Height: "150px" });   }
	if( jQuery( "#buscar_item"     ) ){ jQuery( "#buscar_item"     ).button({ icons: {primary:'ui-icon ui-icon-circle-check' ,secondary:'ui-icon-triangle-1-s'}       });   }
	if( jQuery( "#agregar_item"    ) ){ jQuery( "#agregar_item"    ).button({ icons: {primary:'ui-icon ui-icon-circle-check' ,secondary:'ui-icon-triangle-1-s'}       });   }
	if( jQuery( "#modificar_item"  ) ){ jQuery( "#modificar_item"  ).button({ icons: {primary:'ui-icon ui-icon-circle-check' ,secondary:'ui-icon-triangle-1-s'}       });   }
	if( jQuery( "#borrar_item"     ) ){ jQuery( "#borrar_item"     ).button({ icons: {primary:'ui-icon ui-icon-circle-minus' ,secondary:'ui-icon ui-icon-closethick'} });   }
	
	jQuery("#forma_pago_id").val("EF");
	jQuery("#tmp_multiplica").val("1");
	
var detalles = [];

/*---------------------------------------------Guardar Egresos-------------------------------------------------------------------------*/

jQuery("#guardar").click(function(){
	guardar_egreso();
	
});

function guardar_egreso(){
		
	var srv = JSON.stringify(detalles);
		//	alert(jQuery("#forma_pago_id").val());
		var datos = jQuery("#egresos").serialize();
			datos += "&detalle="+srv;
		jQuery( "#progressbar" ).progressbar({ value: 50 });	
		var jqXHR = jQuery.ajax({
			type: "POST",
			url: "<?php echo core::getInstancePath(); ?>egresos/add",
			data: datos,

			success: function(data) {
				
				jQuery( '#mensajes' ).html("");
				jQuery( "#progressbar" ).progressbar({ value: 90 });
				jQuery( '#mensajes' ).html(data);
				
			},
			error: function(data) {
				jQuery('#dialogo_mensajes').html("Error Enviando parametros.....");
				jQuery( "#progressbar" ).progressbar({ value: 0 });
				jQuery('#dialogo_mensajes').dialog("open");
			}
		});
		
		 jqXHR.done(function(data){
			jQuery( "#progressbar" ).progressbar({ value: 0 });
		});
	
	}


/*------------------------------------------Agregar Item--------------------------------------------------------*/


	
jQuery("#dialogo_agregar_item").dialog(
	{ 
		autoOpen:false
		, width:700 
		, heigth:400 
		,modal: true
		,buttons:[
			{
				text:  "Escoger"
				,click: function(){
						//agregar_item(data);
						
						if(jQuery("#tmp_multiplica").val()==1){ suma = "SUMA"; }else{ suma="RESTA"; }
						detalles.push(
							{
								 id:            jQuery("#tmp_idtemp").val()
								,cxp_id:        jQuery("#tmp_cxp_id").val()
								,factura:       jQuery("#tmp_factura").val()
								,concepto:      jQuery("#tmp_concepto").val()
								,valor:         jQuery("#tmp_valor").val()
								,anulado:       "NO"
								,multiplica:    suma
								
							}
						);
						reload_grid();
						
						jQuery(this).dialog("close"); 
					}	
			}
		]
	});
//var srv = JSON.stringify(detalle_servicios)

jQuery("#agregar_item").click(function(){
	jQuery("#dialogo_agregar_item").dialog("open");
});


		

//detalles.push({id:1,referencia:123,nombre:"prueba",costo:10000,tarifaiva:16,iva:16000,descuento:20000,porc_desc:20,total:80000});
function reload_grid(){
		jQuery("#grid_egresos").jqGrid('setGridParam',
			{ 	datatype: 'local',
				data:detalles
			}).trigger("reloadGrid");
}





/*------------------------------------------------Configuracion Grilla----------------------------------------------------------*/
/*grib maestros de clientes*/
function config_gridCompras(){
		grid_fndCompras = jQuery("#grid_egresos").jqGrid({
							datatype:"local",
							data: detalles,
							height:200,
							rowNum:25,
							autowidth:true,
							pager:"#pagegresos",
							
							colNames:['Id','Cxp Id','Factura','Concepto','Valor','Anulado','Naturaleza'],
							colModel:[
							{   name:'id',          index:'id',          sorttype:'text'                        },
							{	name:'cxp_id',	    index:'cxp_id',	 sorttype:'integer'	                    },
							{	name:'factura',		index:'factura',	 sorttype:'text' },
							{	name:'concepto',    index:'concepto',    sorttype:'text',  width: 300 },
							{	name:'valor',		index:'valor',       sorttype:'double',	 formatter:"number" },
							{	name:'anulado',		index:'anulado',     sorttype:'text', },
							{	name:'multiplica',	index:'multiplica',     sorttype:'text', }
							],
							multiselect:false,
							caption:"Detalle Egresos",
							sortname: 'id', 
							viewrecords: true, 
							sortorder: "desc",
							
							ondblClickRow:function(rowid,iRow,iCol,e){
								
								/*var fila = $(this).jqGrid('getRowData',rowid);
								
								$("#cod_medico").val(fila['codigo'])
								$("#desc_medico").val(fila['nombres']+" "+fila['apellidos'])
								
								diag_fndMedicos.dialog("close")*/
							}
		});
	}

config_gridCompras();


});
</script>


