<table width="100%" cellpadding="0" cellspacing="0">
    	<tr>
         <th><div align="center">VALOR</div></th>
         <th width="60%"><div align="center">CONCEPTO</div></th>
         <th width="10%"><div align="center">ELIMINAR</div></th>
        </tr>
<?php 
$i=1;
$banco = new Bancos();
foreach($dtegresos as $dtegresos): 

?>        
        <tr>
            <td><?php echo Tag::hiddenField("id","size: 30","value: $dtegresos->id"); ?><?php echo $dtegresos->total; ?></td>
            <td><?php echo $dtegresos->concepto; ?></td>
            <td align="center" ><a href="javascript: void(0);"  onClick="eliminar('<?php echo $dtegresos->id; ?>');" id='bt<?php echo $dtegresos->id; ?>' name='bt<?php echo $dtegresos->id; ?>'> <?php echo Tag::image("64x64/Stop.png",'width: 20px'); ?> </a></td>
        </tr>
<?php endforeach; ?>
        </table>
