<?php
header('Cache-Control: no-cache, must-revalidate');
header('Expires: 0');
header('Content-Type: application/json');
$clientes = new Clientes();
$i=0;
$condicion=" 1= 1 ";
if(isset($_REQUEST["nit"])){
		$condicion=" and nit = '".$_REQUEST["nit"]."' ";
	}
foreach($clientes->find($condicion) as $clientes):
	$responce[]=array(
					"id"=>$clientes->id,
					"nit"=>$clientes->nit,
					"nombres"=>utf8_encode($clientes->nombre1." ".$clientes->nombre2." ".$clientes->apellido1." ".$clientes->apellido2),
					"direccion"=>$clientes->direccion,
					"telefono"=>$clientes->telefono ? is_null($clientes->telefono) : 0,
					"celular"=>$clientes->celular,
					"referencia_id"=>$clientes->referencia_id  ? is_null($clientes->telefono) : 0
				); 						
	$i++;
endforeach;
echo json_encode($responce);
		
?>			