<h4>FORMULARIO ELIMINAR USUARIOS DEL SISTEMA</h5>

<?php echo Tag::formRemote(Router::getController()."/delete", "update: mensajes", "id: fx","name: fx"); ?>
<br />
<table width="80%" height="160"  align="center" cellpadding="2" cellspacing="2">
 <tr>
    <th colspan="6">
    <?php echo Tag::hiddenField("id"); ?></th>
</tr>

  <tr>
    <td width="29%" align="right">Nombre Usuario</td>
    <td width="38%" align="left"><?php echo Tag::textField("username", "size: 25","maxlength: 20") ?></td>
    <td width="33%" align="left">&nbsp;</td>
  </tr>
  <tr>
    <td align="right">Clave</td>
    <td align="left"><?php echo Tag::PasswordField("password", "size: 25","maxlength: 20") ?></td>
    <td align="left">&nbsp;</td>
  </tr>
  <tr>
    <td align="right">Confirmar Clave</td>
    <td align="left"><?php echo Tag::PasswordField("confirmar", "size: 25","maxlength: 20") ?></td>
    <td align="left">&nbsp;</td>
  </tr>
  <tr>
    <td align="right">Nombre Completo</td>
    <td align="left" colspan="2"><?php echo Tag::textFieldExt("empleado","size: 10 ");?></td>

  </tr>
  <tr>
    <td align="right">Tipo de Usuario</td>
    <td align="left"><?php $rol = new Role();
      echo Tag::select('role',$rol->find(), 'using: role,role','useDummy=yes'); 
	  ?>    </td>
    <td align="left">&nbsp;</td>
  </tr>
  <tr>
   <td colspan="4" align="center" >
     		<button type="submit" id="enviar" name="enviar">Eliminar</button>
            <button type="button" id="cancelar" name="cancelar" onclick="doccancelar('<?php echo core::getInstancePath(); ?>','<?php echo Router::getController(); ?>');">Cancelar</button>
     </td>
   </tr>
</table>

<?php echo Tag::endForm() ?>

<div id="div_mensajes"></div>
<br />

<script>
	
	jQuery(document).ready(function(e) {
		
        jQuery("#id").attr("readOnly","ReadOnly");
		jQuery("#username").attr("readOnly","ReadOnly");
		jQuery("#password").attr("readOnly","ReadOnly");
		jQuery("#nombre_empleados").attr("readOnly","ReadOnly");
		jQuery("#empleado_id").attr("readOnly","ReadOnly");
		jQuery("#role").prop('disabled', true);
		
    });
	
</script>