<h4>FORMULARIO MODIFICAR USUARIOS DEL SISTEMA</h5>

<?php echo Tag::formRemote(Router::getController()."/update", "update: mensajes", "id: fx","name: fx"); ?>
<br />
<table width="80%" height="160"  align="center" cellpadding="2" cellspacing="2">
 <tr>
    <th colspan="6" class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix" align="left">
    Agregar o Modificar Usuarios del Sistema
    <?php echo Tag::hiddenField("id"); ?>    </th>
</tr>

  <tr>
    <td width="29%" align="right">Nombre Usuario</td>
    <td width="38%" align="left"><?php echo Tag::textField("username", "size: 25","maxlength: 20") ?></td>
    <td width="33%" align="left">&nbsp;</td>
  </tr>
  <tr>
    <td align="right">Clave</td>
    <td align="left"><?php echo Tag::PasswordField("password", "size: 25","maxlength: 20") ?></td>
    <td align="left">&nbsp;</td>
  </tr>
  <tr>
    <td align="right">Confirmar Clave</td>
    <td align="left"><?php echo Tag::PasswordField("confirmar", "size: 25","maxlength: 20") ?></td>
    <td align="left">&nbsp;</td>
  </tr>
  <tr>
    <td align="right">Nombre Completo</td>
    <td align="left" colspan="2"><?php echo Tag::textFieldExt("empleado","size: 10 ");?></td>

  </tr>
  <tr>
    <td align="right">Tipo de Usuario</td>
    <td align="left"><?php $rol = new Role();
      echo Tag::select('role',$rol->find(), 'using: role,role','useDummy=yes'); 
	  ?>    </td>
    <td align="left">&nbsp;</td>
  </tr>
  <tr>
   <td colspan="4" align="center" >
     		<button type="submit" id="enviar" name="enviar">Modificar</button>
            <button type="button" id="cancelar" name="cancelar" onclick="doccancelar('<?php echo core::getInstancePath(); ?>','<?php echo Router::getController(); ?>');">Cancelar</button>
     </td>
   </tr>
</table>

<?php echo Tag::endForm() ?>

<div id="div_mensajes"></div>
<br />
