<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
 <style media="print" type="text/css" >
   .oculto{ 
      display:none; 
    }

</style>
</head>

<body style="margin:0px; padding:0px; font-size:10pt;font-family:Arial, Helvetica, sans-serif;">
<?php 

$emp = new Empresa();
$empresa = $emp->findFirst(" id = '$encabezado->empresa_id' ");
$nombre_empresa = $empresa->nombre_empresa;
$regimen=$empresa->regimen_id;
$nit=$empresa->nit;
$consecutivo = str_pad(intval($encabezado->consecutivo), 4, '0', STR_PAD_LEFT);
$consecutivo=$encabezado->prefijo." ".$consecutivo;
$direccion=$empresa->direccion;
$telefonos=$empresa->telefonos;
$celular=$empresa->celular;
$web=$empresa->web;
$correo=$empresa->correo;
$nit_cliente=$cli->nit;
$razon_social=$cli->razon_social;
$direccion_cliente=$cli->direccion_casa;
$telefonos_cliente=$cli->telefono1. " ".$cli->telefono2;
$fecha=$encabezado->fecha;
$observaciones=$encabezado->observaciones;
$mostrar_logo=$tipo_documento->mostrar_logo;
$logo=$tipo_documento->logo;
$ancho=$tipo_documento->ancho;
$alto=$tipo_documento->alto;
$font=$tipo_documento->font;
$size=$tipo_documento->size;
$tipo_letra=$tipo_documento->tipo_letra;
$papel=$tipo_documento->papel;
$entro = '';
$limite = $total_page;
?>
<br /><br /><br /><br /><br />
<br />
<br /><br /><br /><br />
<table width="100%" border="0" cellspacing="0" cellpadding="1">
<thead>
	<tr>
   	  <td colspan="6">
       	  <table width="100%">
           		  <tr>
                      <th width="16%" rowspan="4" align="left" valign="top">
                          <?php
                            if($mostrar_logo=='1'){
                               echo "<img src=\"".core::getInstancePath()."public/img/$logo\" width=\"125px\" />";
                            }
                            ?>    </th>
              <th colspan="3" rowspan="4" align="center" scope="col">
					  			<?php if($regimen == 1 ){ echo ""; }else{ echo $nombre_empresa; } ?><br />
                                <?php if($regimen == 1 ){ echo ""; }else{ echo $nit; } ?><br />
                                <?php echo $direccion;  ?><br />             
                                <?php echo "TEL: ".$telefonos." CEL: ".$celular; ?><br /> 
								<?php $w = '';
                                    if( $web != ''){
                                        $w=" WEB: ".$web;
                                    }
                                    if( $correo !=''){
                                        $w=" CORREO: ".$correo;
                                    }
                                    echo $w;?><br />                         </th>
                      <th width="21%" scope="col">EGRESO NUMERO</th>
            </tr>
                    <tr>
                      <th align="center"><?php echo $consecutivo; ?></th>
                    </tr>
                    <tr>
                      <th>&nbsp;</th>
                    </tr>
                    <tr>
                      <th>&nbsp;</th>
                    </tr>
          </table>      </td>
    </tr>
  <tr>
    <th colspan="6" scope="row">&nbsp;</th>
  </tr>
  <tr>
    <th width="1%" scope="row" align="right">&nbsp;</th>
    <th width="19%" scope="row" align="right">PAGADO A </th>
    <td width="35%">&nbsp;&nbsp;<?php echo  " ".$razon_social;?></td>
    <td width="26%">CEDULA: &nbsp;&nbsp;<?php echo " ".$nit_cliente; ?></td>
    <td width="19%">&nbsp;</td>
    </tr>
  <tr>
    <th scope="row" align="right">&nbsp;</th>
    <th scope="row" align="right">DIRECCION</th>
    <td>&nbsp;&nbsp;</td>
    <td>FECHA &nbsp;&nbsp;<?php echo $fecha;?></td>
    <td>&nbsp;</td>
    </tr><?php echo $direccion_cliente;?>
  <tr>
    <th scope="row" align="right">&nbsp;</th>
    <th scope="row" align="right">FORMA DE PAGO</th>
    <td>&nbsp;&nbsp;<?php $f = new FormaPago(); echo $f->findFirst(" id = '$encabezado->forma_pago_id' ")->forma_pago; ?></td>
    <td colspan="2">CHEQUE:  &nbsp;&nbsp;<?php echo $encabezado->cheque;?> BANCO:  &nbsp;&nbsp;
      <?php $b = new Bancos(); echo $b->findFirst(" id = '$encabezado->bancos_id' ")->descripcion; ?></td>
    </tr>
  <tr>
    <th colspan="6" scope="row">&nbsp;</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <th colspan="4" nowrap="nowrap" scope="row">CONCEPTO</th>
    <th nowrap="nowrap">VALOR</th>
    </tr>
<?php 
    $i=0;
	$c=0;
	$a1 = 0;
	$a2 = 0;
	$a3 = 0;
	$s = 0;
foreach($paginate->items as $det):
	$c++; $i++; 
?>  
  <tr>
    <th colspan="4" align="left" scope="row"><?php echo $det->concepto;?></th>
    <td align="center"><?php echo "$".number_format($det->total,0,",",".");  $a1 += $det->total; ?></td>
    </tr>
<?php 
	endforeach;

 ?>
  <tr>
    <td colspan="3" align="left" scope="row">
    	SON:&nbsp;&nbsp;
        <?php 
			$currency = new Currency(new Locale('es_CO'));
			$letras = $currency->getMoneyAsText($a1,false);
			$letras =  str_replace("COLOMBIANOS",'',$letras); 
			$letras =  str_replace("colombianos",'',$letras); 
			echo $letras;
			//print $currency->getMoneyAsText($a3);
			
			 ?>
    	&nbsp;&nbsp;</td>
    <td colspan="2" align="right" scope="row">TOTAL CANCELADO&nbsp;&nbsp;&nbsp;&nbsp; <?php echo "$".number_format($a1,0,",","."); ?></td>
    <td width="0%" align="left" scope="row">&nbsp;</td>
  </tr>
  <tr>
    <th colspan="6" align="left" scope="row">RECIBIDO: _______________________</th>
    </tr>
  </tbody>
</table>
<div align="center" class="oculto">
<table border="1" cellpadding="1" cellspacing="2">
	<tr>
    	<?php for($i=1;$i<$paginate->total_pages;$i++){ ?>
        	<th style="border:#000000 1px solid;"><?php echo Tag::linkTo("print/recibos_caja_html/$encabezado->id/?pagina=$i&totalizar=$totalizar"," ---   Pagina $i"); ?> </th>
    	<?php } ?>
        <th style="border:#000000 1px solid;"><?php echo Tag::linkTo("print/recibos_caja_html/$encabezado->id/?pagina=".$paginate->last."&totalizar=$totalizar"," ---   Pagina $paginate->last "); ?></th>
    </tr>
    <tr>
    	<td colspan="<?php echo $paginate->total_pages; + 1 ?>"><?php echo $paginate->current; ?> PAGINA DE <?php echo $paginate->total_pages; ?></td>
    </tr>
    <tr>
      <td colspan="<?php echo $paginate->total_pages; + 1 ?>" align="center"><?php echo Tag::button("Imprimir","onClick: window.print();"); ?><?php echo Tag::button("Regresar","onClick: window.close();"); ?></td>
    </tr>
</table>    
</div>
<?php echo view::getContent(); ?>
</body>
</html>
