<?php echo Tag::formRemote(Router::getController()."/add", "update: mensajes", "id: fx","name: fx"); ?>

<h1>AGREGAR <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?></h1>

<h4>
	<?php echo $tipo_documento; 
	echo " - "; 
	echo $tipo_documento_id; 
	echo "EMPRESA: ".Tag::textField("nombre_empresa","size: 30","readOnly: readOnly","style: background: #cccccc;","value: ".Session::get("nombre_empresa")); ?>
</h4>

<table width="100%" border="0" align="center" cellpadding="2" cellspacing="4">

   <tr>
     
     <td align="right"><div align="right">CLIENTE:</div></td>
     
     <td align="left" valign="middle" id="aclientes">
       
      <?php echo Tag::textFieldExt("clientes","size: 30"); ?>
   </tr>

  <tr>

    <!--<td align="right"><div align="right">SOLICITUD:</div></td>-->

    <td align="left" valign="middle" id="aclientes">
    
       <?php echo Tag::hiddenField("id"); ?> 

		<?php echo Tag::textField("tipo_documento_id"); ?> 

        <?php echo Tag::hiddenField("empresa_id"); ?> 

        <?php echo Tag::hiddenField("prefijo"); ?> 

        <?php echo Tag::hiddenField("consecutivo"); ?> 

	<?php //echo Tag::textFieldExt("solicitud","size: 30"); ?>

  </tr>

  <tr>

    <td align="right" valign="top">FECHA</td>

    <td><?php echo Tag::textField("fecha","size: 20"); ?></td>

  </tr>

  <tr>
    <td align="right" valign="top">FECHA CUOTA</td>
    <td><?php echo Tag::textField("fecha_cuota","size: 20"); ?></td>
  </tr>
  <tr>

    <td align="right" valign="top">OBSERVACIONES</td>

    <td><?php echo Tag::textArea("observaciones","size: 20"); ?></td>

    </tr>
    
     <tr>
       <td align="right" valign="top">PORCENTAJE</td>
       <td>
		   	<?php echo Tag::numericField("porcentaje","size: 4","maxlenth: 2"); ?>% 
	        <!--Capital Prestado--><?php //echo Tag::numericField("capital","size: 20","maxlenth: 100"); ?>
       </td>
     </tr>
     <tr>

    <td align="right" valign="top">TOTAL DE CREDITO</td>

    	<td>
         	
            <?php echo Tag::numericField("total_credito","size: 20"); ?>
            NUMERO DE CUOTAS
            <?php echo Tag::numericField("numero_cuotas","size: 10"); ?>
            VALOR CUOTAS
			<?php echo Tag::numericField("valor_cuotas","size: 20"); ?>
           	<button id="generar" type="button" name="generar">Generar</button>
        </td>

    </tr>


</table>

<table id="grid_<?php echo Router::getController(); ?>"></table>

<div id="pag<?php echo Router::getController(); ?>"></div>

  

  <button id="agregar_item" type="button">Agregar</button>

 <!-- <button id="buscar_item" type="button">Buscar</button> -->

  <button id="modificar_item" type="button">Modificar</button>

<button id="borrar_item" type="button">Borrar</button>

 <br />

 <br /> <br /> <br /> <br />
<!--
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" id="f3">

  <tr>

    <td width="50%">&nbsp;</td>

    <th align="right">CANTIDAD TOTAL </th>

    <td><?php //echo Tag::textField("total","size: 12"); ?></td>

  </tr>

</table>

-->

	<div align="center">

    	<button id="guardar" type="button">Guardar</button>

        <button id="cancelar" type="button">Cancelar</button>

    </div>



<p>&nbsp;</p>


<?php echo Tag::endForm(); ?>
<div id="mensajes"></div>
<?php echo view::getContent(); ?>



<div title="Agergar Cuota" id="dialogo_agregar_item">

	

    <table width="70%" cellpadding="2" cellspacing="2" align="center">

        
 		<tr>

       	    <td>Codigo</td>

            <td colspan="2"><input type="text"  id="tmp_codigo" name="tmp_codigo"/></td>

        </tr>

        <tr>

       	    <td>Vencimiento</td>

            <td colspan="2"><input type="text"  id="tmp_vencimiento"  name="tmp_vencimiento"/></td>

        </tr>
        
        <tr>

       	    <td>Valor</td>

            <td colspan="2"><input type="text"  id="tmp_valor"  name="tmp_valor"/></td>

        </tr>

       

    </table>



</div>





<div title="Modificar Cuota" id="dialogo_modificar_item">

	

    <table width="70%" cellpadding="2" cellspacing="2" align="center">

       <tr>

   	      <td>Id</td>

           <td colspan="2"><input type="text"  id="tmp_id_mod" name="tmp_id_mod" size="30" readonly="readonly" /></td>

        </tr>

       <tr>

       	    <td>Codigo</td>

            <td colspan="2"><input type="text"  id="tmp_codigo_mod" name="tmp_codigo_mod"/></td>

        </tr>

        <tr>

       	    <td>Vencimiento</td>

            <td colspan="2"><input type="text"  id="tmp_vencimiento_mod" name="tmp_vencimiento_mod"/></td>

        </tr>
        
        <tr>

       	    <td>Valor</td>

            <td colspan="2"><input type="text"  id="tmp_valor_mod"  name="tmp_valor_mod"/></td>

        </tr>

       

    </table>



</div>


<script type="text/javascript">
jQuery(document).ready(function(){
	

<?php 
echo "jQuery(\"#clientes_id\").val($clientes_id);\n";
echo "jQuery(\"#solicitud_id\").val($solicitud_id);\n";

//echo "jQuery(\"#observaciones\").val('paso por aqui');\n";
?>	

	
	if( jQuery( "#fecha_cuota"          ) ){ jQuery( "#fecha_cuota"      ).datepicker({ dateFormat: "yy-mm-dd"}); 	}
	if( jQuery( "#tmp_vencimiento"      ) ){ jQuery( "#tmp_vencimiento"      ).datepicker({ dateFormat: "yy-mm-dd"}); 	}
	if( jQuery( "#tmp_vencimiento_mod"  ) ){ jQuery( "#tmp_vencimiento_mod"      ).datepicker({ dateFormat: "yy-mm-dd"}); 	}
	
	if( jQuery( "#buscar_item"     ) ){ jQuery( "#buscar_item"        ).button({ icons: {primary:'ui-icon ui-icon-circle-check' ,secondary:'ui-icon-triangle-1-s'}       });   }
	if( jQuery( "#agregar_item"     ) ){ jQuery( "#agregar_item"        ).button({ icons: {primary:'ui-icon ui-icon-circle-check' ,secondary:'ui-icon-triangle-1-s'}       });   }
	if( jQuery( "#modificar_item"    ) ){ jQuery( "#modificar_item"       ).button({ icons: {primary:'ui-icon ui-icon-circle-check' ,secondary:'ui-icon-triangle-1-s'}       });   }
	if( jQuery( "#borrar_item"   ) ){ jQuery( "#borrar_item"      ).button({ icons: {primary:'ui-icon ui-icon-circle-minus' ,secondary:'ui-icon ui-icon-closethick'} });   }

	
 <?php 
		$entidad = new creditos();
		
		foreach( $entidad->getPrimaryKeyAttributes() as $filas):
			echo "jQuery(\"#$filas\").attr(\"readonly\",\"readonly\");\n";
		endforeach;	
		
		foreach( $entidad->getNonPrimaryKeyAttributes() as $filas):
				foreach( $entidad->getNonPrimaryKeyAttributes() as $filas2):
					if($filas==$filas2){ echo "jQuery(\"#$filas2\").attr(\"required\",\"required\");\n"; break;} 
				endforeach;	
				
		endforeach;	
		
	?> 	

/*inicializamos variable local*/
var detalles = [];


/*--------------------------------------------Guardar <?php echo Router::getController(); ?> Especiales--------------------------------------------------------------*/

jQuery("#guardar").click(function(){
		guardar_compra();
});

function guardar_compra(){
	var datos = "";
	var srv = JSON.stringify(detalles);
	//datos = jQuery("#compras").serialize();
	jQuery( "#progressbar" ).progressbar({ value: 50 });	
		//$('#resumen').html('Cargando....');
		var jqXHR = jQuery.ajax({
			type: "POST",
			url: "<?php echo core::getInstancePath(); ?><?php echo Router::getController(); ?>/add",
			data: {
					id:                 jQuery("#id").val(),
					tipo_documento_id:  jQuery("#tipo_documento_id").val(),
					empresa_id:         jQuery("#empresa_id").val(),
					prefijo:            jQuery("#prefijo2").val(),
					consecutivo:        jQuery("#consecutivo").val(),
					solicitud_id:       jQuery("#solicitud_id").val(),
					clientes_id:        jQuery("#clientes_id").val(),
					fecha:              jQuery("#fecha").val(),
					fecha_cuota:        jQuery("#fecha_cuota").val(),
					porcentaje:         jQuery("#porcentaje").val(),
					capital:            jQuery("#capital").val(),
					observaciones:      jQuery("#observaciones").val(),
					valor_cuotas:       jQuery("#valor_cuotas").val(),
					numero_cuotas:      jQuery("#numero_cuotas").val(),
					total_credito:      jQuery("#total_credito").val(),
					detalles: srv
			},

			success: function(data) {
				jQuery( '#mensajes' ).html("");
				jQuery( "#progressbar" ).progressbar({ value: 90 });
				jQuery( '#mensajes' ).html(data);

			},

			error: function(data) {
				jQuery('#dialogo_mensajes').html("Error Enviando parametros.....");
				jQuery( "#progressbar" ).progressbar({ value: 0 });
				jQuery('#dialogo_mensajes').dialog("open");
			}
		});

		 jqXHR.done(function(data){
			jQuery( "#progressbar" ).progressbar({ value: 0 });
		});

}





/*--------------------------------------------------Agregar item---------------------------------------------------------------------------------*/



function agregar_item(data){

var existe = false;   
for(i=0;i<detalles.length;i++) {  
	
	if (detalles[i]["codigo"] == data["codigo"]) {  
	   alert("Codigo debe ser unico para este credito");  
	   existe = true;  
	 }   
	if (detalles[i]["codigo"] == data["codigo"] && detalles[i]["vencimiento"] == data["vencimiento"]) {  
	   alert("Articulo ya esta en este Credito");  
	   existe = true;  
	 }   

 }  

if (!existe) {  

	detalles.push(
		{
			 id:data["id"]
			,codigo:data["codigo"]
			,valor:data["valor"]
			,vencimiento:data["vencimiento"]
			,anulado: "NO"

		}

	);

	reload_grid();

}  



}


 jQuery("#agregar_item").click(function(e){
	 e.preventDefault();
	if( jQuery("#bodegas_id").val() != '' ){
		jQuery("#dialogo_agregar_item").dialog("open");
		//reload_grid();
	}else{
		jQuery("#dialogo_mensajes").html("");
		jQuery("#dialogo_mensajes").html("Por Favor escoja una Bodega");
		jQuery("#dialogo_mensajes").dialog("open");
	}
});


 jQuery("#numero_cuotas").blur(function(e){
	 e.preventDefault();
		if(jQuery("#total_credito").val()!=''){
			jQuery("#valor_cuotas").val(jQuery("#total_credito").val()/jQuery("#numero_cuotas").val())
		}
});	


 jQuery("#valor_cuotas").blur(function(e){
	 e.preventDefault();
		if(jQuery("#numero_cuotas").val()!=''){
			jQuery("#valor_cuotas").val(jQuery("#total_credito").val()/jQuery("#numero_cuotas").val())
		}
});	

jQuery("#total_credito").focus(function(e){
	 e.preventDefault();
		if(jQuery("#total_credito").val()!='' && jQuery("#numero_cuotas").val()!=''){
			jQuery("#valor_cuotas").val(jQuery("#total_credito").val()/jQuery("#numero_cuotas").val())
		}
});	

 jQuery("#generar").click(function(){
	if( jQuery("#valor_cuotas").val() != '' && jQuery("#numero_cuotas").val() != '' && jQuery("#fecha_cuota").val() != '') {
		calcular_items_all(jQuery("#numero_cuotas").val(),jQuery("#valor_cuotas").val(),jQuery("#fecha_cuota").val())
		//reload_grid();
	}else{
		jQuery("#dialogo_mensajes").html("");
		jQuery("#dialogo_mensajes").html("Valor Cuotas, Numero Cuotas y Fecha Cuota son Requeridos");
		jQuery("#dialogo_mensajes").dialog("open");
	}
});	

function calcular_items(numero_cuotas,valor_cuotas,fecha_cuota){
//borrando java
detalles.length = 0;
detalles=[];
reload_grid();

var existe = false;   
for(i=1;i<=numero_cuotas;i++) {  

	 var jqXHR = jQuery.ajax({
				url:"<?php echo core::getInstancePath(); ?><?php echo Router::getController(); ?>/calcular_items/",
				type:"POST",
				dataType:"json",
				data:{
						codigo:        i,
						valor:         valor_cuotas,
						vencimiento:   fecha_cuota,
					},
					fail:function(){
						alert("error");
					},
					error:function(jqXHR,textStatus,errorThrown){
						alert("error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
					}
		});

	 jqXHR.done(function(data){
		agregar_item(data);
	});
					
 }  //fin for


}



function calcular_items_all(numero_cuotas,valor_cuotas,fecha_cuota){
//borrando java
detalles.length = 0;
detalles=[];
reload_grid();

var existe = false;   

	var jqXHR = jQuery.ajax({
		url:"<?php echo core::getInstancePath(); ?><?php echo Router::getController(); ?>/calcular_items_all/",
		type:"POST",
		dataType:"json",
		data:{
				numero_cuotas: numero_cuotas,
				valor:         valor_cuotas,
				vencimiento:   fecha_cuota,
			},
			fail:function(){
				alert("error");
			},
			error:function(jqXHR,textStatus,errorThrown){
				alert("error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
			}
	});
	
	jqXHR.done(function(data){
		//jQuery("#mensajes").html(data);
		//alert("LLego Aqui");
		jQuery.each(data, function(i, item) {
			detalles.push(
					{
						 id:data[i].id
						,codigo:data[i].codigo
						,valor:data[i].valor
						,vencimiento:data[i].vencimiento
						,anulado: data[i].anulado
					}
				);
		});
		reload_grid();
	});
	
}
	 

/*	 

//autocomplete con json	

jQuery( "#tmp_valor" ).autocomplete({

	source: "<?php// echo core::getInstancePath(); ?>kardex/autocompletejson",

	minLength: 2,

	select: function( event, ui ) {

		 //alert("Has seleccionado: " + ui.item.value);

		 jQuery("#tmp_valor").val(ui.item.value)

		 jQuery("#tmp_codigo").val(ui.item.id);

		 jQuery("#tmp_codigo").val(ui.item.codigo);

	}

});

*/	


jQuery("#dialogo_agregar_item").dialog(

{ 

	autoOpen:false
	, width:600 
	, heigth:400 
	,modal: true
	,buttons:[
		{
			text:  "Escoger"
			,click: function(){
					var jqXHR = jQuery.ajax({
							url:"<?php echo core::getInstancePath(); ?><?php echo Router::getController(); ?>/agregar_item/",
							type:"POST",
							dataType:"json",
							data:{
									codigo:        jQuery("#tmp_codigo").val(),
									valor:         jQuery("#tmp_valor").val(),
									vencimiento:   jQuery("#tmp_vencimiento").val(),
								},
								fail:function(){
									alert("error");
								},
								error:function(jqXHR,textStatus,errorThrown){
									alert("error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
								}
					});

					

					 jqXHR.done(function(data){

						agregar_item(data);

					});

					jQuery(this).dialog("close"); 

				}	

		}

	]

});



function reload_grid(){

	jQuery("#grid_<?php echo Router::getController(); ?>").jqGrid('setGridParam',

		{ 	datatype: 'local',

			data:detalles

		}).trigger("reloadGrid");

}



/*-----------------------------------------------------modificar item----------------------------------------------------------------------------*/

//agregar un item al vector json de items

function modificar_item(data,mod_id){

	for(i=0;i<detalles.length;i++){

			if(detalles[i].id==mod_id){

				detalles[i].id          = data["id"];
				detalles[i].codigo      = data["codigo"];
				detalles[i].valor       = data["valor"];
				detalles[i].vencimiento = data["vencimiento"];
				detalles[i].anulado     = data["anulado"];

			}

	}

	reload_grid();

}



//cuadro de dialogo de agregar item...	 

jQuery("#modificar_item").click(function(){

		toMod = jQuery("#grid_<?php echo Router::getController(); ?>").jqGrid('getGridParam','selrow');

		var sw = 0;

		for(i=0;i<detalles.length;i++){

			if(detalles[i].id==toMod){

				//alert("Lo Encontre: "+detalles[i].id + " SUBSTRING TEMP " + detalles[i].id.substring(0,4));

				if( detalles[i].anulado == "SI" ){

					alert("Elemento Anulado no se Puede Modificar");

					sw=1;

				}else{
					//alert("liena guardada en la base de datos anular");
					jQuery("#tmp_id_mod").val(detalles[i].id);
					jQuery("#tmp_codigo_mod").val(detalles[i].codigo);
					jQuery("#tmp_valor_mod").val(detalles[i].valor);
					jQuery("#tmp_vencimiento_mod").val(detalles[i].vencimiento);
					sw=0;

				}

			}

		}

		

		if(sw==0){

			jQuery("#dialogo_modificar_item").dialog("open");

		}

	//reload_grid();

});



	

jQuery("#dialogo_modificar_item").dialog(

{ 
	autoOpen:false
	, width:600 
	, heigth:400 
	,modal: true
	,buttons:[
		{
			text:  "Escoger"
			,click: function(){
					var mod_id =         jQuery("#tmp_id_mod").val();
					//alert(mod_id);
					var jqXHR = jQuery.ajax({

							url:"<?php echo core::getInstancePath(); ?><?php echo Router::getController(); ?>/agregar_item/",
							type:"POST",
							dataType:"json",
							data:{
									id:           jQuery("#tmp_id_mod").val(),
									codigo:       jQuery("#tmp_codigo_mod").val(),
									vencimiento:  jQuery("#tmp_vencimiento_mod").val(),
									valor:        jQuery("#tmp_valor_mod").val()

								}
								,
								fail:function(){
									alert("error");
								},
								error:function(jqXHR,textStatus,errorThrown){
									alert("error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
								}

					});

					 jqXHR.done(function(data){

						modificar_item(data,mod_id);

					});

					

					jQuery(this).dialog("close"); 

					

				}	

		}

	]

});







/*-------------------------------------------------------delete item----------------------------------------------------*/



var grid = jQuery("#grid_<?php echo Router::getController(); ?>"),

	delSettings = {

		afterShowForm: function (jQueryform) {

			// delete button: "#dData", cancel button: "#eData"

			jQuery("#dData", jQueryform.parent()).click();

		},

		// because I use "local" data I don't want to send the changes to the server

		// so I use "processing:true" setting and delete the row manually in onclickSubmit

		onclickSubmit: function (options) {

			var gridId = grid[0].id,

				gridP = grid[0].p,

				newPage = gridP.page,

				rowids = gridP.multiselect ? gridP.selarrrow : [gridP.selrow];



			// reset the value of processing option to true

			// because the value can be changed by jqGrid

			options.processing = true;



			// delete the row

			jQuery.each(rowids, function () {

				grid.jqGrid('delRowData', this);

				

			});

			jQuery.jgrid.hideModal("#delmod" + gridId,

								{ gb: "#gbox_" + gridId,

									jqm: options.jqModal,

									onClose: options.onClose });



			if (gridP.lastpage > 1) {// on the multipage grid reload the grid

				if (gridP.reccount === 0 && newPage === gridP.lastpage) {

					// if after deliting there are no rows on the current page

					// which is the last page of the grid

					newPage -= 1; // go to the previous page

				}

				// reload grid to make the row from the next page visable.

				grid.trigger("reloadGrid", [{ page: newPage}]);

			}



			return true;

		},

		processing: true

	};


//cuadro de dialogo de agregar item...	 

jQuery("#borrar_item").click(function(){

//jQuery("#dialogo_agregar_item").dialog("open");

if(confirm("Realmente Desea Borrar o Anular el Registro")){

	//var gr = jQuery("#grid_<?php echo Router::getController(); ?>").jqGrid('getGridParam','selrow');

	//jQuery("#grid_<?php echo Router::getController(); ?>").find("#"+gr).remove();

	toDelete = jQuery("#grid_<?php echo Router::getController(); ?>").jqGrid('getGridParam','selrow');

	var sw = 0;


	for(i=0;i<detalles.length;i++){

		if(detalles[i].id==toDelete){

			//alert("Lo Encontre: "+detalles[i].id + " SUBSTRING TEMP " + detalles[i].id.substring(0,4));

			if( detalles[i].id.substring(0,4) == 'temp' ){

				//alert("linea temporarl borrar");

				sw=0;

			}else{

				//alert("liena guardada en la base de datos anular");

				sw=1;

				detalles[i].anulado = "SI";

					

				}

		}

	}



	//alert(detalles["id"][toDelete]);

	//jQuery("#grid_<?php //echo Router::getController(); ?>").jqGrid('delGridRow',toDelete,myDelOptions);

	if(sw==0){

		

		if( toDelete != null ) {

			if(jQuery("#grid_<?php echo Router::getController(); ?>").delGridRow(toDelete,delSettings)){

				detalles = jQuery.grep(

							detalles, 

							function (item,index) { 

							  return item.id !=  toDelete; 

							});



			}else{

					alert("no borro nada");

				}

			//getSelectedRow();

		}else{ alert("Por favor seleccione una fila para borrar!"); }

	}else{

			//alert("anular");

			reload_grid();

		}

	//reload_grid();

}

});



/*------------------------------------------------ Configurar Grilla de Entradas especiales --------------------------------------------------------------------*/





/*grib maestros de clientes*/

function config_gridCompras(){

		grid_fndCompras = jQuery("#grid_<?php echo Router::getController(); ?>").jqGrid({
			datatype:"local",
			data: detalles,
			height:200,
			rowNum:25,
			autowidth:true,
			pager:"#pag<?php echo Router::getController(); ?>",
			colNames:['Id','Codigo','Valor','Vencimiento',"Anulado"],
			colModel:[
				{   name:'id',          index:'id',          sorttype:'text'                        },
				{	name:'codigo',	    index:'codigo',	     sorttype:'text'	                    },
				{	name:'valor',	    index:'valor',	     	 formatter:"number" },
				{	name:'vencimiento',	index:'vencimiento', sorttype:'text',    width: 300         },
				{	name:'anulado',		index:'anulado',  	 sorttype:'text',    width: 50          }
			],
			multiselect:false,
			caption:"Detalle <?php echo Router::getController(); ?>",
			sortname: 'vencimiento', 
			viewrecords: true, 
			sortorder: "desc",
			ondblClickRow:function(rowid,iRow,iCol,e){
				

			}
		});
	}


config_gridCompras();



jQuery("#generar").click();

});





	
</script>




